In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np

print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")

PyTorch version: 2.11.0+cu130
CUDA available: False


/home/sandeep/workspace/learn-ml/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py:180: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 12080). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at /pytorch/c10/cuda/CUDAFunctions.cpp:119.)
  return torch._C._cuda_getDeviceCount() > 0


# PyTorch Functions Comprehensive Reference
## Understanding PyTorch Under the Hood with Python API Examples

This notebook provides a comprehensive guide to PyTorch functions with practical Python examples showing how to call the raw PyTorch API.

# 1. Tensor Creation Functions

## Basic Tensor Creation

In [2]:
# torch.tensor() - Creates tensor from data
# Directly pass data to create a tensor
tensor_from_list = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)
print("torch.tensor([1, 2, 3, 4, 5]):")
print(tensor_from_list)

# torch.empty() - Allocates uninitialized tensor (faster, no zero-fill)
empty_tensor = torch.empty(2, 3)
print("\ntorch.empty(2, 3):")
print(empty_tensor)

# torch.zeros() - Creates tensor filled with zeros
zeros_tensor = torch.zeros(3, 4)
print("\ntorch.zeros(3, 4):")
print(zeros_tensor)

# torch.ones() - Creates tensor filled with ones
ones_tensor = torch.ones(2, 5)
print("\ntorch.ones(2, 5):")
print(ones_tensor)

# torch.full() - Creates tensor filled with specific value
full_tensor = torch.full((2, 3), 7.5)
print("\ntorch.full((2, 3), 7.5):")
print(full_tensor)

torch.tensor([1, 2, 3, 4, 5]):
tensor([1., 2., 3., 4., 5.])

torch.empty(2, 3):
tensor([[-9.8736e-01,  7.0065e-45,  2.3707e+30],
        [ 4.1017e-41,  2.3726e+30,  4.1017e-41]])

torch.zeros(3, 4):
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

torch.ones(2, 5):
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

torch.full((2, 3), 7.5):
tensor([[7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000]])


In [3]:
# _like variants - Create tensors with same shape as input
input_tensor = torch.randn(2, 3)
zeros_like = torch.zeros_like(input_tensor)
ones_like = torch.ones_like(input_tensor)
print("torch.zeros_like(input_tensor):")
print(zeros_like)

# torch.arange() - Create sequence of values
arange_tensor = torch.arange(0, 10, 2, dtype=torch.float32)
print("\ntorch.arange(0, 10, 2):")
print(arange_tensor)

# torch.linspace() - Create linearly spaced tensor
linspace_tensor = torch.linspace(0, 1, 5)
print("\ntorch.linspace(0, 1, 5):")
print(linspace_tensor)

# torch.logspace() - Create logarithmically spaced tensor
logspace_tensor = torch.logspace(0, 2, 5)
print("\ntorch.logspace(0, 2, 5) (base 10):")
print(logspace_tensor)

torch.zeros_like(input_tensor):
tensor([[0., 0., 0.],
        [0., 0., 0.]])

torch.arange(0, 10, 2):
tensor([0., 2., 4., 6., 8.])

torch.linspace(0, 1, 5):
tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

torch.logspace(0, 2, 5) (base 10):
tensor([  1.0000,   3.1623,  10.0000,  31.6228, 100.0000])


In [4]:
# Random Tensor Creation

# torch.rand() - Uniform random [0, 1)
rand_tensor = torch.rand(2, 3)
print("torch.rand(2, 3) - uniform [0, 1):")
print(rand_tensor)

# torch.randn() - Standard normal N(0,1)
randn_tensor = torch.randn(2, 3)
print("\ntorch.randn(2, 3) - standard normal:")
print(randn_tensor)

# torch.randint() - Random integers
randint_tensor = torch.randint(0, 10, (3, 4))
print("\ntorch.randint(0, 10, (3, 4)):")
print(randint_tensor)

# torch.normal() - Normal distribution with custom mean/std
normal_tensor = torch.normal(mean=2.0, std=0.5, size=(2, 3))
print("\ntorch.normal(mean=2.0, std=0.5, size=(2, 3)):")
print(normal_tensor)

# torch.eye() - Identity matrix
eye_tensor = torch.eye(3)
print("\ntorch.eye(3) - Identity matrix:")
print(eye_tensor)

torch.rand(2, 3) - uniform [0, 1):
tensor([[0.6075, 0.6030, 0.9839],
        [0.4704, 0.7665, 0.8764]])

torch.randn(2, 3) - standard normal:
tensor([[-0.5312,  0.1430, -0.8657],
        [ 1.9438,  1.2809,  0.1402]])

torch.randint(0, 10, (3, 4)):
tensor([[1, 9, 0, 4],
        [2, 6, 0, 3],
        [1, 1, 5, 1]])

torch.normal(mean=2.0, std=0.5, size=(2, 3)):
tensor([[2.3441, 1.1836, 2.3846],
        [2.8550, 1.4461, 2.0715]])

torch.eye(3) - Identity matrix:
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


# 2. Tensor Properties & Attributes

In [5]:
sample_tensor = torch.randn(3, 4, 5)

# Shape and size information
print("tensor.shape:", sample_tensor.shape)
print("tensor.size():", sample_tensor.size())
print("tensor.dim():", sample_tensor.dim())
print("tensor.numel():", sample_tensor.numel())
print("tensor.size(1):", sample_tensor.size(1))

# Data type and device
print("\ntensor.dtype:", sample_tensor.dtype)
print("tensor.device:", sample_tensor.device)
print("tensor.is_contiguous():", sample_tensor.is_contiguous())

# Gradient properties
grad_tensor = torch.randn(2, 3, requires_grad=True)
print("\ntensor.requires_grad:", grad_tensor.requires_grad)
print("tensor.is_leaf:", grad_tensor.is_leaf)
print("tensor.grad:", grad_tensor.grad)

# Data pointer (for C/C++ interop)
print("\ntensor.data_ptr():", sample_tensor.data_ptr())
print("tensor.storage():", sample_tensor.storage()[:5])

tensor.shape: torch.Size([3, 4, 5])
tensor.size(): torch.Size([3, 4, 5])
tensor.dim(): 3
tensor.numel(): 60
tensor.size(1): 4

tensor.dtype: torch.float32
tensor.device: cpu
tensor.is_contiguous(): True

tensor.requires_grad: True
tensor.is_leaf: True
tensor.grad: None

tensor.data_ptr(): 101119843458048


/tmp/ipykernel_379090/2632931430.py:23: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  print("tensor.storage():", sample_tensor.storage()[:5])


RuntimeError: slices are only supported in UntypedStorage.__getitem__

# 3. Tensor Reshaping & Manipulation

In [ ]:
# Shape modification
t = torch.randn(2, 3, 4)

# reshape() - Returns view or new tensor
reshaped = t.reshape(6, 4)
print("Original shape:", t.shape)
print("After reshape(6, 4):", reshaped.shape)

# view() - Returns view with different shape (must be contiguous)
viewed = t.view(-1)  # -1 means infer this dimension
print("After view(-1):", viewed.shape)

# unsqueeze() - Add dimension of size 1
unsqueezed = t.unsqueeze(0)
print("After unsqueeze(0):", unsqueezed.shape)

# squeeze() - Remove dimensions of size 1
squeezed = t.unsqueeze(-1).squeeze()
print("After unsqueeze then squeeze:", squeezed.shape)

# expand() - Broadcast to larger shape
expanded = torch.randn(1, 3, 4).expand(5, 3, 4)
print("After expand(5, 3, 4):", expanded.shape)

# transpose() - Swap two dimensions
transposed = t.transpose(0, 1)
print("After transpose(0, 1):", transposed.shape)

# permute() - Reorder all dimensions
permuted = t.permute(2, 0, 1)
print("After permute(2, 0, 1):", permuted.shape)

# flatten() - Flatten range of dimensions
flattened = t.flatten(start_dim=1)
print("After flatten(start_dim=1):", flattened.shape)

In [ ]:
# Concatenation and stacking
t1 = torch.randn(2, 3)
t2 = torch.randn(2, 3)

# torch.cat() - Concatenate along existing dimension
concatenated = torch.cat([t1, t2], dim=0)
print("torch.cat([t1, t2], dim=0):", concatenated.shape)

# torch.stack() - Stack along new dimension
stacked = torch.stack([t1, t2], dim=0)
print("torch.stack([t1, t2], dim=0):", stacked.shape)

# Splitting
t = torch.randn(4, 6)

# torch.split() - Split into chunks
split_tensors = torch.split(t, 2, dim=0)
print("torch.split(t, 2, dim=0) returns", len(split_tensors), "tensors")
print("First chunk shape:", split_tensors[0].shape)

# torch.chunk() - Split into roughly equal chunks
chunk_tensors = torch.chunk(t, 3, dim=1)
print("torch.chunk(t, 3, dim=1) returns", len(chunk_tensors), "tensors")

# repeat() - Repeat tensor
repeated = t1.repeat(2, 3)
print("t1.repeat(2, 3):", repeated.shape)

# 4. Mathematical Operations

In [ ]:
# Arithmetic operations
a = torch.tensor([1., 2., 3.])
b = torch.tensor([4., 5., 6.])

print("Addition: a + b =", a + b)
print("Subtraction: a - b =", a - b)
print("Multiplication: a * b =", a * b)
print("Division: b / a =", b / a)
print("Power: a ** 2 =", a ** 2)

# torch.add(), torch.mul(), etc.
print("\ntorch.add(a, b, alpha=2) =", torch.add(a, b, alpha=2))
print("torch.mul(a, 3) =", torch.mul(a, 3))

# Exponential and Logarithmic
x = torch.tensor([1., 2., 3.])
print("\ntorch.exp(x) =", torch.exp(x))
print("torch.log(x) =", torch.log(x))
print("torch.sqrt(x) =", torch.sqrt(x))

# Trigonometric
angles = torch.tensor([0., 1.57, 3.14])  # 0, pi/2, pi
print("\ntorch.sin(angles) =", torch.sin(angles))
print("torch.cos(angles) =", torch.cos(angles))

# Rounding and sign
y = torch.tensor([-2.3, -1.5, 0.0, 1.5, 2.3])
print("\ntorch.ceil(y) =", torch.ceil(y))
print("torch.floor(y) =", torch.floor(y))
print("torch.round(y) =", torch.round(y))
print("torch.sign(y) =", torch.sign(y))

# 5. Linear Algebra Operations

In [ ]:
# Matrix multiplication
mat1 = torch.randn(3, 4)
mat2 = torch.randn(4, 5)

# torch.mm() - Matrix-matrix multiplication
result_mm = torch.mm(mat1, mat2)
print("torch.mm(mat1, mat2):", result_mm.shape)

# torch.matmul() or @ operator - General matrix multiplication
result_matmul = torch.matmul(mat1, mat2)
result_at = mat1 @ mat2
print("torch.matmul(mat1, mat2):", result_matmul.shape)
print("mat1 @ mat2:", result_at.shape)

# Matrix-vector multiplication
vec = torch.randn(4)
result_mv = torch.mv(mat1, vec)
print("torch.mv(mat1, vec):", result_mv.shape)

# Batch matrix multiplication
batch1 = torch.randn(5, 3, 4)
batch2 = torch.randn(5, 4, 5)
result_bmm = torch.bmm(batch1, batch2)
print("torch.bmm(batch1, batch2):", result_bmm.shape)

# Outer product
v1 = torch.tensor([1., 2., 3.])
v2 = torch.tensor([4., 5.])
outer = torch.outer(v1, v2)
print("torch.outer(v1, v2):", outer.shape)

# Norms
m = torch.randn(3, 4)
norm_frobenius = torch.norm(m, p='fro')
norm_2 = torch.norm(m, p=2)
print("\ntorch.norm(m, p='fro'):", norm_frobenius.item())
print("torch.norm(m, p=2):", norm_2.item())

In [ ]:
# Determinant and Inverse
square_mat = torch.randn(4, 4)

# torch.det() - Determinant
det = torch.det(square_mat)
print("torch.det(square_mat):", det.item())

# torch.inverse() - Matrix inversion
inv = torch.inverse(square_mat)
print("torch.inverse(square_mat):", inv.shape)

# Verify A * A_inv ≈ I
identity_approx = square_mat @ inv
print("square_mat @ inv (should be ~identity):")
print(identity_approx.diagonal())

# torch.eig() - Eigenvalues and eigenvectors
eigenvalues, eigenvectors = torch.eig(square_mat, eigenvectors=True)
print("\ntorch.eig() eigenvalues shape:", eigenvalues.shape)
print("torch.eig() eigenvectors shape:", eigenvectors.shape)

# torch.qr() - QR decomposition
Q, R = torch.qr(torch.randn(5, 4))
print("\ntorch.qr() - Q shape:", Q.shape, ", R shape:", R.shape)

# torch.svd() - Singular Value Decomposition
U, S, V = torch.svd(torch.randn(4, 5))
print("torch.svd() - U shape:", U.shape, ", S shape:", S.shape, ", V shape:", V.shape)

# 6. Reduction Operations

In [ ]:
t = torch.randn(3, 4, 5)

# Sum operations
print("torch.sum(t):", torch.sum(t).item())
print("torch.sum(t, dim=0):", torch.sum(t, dim=0).shape)
print("torch.sum(t, dim=1, keepdim=True):", torch.sum(t, dim=1, keepdim=True).shape)

# Mean and other statistics
print("\ntorch.mean(t):", torch.mean(t).item())
print("torch.std(t):", torch.std(t).item())
print("torch.var(t):", torch.var(t).item())

# Min and Max
print("\ntorch.min(t):", torch.min(t).item())
print("torch.max(t):", torch.max(t).item())

# Min and Max with dimension
min_vals, min_indices = torch.min(t, dim=1)
print("torch.min(t, dim=1) values shape:", min_vals.shape)
print("torch.min(t, dim=1) indices shape:", min_indices.shape)

# argmax and argmin
argmax_result = torch.argmax(t, dim=2)
argmin_result = torch.argmin(t, dim=2)
print("\ntorch.argmax(t, dim=2):", argmax_result.shape)
print("torch.argmin(t, dim=2):", argmin_result.shape)

# Cumulative operations
simple = torch.tensor([1., 2., 3., 4., 5.])
print("\ntorch.cumsum(simple):", torch.cumsum(simple, dim=0))
print("torch.cumprod(simple):", torch.cumprod(simple, dim=0))

# 7. Activation Functions

In [ ]:
x = torch.randn(2, 4)

# ReLU - Rectified Linear Unit
relu_output = F.relu(x)
print("F.relu(x):", relu_output)

# Leaky ReLU - Allows small negative values
leaky_relu_output = F.leaky_relu(x, negative_slope=0.1)
print("\nF.leaky_relu(x, negative_slope=0.1):", leaky_relu_output)

# Sigmoid - Maps to [0, 1]
sigmoid_output = F.sigmoid(x)
print("\nF.sigmoid(x):", sigmoid_output)

# Tanh - Maps to [-1, 1]
tanh_output = F.tanh(x)
print("F.tanh(x):", tanh_output)

# ELU - Exponential Linear Unit
elu_output = F.elu(x)
print("\nF.elu(x):", elu_output)

# GELU - Gaussian Error Linear Unit (used in Transformers)
gelu_output = F.gelu(x)
print("F.gelu(x):", gelu_output)

# Softmax - Probability distribution
softmax_output = F.softmax(x, dim=1)
print("\nF.softmax(x, dim=1):", softmax_output)
print("Sum of each row (should be ~1):", softmax_output.sum(dim=1))

# Log Softmax - Numerically stable log(softmax())
log_softmax_output = F.log_softmax(x, dim=1)
print("\nF.log_softmax(x, dim=1):", log_softmax_output)

# Clamp - Clamp values to range
clamped = torch.clamp(x, min=-0.5, max=0.5)
print("\ntorch.clamp(x, min=-0.5, max=0.5):", clamped)

# 8. Loss Functions

In [ ]:
# Classification losses
logits = torch.randn(4, 3)  # 4 samples, 3 classes
targets = torch.tensor([0, 2, 1, 0])  # class labels

# Cross entropy loss - Most common for classification
ce_loss = F.cross_entropy(logits, targets)
print("F.cross_entropy(logits, targets):", ce_loss.item())

# NLL Loss - Negative Log Likelihood
log_probs = F.log_softmax(logits, dim=1)
nll_loss = F.nll_loss(log_probs, targets)
print("F.nll_loss(log_softmax(logits), targets):", nll_loss.item())

# Regression losses
predictions = torch.randn(5, 1)
targets_reg = torch.randn(5, 1)

# MSE Loss - Mean Squared Error
mse_loss = F.mse_loss(predictions, targets_reg)
print("\nF.mse_loss(predictions, targets):", mse_loss.item())

# L1 Loss
l1_loss = F.l1_loss(predictions, targets_reg)
print("F.l1_loss(predictions, targets):", l1_loss.item())

# Smooth L1 Loss - Huber Loss
smooth_l1_loss = F.smooth_l1_loss(predictions, targets_reg, beta=1.0)
print("F.smooth_l1_loss(predictions, targets):", smooth_l1_loss.item())

# Binary Cross Entropy
probs = torch.sigmoid(torch.randn(5))  # Probabilities [0, 1]
binary_targets = torch.randint(0, 2, (5,)).float()
bce_loss = F.binary_cross_entropy(probs, binary_targets)
print("\nF.binary_cross_entropy(probs, targets):", bce_loss.item())

# BCE with Logits (numerically stable)
logits_binary = torch.randn(5)
bce_logits_loss = F.binary_cross_entropy_with_logits(logits_binary, binary_targets)
print("F.binary_cross_entropy_with_logits(logits, targets):", bce_logits_loss.item())

# KL Divergence
input_dist = F.log_softmax(torch.randn(4, 3), dim=1)
target_dist = F.softmax(torch.randn(4, 3), dim=1)
kl_loss = F.kl_div(input_dist, target_dist)
print("\nF.kl_div(log_prob, prob):", kl_loss.item())

# 9. Neural Network Modules

In [ ]:
# Linear layer
linear = nn.Linear(10, 5)
x = torch.randn(2, 10)  # batch size 2, 10 features
output = linear(x)
print("nn.Linear(10, 5) output shape:", output.shape)
print("Linear weight shape:", linear.weight.shape)
print("Linear bias shape:", linear.bias.shape)

# Convolutional layer
conv2d = nn.Conv2d(in_channels=3, out_channels=16, kernel_size=3, stride=1, padding=1)
x_img = torch.randn(2, 3, 32, 32)  # batch=2, channels=3, H=32, W=32
conv_output = conv2d(x_img)
print("\nnn.Conv2d output shape:", conv_output.shape)

# Pooling
max_pool = nn.MaxPool2d(kernel_size=2, stride=2)
pooled = max_pool(conv_output)
print("nn.MaxPool2d output shape:", pooled.shape)

# Batch Normalization
batch_norm = nn.BatchNorm2d(16)
bn_output = batch_norm(conv_output)
print("\nnn.BatchNorm2d output shape:", bn_output.shape)

# Dropout
dropout = nn.Dropout(p=0.5)
x_dropout = torch.randn(3, 10)
dropout_output = dropout(x_dropout)
print("nn.Dropout output shape:", dropout_output.shape)

# Embedding layer
embedding = nn.Embedding(num_embeddings=100, embedding_dim=50)
indices = torch.randint(0, 100, (2, 10))  # 2 sequences of length 10
embedded = embedding(indices)
print("\nnn.Embedding output shape:", embedded.shape)

# Recurrent layer
lstm = nn.LSTM(input_size=20, hidden_size=50, num_layers=2)
x_seq = torch.randn(10, 2, 20)  # seq_len=10, batch=2, input_size=20
output, (h_n, c_n) = lstm(x_seq)
print("nn.LSTM output shape:", output.shape)
print("nn.LSTM hidden state shape:", h_n.shape)

# Multi-head Attention
attention = nn.MultiheadAttention(embed_dim=64, num_heads=8)
q = torch.randn(10, 2, 64)  # seq_len, batch, embed_dim
k = torch.randn(10, 2, 64)
v = torch.randn(10, 2, 64)
attn_output, attn_weights = attention(q, k, v)
print("\nnn.MultiheadAttention output shape:", attn_output.shape)

# 10. Optimizers & Learning Rate Schedulers

In [ ]:
# Create a simple model
model = nn.Sequential(
    nn.Linear(10, 20),
    nn.ReLU(),
    nn.Linear(20, 5)
)

# SGD optimizer - Stochastic Gradient Descent
optimizer_sgd = optim.SGD(model.parameters(), lr=0.01, momentum=0.9)
print("Created SGD optimizer with lr=0.01, momentum=0.9")

# Adam optimizer - Most popular
optimizer_adam = optim.Adam(model.parameters(), lr=0.001, betas=(0.9, 0.999))
print("Created Adam optimizer with lr=0.001")

# AdamW - Adam with weight decay
optimizer_adamw = optim.AdamW(model.parameters(), lr=0.001, weight_decay=0.01)
print("Created AdamW optimizer with lr=0.001, weight_decay=0.01")

# RMSprop - Root Mean Square Propagation
optimizer_rmsprop = optim.RMSprop(model.parameters(), lr=0.001)
print("Created RMSprop optimizer")

# Simple training loop example
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Generate dummy data
x = torch.randn(8, 10)
y = torch.randint(0, 5, (8,))

# Forward pass
output = model(x)
loss = criterion(output, y)

# Backward pass
optimizer.zero_grad()  # Clear gradients
loss.backward()  # Compute gradients
optimizer.step()  # Update parameters

print(f"\nTraining step example - Loss: {loss.item():.4f}")

# Learning Rate Schedulers
print("\n--- Learning Rate Schedulers ---")

# StepLR - Decay by factor every step_size epochs
scheduler_step = optim.lr_scheduler.StepLR(optimizer, step_size=10, gamma=0.1)
print("Created StepLR scheduler")

# CosineAnnealingLR - Cosine annealing schedule
scheduler_cosine = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=100)
print("Created CosineAnnealingLR scheduler")

# ReduceLROnPlateau - Reduce when metric plateaus
scheduler_plateau = optim.lr_scheduler.ReduceLROnPlateau(
    optimizer, mode='min', factor=0.1, patience=10
)
print("Created ReduceLROnPlateau scheduler")

print(f"\nCurrent learning rate: {optimizer.param_groups[0]['lr']}")

# 11. Autograd & Gradient Functions

In [ ]:
# Basic backpropagation
x = torch.tensor([2.0, 3.0], requires_grad=True)
y = torch.tensor([5.0, 7.0], requires_grad=True)

# Forward pass - build computational graph
z = (x ** 2).sum() + (y ** 2).sum()

print("z (result):", z.item())
print("x.requires_grad:", x.requires_grad)
print("z.grad_fn:", z.grad_fn)

# Backward pass - compute gradients
z.backward()

print("x.grad (dz/dx):", x.grad)
print("y.grad (dz/dy):", y.grad)

# Detach - break gradient flow
x2 = torch.tensor([2.0, 3.0], requires_grad=True)
x2_detached = x2.detach()
print("\nDetached tensor requires_grad:", x2_detached.requires_grad)

# torch.no_grad() - Disable gradient tracking for inference
print("\n--- Using torch.no_grad() ---")
model = nn.Linear(5, 3)
x_test = torch.randn(2, 5)

# With gradients (training)
output_train = model(x_test)
print("With gradients - output.requires_grad:", output_train.requires_grad)

# Without gradients (inference)
with torch.no_grad():
    output_test = model(x_test)
    print("With no_grad() - output.requires_grad:", output_test.requires_grad)

# torch.enable_grad() - Enable gradients inside no_grad()
print("\n--- Using torch.enable_grad() inside no_grad() ---")
with torch.no_grad():
    x3 = torch.tensor([1.0, 2.0], requires_grad=False)
    with torch.enable_grad():
        x3.requires_grad = True
        y3 = x3 ** 2
    print("Inside enable_grad() - y3.requires_grad:", y3.requires_grad)

# torch.autograd.grad() - Compute gradients directly
print("\n--- Using torch.autograd.grad() ---")
x4 = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
y4 = (x4 ** 2).sum()
grads = torch.autograd.grad(y4, x4)[0]
print("Gradients using torch.autograd.grad():", grads)

# Register hook - Custom function during backward
print("\n--- Using register_hook() ---")
x5 = torch.tensor([1.0, 2.0], requires_grad=True)
y5 = x5 ** 2

def my_hook(grad):
    print(f"Hook called - gradient: {grad}")
    return grad * 2  # Multiply gradient by 2

hook_handle = y5.register_hook(my_hook)
z5 = y5.sum()
z5.backward()
print("x5.grad after hook:", x5.grad)

# 12. Device Management

In [ ]:
# Check CUDA availability
print("torch.cuda.is_available():", torch.cuda.is_available())
print("torch.cuda.device_count():", torch.cuda.device_count())

# Create device object
device_cpu = torch.device('cpu')
device_cuda = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

print("device_cpu:", device_cpu)
print("device_cuda:", device_cuda)

# Create tensor on specific device
tensor_cpu = torch.randn(2, 3, device=device_cpu)
print("\nTensor on CPU - device:", tensor_cpu.device)

if torch.cuda.is_available():
    tensor_gpu = torch.randn(2, 3, device=device_cuda)
    print("Tensor on GPU - device:", tensor_gpu.device)
    
    # Move tensor between devices
    tensor_moved = tensor_cpu.to(device=device_cuda)
    print("After .to(cuda) - device:", tensor_moved.device)

# Type conversion using .to()
tensor_float = torch.randn(2, 3)
tensor_double = tensor_float.to(dtype=torch.float64)
print("\nAfter .to(float64) - dtype:", tensor_double.dtype)

# Manual seed for reproducibility
torch.manual_seed(42)
print("\nSet torch.manual_seed(42)")

if torch.cuda.is_available():
    torch.cuda.manual_seed(42)
    print("Set torch.cuda.manual_seed(42)")
    
    # Memory information
    print("\nGPU Memory Info:")
    print("torch.cuda.memory_allocated():", torch.cuda.memory_allocated() / 1e6, "MB")
    print("torch.cuda.memory_reserved():", torch.cuda.memory_reserved() / 1e6, "MB")
    
    # Synchronize GPU operations
    torch.cuda.synchronize()
    print("torch.cuda.synchronize() - GPU work completed")

# 13. Comparison & Logical Operations

In [ ]:
a = torch.tensor([1., 2., 3., 4.])
b = torch.tensor([2., 2., 2., 2.])

# Element-wise comparisons
print("a == b:", a == b)
print("a != b:", a != b)
print("a < b:", a < b)
print("a <= b:", a <= b)
print("a > b:", a > b)
print("a >= b:", a >= b)

# Using torch comparison functions
print("\ntorch.eq(a, b):", torch.eq(a, b))
print("torch.ne(a, b):", torch.ne(a, b))
print("torch.lt(a, b):", torch.lt(a, b))

# Approximate equality
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([1.0001, 2.0001, 3.0001])
print("\ntorch.allclose(x, y):", torch.allclose(x, y, atol=1e-3))
print("torch.isclose(x, y):", torch.isclose(x, y, atol=1e-3))

# Logical operations
mask1 = torch.tensor([True, False, True, False])
mask2 = torch.tensor([True, True, False, False])

print("\ntorch.logical_and(mask1, mask2):", torch.logical_and(mask1, mask2))
print("torch.logical_or(mask1, mask2):", torch.logical_or(mask1, mask2))
print("torch.logical_xor(mask1, mask2):", torch.logical_xor(mask1, mask2))
print("torch.logical_not(mask1):", torch.logical_not(mask1))

# Reduction to boolean
print("\ntorch.all(mask1):", torch.all(mask1))
print("torch.any(mask1):", torch.any(mask1))

# where() - Conditional selection
condition = a > 2
result = torch.where(condition, torch.tensor(999.), a)
print("\ntorch.where(a > 2, 999, a):", result)

# Boolean indexing
print("\na[a > 2]:", a[a > 2])  # Elements where condition is True

# masked_select
selected = torch.masked_select(a, a > 2)
print("torch.masked_select(a, a > 2):", selected)

# 14. Data Loading & Preprocessing

In [ ]:
from torch.utils.data import Dataset, DataLoader, TensorDataset

# Create custom dataset
class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels
    
    def __len__(self):
        return len(self.features)
    
    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]

# Generate sample data
X = torch.randn(100, 10)  # 100 samples, 10 features
y = torch.randint(0, 3, (100,))  # 100 labels

# Create dataset
dataset = CustomDataset(X, y)
print("Dataset length:", len(dataset))
print("First sample:", dataset[0][0].shape, dataset[0][1])

# Using TensorDataset
tensor_dataset = TensorDataset(X, y)
print("\nTensorDataset created from tensors")

# DataLoader - Batching and shuffling
dataloader = DataLoader(
    dataset, 
    batch_size=16, 
    shuffle=True, 
    num_workers=0
)

print("\nDataLoader created with batch_size=16")
print("Number of batches:", len(dataloader))

# Iterate through batches
for batch_idx, (batch_X, batch_y) in enumerate(dataloader):
    print(f"Batch {batch_idx}: X shape {batch_X.shape}, y shape {batch_y.shape}")
    if batch_idx == 1:  # Show only first 2 batches
        break

# Padding sequences (for variable length sequences)
from torch.nn.utils.rnn import pad_sequence

seq1 = torch.tensor([1., 2., 3.])
seq2 = torch.tensor([4., 5.])
seq3 = torch.tensor([6., 7., 8., 9.])

padded = pad_sequence([seq1, seq2, seq3], batch_first=True, padding_value=0)
print("\ntorch.nn.utils.rnn.pad_sequence() result shape:", padded.shape)
print("Padded sequences:\n", padded)

# 15. Serialization & Model Saving

In [ ]:
import tempfile
import os

# Create a model
model = nn.Sequential(
    nn.Linear(10, 20),
    nn.ReLU(),
    nn.Linear(20, 5)
)

# Get model state dict
state_dict = model.state_dict()
print("model.state_dict() keys:")
for key in state_dict.keys():
    print(f"  {key}: {state_dict[key].shape}")

# Save model checkpoint
checkpoint_path = 'model_checkpoint.pt'
checkpoint = {
    'model_state_dict': model.state_dict(),
    'epoch': 10,
    'loss': 0.123
}
torch.save(checkpoint, checkpoint_path)
print(f"\nSaved checkpoint to {checkpoint_path}")

# Load model checkpoint
loaded_checkpoint = torch.load(checkpoint_path)
model.load_state_dict(loaded_checkpoint['model_state_dict'])
print(f"Loaded checkpoint - Epoch: {loaded_checkpoint['epoch']}, Loss: {loaded_checkpoint['loss']}")

# Save entire model
model_path = 'full_model.pt'
torch.save(model, model_path)
print(f"Saved full model to {model_path}")

# Load entire model
loaded_model = torch.load(model_path)
print("Loaded full model")

# Save tensor
tensor = torch.randn(3, 4)
tensor_path = 'tensor.pt'
torch.save(tensor, tensor_path)
loaded_tensor = torch.load(tensor_path)
print(f"\nSaved and loaded tensor shape: {loaded_tensor.shape}")

# Model parameters and buffers
print("\n--- Model Parameters ---")
for name, param in model.named_parameters():
    print(f"{name}: {param.shape}")

# Set model to eval mode
model.eval()
print("\nSet model to eval mode with model.eval()")

# Disable gradients for inference
with torch.no_grad():
    test_input = torch.randn(2, 10)
    output = model(test_input)
    print(f"Inference output shape: {output.shape}")

# Clean up
os.remove(checkpoint_path)
os.remove(model_path)
os.remove(tensor_path)
print("\nCleaned up saved files")

# 16. Utilities & Helpers

In [ ]:
# Type conversion
print("=== Type Conversion ===")
int_tensor = torch.randint(0, 10, (2, 3))
float_tensor = int_tensor.float()
print("torch.randint -> .float():", float_tensor.dtype)

# Convert to NumPy
np_array = float_tensor.numpy()
print("tensor.numpy():", type(np_array), np_array.shape)

# Convert from NumPy
np_arr = np.array([[1, 2], [3, 4]])
torch_tensor = torch.from_numpy(np_arr)
print("torch.from_numpy():", torch_tensor.dtype)

# Unique elements
print("\n=== Unique & Sorting ===")
t = torch.tensor([3, 1, 4, 1, 5, 9, 2, 6])
unique_vals, inverse_indices = torch.unique(t, return_inverse=True)
print("torch.unique():", unique_vals)
print("Inverse indices:", inverse_indices)

# Sort
sorted_vals, sorted_indices = torch.sort(t)
print("torch.sort():", sorted_vals)

# Top-k elements
top_vals, top_indices = torch.topk(t, k=3)
print("torch.topk(k=3):", top_vals)

# Non-zero elements
print("\n=== Non-zero & Indexing ===")
sparse = torch.tensor([[0, 1, 0], [2, 0, 3], [0, 0, 4]])
nonzero_indices = torch.nonzero(sparse)
print("torch.nonzero():\n", nonzero_indices)

# Weight initialization
print("\n=== Weight Initialization ===")
w1 = torch.empty(3, 4)
torch.nn.init.xavier_normal_(w1)
print("Xavier normal init - mean:", w1.mean().item(), "std:", w1.std().item())

w2 = torch.empty(3, 4)
torch.nn.init.kaiming_normal_(w2, mode='fan_in', nonlinearity='relu')
print("Kaiming normal init - mean:", w2.mean().item())

# Gradient clipping
print("\n=== Gradient Clipping ===")
model = nn.Linear(5, 3)
loss_fn = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

x = torch.randn(4, 5)
y_true = torch.randn(4, 3)
y_pred = model(x)
loss = loss_fn(y_pred, y_true)
optimizer.zero_grad()
loss.backward()

# Clip gradients
torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
print("Clipped gradients with max_norm=1.0")

# Check NaN/Inf
print("\n=== Checking for NaN/Inf ===")
normal = torch.randn(3, 3)
print("torch.isnan(normal).any():", torch.isnan(normal).any())
print("torch.isinf(normal).any():", torch.isinf(normal).any())
print("torch.isfinite(normal).all():", torch.isfinite(normal).all())

# Roll and flip
print("\n=== Tensor Operations ===")
t = torch.tensor([[1, 2, 3], [4, 5, 6]])
rolled = torch.roll(t, shifts=1, dims=0)
print("torch.roll(shifts=1, dims=0):\n", rolled)

flipped = torch.flip(t, dims=[0])
print("torch.flip(dims=[0]):\n", flipped)

# 17. Complete Training Example

In [ ]:
print("=== Complete Neural Network Training Loop ===\n")

# 1. Define model
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(10, 50)
        self.fc2 = nn.Linear(50, 20)
        self.fc3 = nn.Linear(20, 3)
    
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# 2. Create data
X_train = torch.randn(100, 10)
y_train = torch.randint(0, 3, (100,))

train_dataset = TensorDataset(X_train, y_train)
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)

# 3. Initialize model, loss, optimizer
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = SimpleNN().to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)
scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=5, gamma=0.5)

print(f"Model: {model}")
print(f"Device: {device}\n")

# 4. Training loop
num_epochs = 3
for epoch in range(num_epochs):
    total_loss = 0.0
    batch_count = 0
    
    for batch_X, batch_y in train_loader:
        # Move to device
        batch_X = batch_X.to(device)
        batch_y = batch_y.to(device)
        
        # Forward pass
        outputs = model(batch_X)
        loss = criterion(outputs, batch_y)
        
        # Backward pass
        optimizer.zero_grad()  # Clear gradients
        loss.backward()  # Compute gradients
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()  # Update parameters
        
        total_loss += loss.item()
        batch_count += 1
    
    # Update learning rate
    scheduler.step()
    
    avg_loss = total_loss / batch_count
    print(f"Epoch {epoch+1}/{num_epochs} - Loss: {avg_loss:.4f} - LR: {optimizer.param_groups[0]['lr']:.6f}")

print("\nTraining completed!")

# 5. Inference
model.eval()
test_X = torch.randn(5, 10).to(device)

with torch.no_grad():
    test_output = model(test_X)
    predictions = torch.argmax(test_output, dim=1)
    probabilities = F.softmax(test_output, dim=1)

print(f"\nInference Results:")
print(f"Predictions: {predictions}")
print(f"Probabilities shape: {probabilities.shape}")

# 6. Get model info
print(f"\nModel Parameters:")
total_params = 0
for name, param in model.named_parameters():
    num_params = param.numel()
    total_params += num_params
    print(f"  {name}: {param.shape} = {num_params} parameters")
print(f"Total parameters: {total_params}")

# Summary & Quick Reference

## PyTorch API Overview

This notebook covered all major PyTorch functions organized by category:

### Core Tensor Operations
- **Creation**: `torch.tensor()`, `torch.randn()`, `torch.zeros()`, `torch.arange()`, etc.
- **Properties**: `.shape`, `.dtype`, `.device`, `.requires_grad`, `.grad`, etc.
- **Reshaping**: `.reshape()`, `.view()`, `.transpose()`, `.flatten()`, `torch.cat()`, `torch.stack()`, etc.

### Mathematical & Linear Algebra
- **Arithmetic**: `+`, `-`, `*`, `/`, `torch.pow()`, `torch.sqrt()`, etc.
- **Matrix Operations**: `torch.mm()`, `torch.matmul()` (`@`), `torch.bmm()`, etc.
- **Decompositions**: `torch.svd()`, `torch.qr()`, `torch.eig()`, etc.
- **Norms**: `torch.norm()`, `torch.dist()`, etc.

### Reduction Operations
- **Aggregation**: `torch.sum()`, `torch.mean()`, `torch.std()`, `torch.var()`, etc.
- **Min/Max**: `torch.min()`, `torch.max()`, `torch.argmin()`, `torch.argmax()`, etc.
- **Cumulative**: `torch.cumsum()`, `torch.cumprod()`, etc.

### Neural Network Layers & Functions
- **Layers**: `nn.Linear()`, `nn.Conv2d()`, `nn.BatchNorm2d()`, `nn.LSTM()`, `nn.MultiheadAttention()`, etc.
- **Activations**: `F.relu()`, `F.sigmoid()`, `F.tanh()`, `F.gelu()`, `F.softmax()`, etc.
- **Losses**: `F.cross_entropy()`, `F.mse_loss()`, `F.l1_loss()`, `F.binary_cross_entropy()`, etc.

### Optimization & Training
- **Optimizers**: `optim.SGD()`, `optim.Adam()`, `optim.AdamW()`, `optim.RMSprop()`, etc.
- **Learning Rate Schedulers**: `StepLR`, `CosineAnnealingLR`, `ReduceLROnPlateau`, etc.
- **Autograd**: `.backward()`, `torch.autograd.grad()`, `torch.no_grad()`, hooks, etc.

### Utilities
- **Device**: `torch.device()`, `.to()`, `torch.cuda.*()`, etc.
- **Data Loading**: `Dataset`, `DataLoader`, transforms, etc.
- **Serialization**: `torch.save()`, `torch.load()`, `.state_dict()`, etc.
- **Initialization**: `torch.nn.init.*()` functions
- **Type Conversion**: `.numpy()`, `torch.from_numpy()`, `.to(dtype)`, etc.

## Key Takeaways

1. **Raw PyTorch API** - All functions are accessed through the `torch` module
2. **Functional vs Module** - Prefer `nn.Module` for stateful layers, `F.*` for stateless operations
3. **GPU Support** - Use `.to(device)` to move tensors/models to GPU
4. **Autograd** - Automatic differentiation via `.backward()` and `.grad`
5. **Device Management** - Always be aware of tensor device locations
6. **DataLoader** - Use for efficient batch processing with shuffling and prefetching

## Resources

- Official PyTorch Docs: https://pytorch.org/docs/stable/
- PyTorch Source Code: https://github.com/pytorch/pytorch
- GPU Optimization: cuDNN, cuBLAS documentation

# 18. Calling Conventions: C++ and Python Integration

## How PyTorch Calls C++ from Python

PyTorch is primarily written in C++ but exposed to Python through various binding mechanisms. This section explores how this integration works.

In [ ]:
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Calling Conventions: How Python calls C++ code

PyTorch uses multiple methods to interface with C++ code:
1. pybind11 - Header-only library for C++11 Python bindings
2. CFFI - C Foreign Function Interface
3. ctypes - Low-level foreign function library
4. Direct CPython API - Using CPython C API directly
"""

print("=== Python-to-C++ Call Flow ===\n")

print("""
When you call torch.randn(2, 3) in Python:

1. Python Layer (torch/tensor.py):
   def randn(*size, ...):
       return torch._C._randn(...)

2. C++ Binding Layer (torch._C):
   - Pybind11 binding converts Python arguments to C++ types
   - Calls C++ function: at::randn(...)

3. C++ Implementation Layer (aten/src/ATen/functions.cpp):
   Tensor randn(IntArrayRef size, ...) {
       // Actual computation happens here
       // GPU kernels called via cuBLAS, cuDNN
   }

4. Return to Python:
   - C++ Tensor object converted back to Python
   - torch.Tensor Python wrapper returned

5. Python Layer (Back):
   - torch.Tensor object in Python
   - Ready for further operations
""")

## Method 1: ctypes - Low-Level C/C++ Calling

`ctypes` is Python's built-in library for calling C/C++ shared libraries directly.

In [ ]:
import ctypes
import platform

print("=== Using ctypes to Call C/C++ ===\n")

# Example: Loading C math library
# This varies by platform
if platform.system() == "Linux":
    libc = ctypes.CDLL(None)  # Load C library
    sqrt_func = libc.sqrt
elif platform.system() == "Darwin":  # macOS
    libc = ctypes.CDLL("libc.dylib")
    sqrt_func = libc.sqrt
else:  # Windows
    libc = ctypes.CDLL("msvcrt")
    sqrt_func = libc.sqrt

# Define argument and return types
sqrt_func.argtypes = [ctypes.c_double]
sqrt_func.restype = ctypes.c_double

# Call C function from Python
result = sqrt_func(16.0)
print(f"C sqrt(16.0) = {result}")

# Example: Calling PyTorch's C++ backend
print("\n--- PyTorch's C++ Backend Access ---")
print("torch._C module - Direct access to C++ bindings:")
print(f"dir(torch._C)[:10] = {dir(torch._C)[:10]}")

# Accessing raw C++ functions
print("\nExample C++ functions exposed via pybind11:")
print("  torch._C._randn - Raw C++ randn function")
print("  torch._C._zeros - Raw C++ zeros function")
print("  torch._C._add - Raw C++ add function")

## Method 2: pybind11 - PyTorch's Binding Mechanism

pybind11 is a lightweight header-only C++11 library that seamlessly exposes C++ types, functions, and classes to Python.

In [ ]:
print("=== pybind11 Example ===\n")

print("""
C++ Code (example.cpp):
```cpp
#include <pybind11/pybind11.h>
#include <torch/torch.h>

// Simple C++ function
int add(int a, int b) {
    return a + b;
}

// Tensor operation
torch::Tensor matrix_multiply(torch::Tensor a, torch::Tensor b) {
    return torch::mm(a, b);
}

// pybind11 module binding
PYBIND11_MODULE(example, m) {
    m.def("add", &add, "Add two integers");
    m.def("matrix_multiply", &matrix_multiply, "Multiply two matrices");
}
```

Python Usage:
```python
import example  # Compiled C++ module

result = example.add(5, 3)  # Calls C++ function
print(result)  # Output: 8

import torch
a = torch.randn(3, 4)
b = torch.randn(4, 5)
c = example.matrix_multiply(a, b)  # C++ tensor operation
print(c.shape)  # Output: torch.Size([3, 5])
```

How It Works:
1. pybind11 generates C++ binding code
2. Automatic type conversion: Python → C++ → Python
3. GIL (Global Interpreter Lock) management built-in
4. Exception mapping: C++ exceptions → Python exceptions
5. Compiled as shared library (.so on Linux, .dylib on macOS, .pyd on Windows)
""")

# 19. Python .pyi Stub Files

`.pyi` files are Python stub files that provide type hints for modules, especially those with C/C++ implementations.

In [ ]:
print("=== .pyi Stub Files ===\n")

print("""
What are .pyi files?
- Type stub files (PEP 484)
- Provide type hints for Python modules
- Used by type checkers (mypy, pyright) and IDEs
- Especially important for C/C++ extensions with no Python source

Why needed?
1. C/C++ extensions have no Python source code to analyze
2. Type checkers can't infer types from compiled binaries
3. Provides IDE autocomplete and type checking

Structure:
- .pyi files contain only declarations (no implementations)
- Mirror the structure of the corresponding .py or .so module
- Can be bundled with packages or in typeshed

Example Structure:

PyTorch package layout:
├── torch/
│   ├── __init__.py
│   ├── __init__.pyi          # Stub for torch module
│   ├── _C.so                 # Compiled C++ module (no source)
│   ├── _C.pyi                # Stub file for _C module
│   ├── nn/
│   │   ├── __init__.py
│   │   ├── modules.py
│   │   └── functional.pyi    # Stub for functional
""")

# Example: Checking torch.pyi
print("\n--- Example: torch._C.pyi stub ---\n")

print("""
torch/_C.pyi content (simplified):

from typing import List, Optional, Tuple, Any
import torch

def _randn(
    size: List[int],
    dtype: Optional[torch.dtype] = ...,
    device: Optional[torch.device] = ...,
    requires_grad: bool = ...,
) -> torch.Tensor: ...

def _zeros(
    size: List[int],
    dtype: Optional[torch.dtype] = ...,
    device: Optional[torch.device] = ...,
) -> torch.Tensor: ...

def _add(
    input: torch.Tensor,
    other: torch.Tensor,
    alpha: float = ...,
) -> torch.Tensor: ...

class Tensor:
    def __init__(self, data: Any, ...) -> None: ...
    def to(
        self,
        dtype: Optional[torch.dtype] = ...,
        device: Optional[torch.device] = ...,
    ) -> Tensor: ...
    @property
    def shape(self) -> torch.Size: ...
    @property
    def dtype(self) -> torch.dtype: ...
""")

## How to Create .pyi Files

### Method 1: Manual Creation

In [ ]:
print("=== Creating .pyi Files ===\n")

# Create example .pyi file
pyi_content = '''"""
Type stubs for custom_module.pyi

This is a stub file for a C++ compiled module.
It provides type hints for functions and classes.
"""

from typing import List, Optional, Union, Tuple, Any, overload
import numpy as np

# Simple function stub
def add(a: float, b: float) -> float:
    """Add two numbers."""
    ...

def matrix_multiply(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    """Multiply two matrices."""
    ...

# Class stub
class Tensor:
    """Tensor class from compiled module."""
    
    data: np.ndarray
    shape: Tuple[int, ...]
    dtype: str
    
    def __init__(self, data: Any) -> None: ...
    
    @overload
    def __getitem__(self, key: int) -> "Tensor": ...
    @overload
    def __getitem__(self, key: slice) -> "Tensor": ...
    
    def __add__(self, other: "Tensor") -> "Tensor": ...
    def __mul__(self, other: "Tensor") -> "Tensor": ...
    
    def to_numpy(self) -> np.ndarray:
        """Convert to numpy array."""
        ...
    
    def reshape(self, *shape: int) -> "Tensor":
        """Reshape tensor."""
        ...

# Function overloads for flexibility
@overload
def create_tensor(size: List[int]) -> Tensor: ...
@overload
def create_tensor(size: Tuple[int, ...]) -> Tensor: ...
'''

print("Example .pyi file (custom_module.pyi):")
print(pyi_content)

# Create actual pyi file for demonstration
pyi_path = '/tmp/custom_module.pyi'
with open(pyi_path, 'w') as f:
    f.write(pyi_content)

print(f"\nCreated example .pyi file at: {pyi_path}")
print(f"File size: {len(pyi_content)} bytes")

### Method 2: Automatic Generation

In [ ]:
print("=== Tools for Automatic .pyi Generation ===\n")

print("""
1. **stubgen** (from typeshed_client)
   Command: stubgen module_name
   Analyzes Python module and generates .pyi files

2. **pybind11-stubgen**
   Specifically for pybind11 modules
   Command: pybind11-stubgen -o stubs module_name

3. **mypy --stubgen-dir**
   Part of mypy type checker
   Command: mypy --stubgen-dir=stubs module_name

4. **PyYAML and dataclasses-based approach**
   Write docstrings → auto-generate stubs

5. **Manual approach** (most common for PyTorch)
   - Extract docstrings from C++ code
   - Write .pyi manually
   - Maintain alongside C++ source
""")

print("\n--- Example: Using pybind11 with auto-generated stubs ---\n")

# Example command
print("""
# Step 1: Build pybind11 module
cd my_project
python setup.py build_ext --inplace

# Step 2: Generate stubs
pybind11-stubgen my_module -o stubs/

# Step 3: Copy stubs to package
cp stubs/my_module.pyi my_module/

# Step 4: Verify with mypy
mypy --strict my_code.py
""")

## How .pyi Files Work

### IDE and Type Checker Resolution

In [ ]:
print("=== .pyi File Resolution Process ===\n")

print("""
When IDE/Type Checker encounters: import torch

1. RESOLUTION PHASE:
   a) Check for torch.pyi (stub file) - PREFERRED
   b) If not found, check torch/__init__.py (Python source)
   c) If not found, check torch/_C.so (compiled module - NO TYPE INFO)

2. If torch.pyi exists:
   - Type checker reads .pyi file for ALL type information
   - Provides accurate autocomplete and type hints
   - Runtime uses compiled .so, but checking uses .pyi

3. If no .pyi exists:
   - Type checker falls back to .py file
   - For compiled modules (.so), type checking is DISABLED
   - IDE can't provide autocomplete

Example Resolution Priority:
torch/
├── __init__.pyi  ← Used by mypy, pyright, IDE (HIGHEST PRIORITY)
├── __init__.py   ← Python source
├── _C.pyi        ← Stub for C++ module (HIGHEST PRIORITY)
└── _C.so         ← Compiled C++ (LOWEST PRIORITY)
""")

print("\n--- Type Checking Example ---\n")

# Example: With and without .pyi
print("""
Code to type-check:
import torch
x = torch.randn(2, 3)  # What is the type of x?
y = x.shape  # What type is shape?

With torch.pyi present:
✓ x: torch.Tensor (from .pyi)
✓ y: torch.Size (from .pyi)
✓ IDE autocomplete works
✓ mypy can verify types

Without torch.pyi:
✗ x: Any (can't infer from .so)
✗ y: Any
✗ IDE autocomplete limited
✗ mypy skips checking
""")

In [ ]:
print("=== PyTorch's Real .pyi Structure ===\n")

# Check if torch has .pyi files
import torch
torch_path = torch.__path__[0]
print(f"PyTorch installation path: {torch_path}\n")

# List some key .pyi files in PyTorch
import os
pyi_files = []
for root, dirs, files in os.walk(torch_path):
    for f in files:
        if f.endswith('.pyi'):
            rel_path = os.path.relpath(os.path.join(root, f), torch_path)
            pyi_files.append(rel_path)
    if len(pyi_files) > 10:  # Limit for display
        break

print("Some PyTorch .pyi files found:")
for pyi in sorted(pyi_files)[:10]:
    print(f"  {pyi}")

# Show structure of torch._C
print("\n--- torch._C Module ---")
print("torch._C is compiled C++ module:")
print(f"Type: {type(torch._C)}")
print(f"Location: {torch._C.__file__ if hasattr(torch._C, '__file__') else 'Built-in'}")

# Type hints from .pyi
print("\n--- Accessing Type Hints ---")
if hasattr(torch, '__annotations__'):
    print("torch.__annotations__:", torch.__annotations__)
else:
    print("Note: Runtime doesn't preserve .pyi info")
    print("Type info is only used during static analysis (mypy, pyright, IDE)")

## Complete Calling Flow Diagram

PyTorch Runtime Stack (How it all works together):

In [ ]:
print("""
╔════════════════════════════════════════════════════════════════╗
║                  PyTorch Execution Stack                      ║
╚════════════════════════════════════════════════════════════════╝

┌─────────────────────────────────────────────────────────┐
│ 1. USER CODE (Python)                                   │
│    x = torch.randn(2, 3)                                │
│    y = x + torch.zeros(2, 3)                            │
│    loss = F.mse_loss(y, target)                         │
└─────────────────────────────────────────────────────────┘
                          ↓
┌─────────────────────────────────────────────────────────┐
│ 2. PYTHON API LAYER (torch/*.py)                        │
│    torch/functional.py:                                 │
│    def mse_loss(input, target):                         │
│        return torch._C._mse_loss(...)                   │
│                                                          │
│    Located: torch/__init__.py, torch/nn/functional.py  │
└─────────────────────────────────────────────────────────┘
                          ↓
┌─────────────────────────────────────────────────────────┐
│ 3. TYPE HINTS (torch/*.pyi)                             │
│    *.pyi files consulted by:                            │
│    - IDE (VSCode, PyCharm) for autocomplete             │
│    - Type checkers (mypy, pyright)                      │
│    - Documentation generators                           │
│                                                          │
│    Runtime: Python IGNORES .pyi files                   │
│    Static Analysis: Python USES .pyi files              │
└─────────────────────────────────────────────────────────┘
                          ↓
┌─────────────────────────────────────────────────────────┐
│ 4. PYBIND11 BINDING LAYER                               │
│    - Converts Python arguments to C++ types             │
│    - Handles type conversion automatically              │
│    - Manages Global Interpreter Lock (GIL)              │
│    - Exception handling: C++ exceptions → Python        │
│                                                          │
│    File: torch/_C.so (compiled pybind11 module)         │
└─────────────────────────────────────────────────────────┘
                          ↓
┌─────────────────────────────────────────────────────────┐
│ 5. C++ IMPLEMENTATION LAYER                             │
│    - torch/csrc/api/torch.cpp                           │
│    - aten/src/ATen/functions.cpp                        │
│    - Pure C++11/14/17 code                              │
│                                                          │
│    namespace torch { namespace nn { ... } }             │
│    Tensor randn(IntArrayRef size, ...);                 │
│    Tensor add(const Tensor& a, const Tensor& b);        │
└─────────────────────────────────────────────────────────┘
                          ↓
┌─────────────────────────────────────────────────────────┐
│ 6. GPU ACCELERATION LAYER (Optional)                    │
│    - cuBLAS: Linear algebra operations                  │
│    - cuDNN: Neural network operations                   │
│    - CUDA: General GPU kernels                          │
│    - cuSPARSE: Sparse operations                        │
│                                                          │
│    if (device.is_cuda()) {                              │
│        callCudaKernel(...);  // GPU execution            │
│    } else {                                              │
│        callCPUKernel(...);   // CPU execution            │
│    }                                                      │
└─────────────────────────────────────────────────────────┘
                          ↓
┌─────────────────────────────────────────────────────────┐
│ 7. HARDWARE EXECUTION                                   │
│    - CPU: Intel MKL, ARM NEON                           │
│    - GPU: NVIDIA CUDA, AMD HIP                          │
│    - TPU: Google Cloud TPU                              │
└─────────────────────────────────────────────────────────┘
                          ↓
┌─────────────────────────────────────────────────────────┐
│ 8. RETURN TO PYTHON                                     │
│    - C++ Tensor converted back to Python object         │
│    - torch.Tensor wrapper created                       │
│    - Returns to user code                               │
└─────────────────────────────────────────────────────────┘

KEY POINTS:
═══════════════════════════════════════════════════════════
• Runtime (.pyi is ignored):
  Python → pybind11 → C++ → GPU → C++ → Python

• Static Analysis (.pyi is used):
  IDEs/Type checkers read .pyi for autocomplete & checking

• Memory Model:
  Python objects hold pointers to C++ Tensor objects
  Garbage collection coordinates cleanup

• Concurrency:
  GIL released during C++ execution
  GPU operations async via CUDA streams
""")

## Practical: Inspecting C++ Bindings

In [ ]:
print("=== Inspecting C++ Bindings from Python ===\n")

# Access C++ layer directly
print("1. Access torch._C (direct C++ bindings):")
print(f"   torch._C module: {torch._C}")
print(f"   Type: {type(torch._C)}")

# List some C++ functions
print("\n2. C++ functions exposed via pybind11:")
c_functions = [attr for attr in dir(torch._C) if not attr.startswith('_')]
for func in c_functions[:10]:
    print(f"   torch._C.{func}")

# Inspect function signatures (if available)
print("\n3. Function help/docstring:")
print(f"   torch._C._randn.__doc__:")
help_text = torch._C._randn.__doc__
if help_text:
    print(f"   {help_text[:200]}...")
else:
    print("   (No docstring available for C++ binding)")

# Check tensor implementation
print("\n4. Tensor class from C++ layer:")
print(f"   torch.Tensor type: {type(torch.tensor([1.0]))}")
print(f"   torch.Tensor.__class__: {torch.tensor([1.0]).__class__}")

# Memory layout
print("\n5. Memory inspection:")
x = torch.randn(2, 3)
print(f"   data_ptr(): {x.data_ptr()}")  # Raw C++ pointer
print(f"   storage_offset(): {x.storage_offset()}")
print(f"   is_contiguous(): {x.is_contiguous()}")

# Direct access to underlying data
print("\n6. Accessing C++ data from Python:")
print(f"   torch.Tensor.data_ptr() type: {type(x.data_ptr())}")  # Python int
print(f"   Can convert to ctypes pointer for C interop")

# Build information
print("\n7. PyTorch build information:")
print(f"   torch.version.cuda: {torch.version.cuda}")
print(f"   torch.backends.cudnn.enabled: {torch.backends.cudnn.enabled}")
print(f"   torch.backends.cudnn.version(): {torch.backends.cudnn.version() if torch.cuda.is_available() else 'N/A'}")

# 20. Summary: Understanding PyTorch's Python-C++ Integration

In [ ]:
print("""
╔══════════════════════════════════════════════════════════════════╗
║  Key Concepts in Python-C++ Integration (PyTorch)                ║
╚══════════════════════════════════════════════════════════════════╝

1. CALLING CONVENTIONS
═══════════════════════════════════════════════════════════════════

   What: How Python calls C/C++ code
   
   Methods:
   • ctypes - Low-level FFI, manual memory management
   • cffi - Complex C/C++, unsafe
   • pybind11 - High-level bindings (PyTorch uses this)
   • Direct CPython API - Most control, complex
   
   PyTorch Uses: pybind11
   └─ Automatic type conversion
   └─ GIL management
   └─ Exception handling
   └─ Performance-optimized


2. PYTHON .PYI STUB FILES
═══════════════════════════════════════════════════════════════════

   What: Type hint files for modules (especially C/C++ extensions)
   
   Purpose:
   • Provide type information for type checkers (mypy, pyright)
   • Enable IDE autocomplete and type hints
   • Document function signatures without runtime overhead
   • Replace missing source code for compiled modules
   
   Key Points:
   • .pyi files are IGNORED at runtime
   • Used ONLY during static analysis
   • Must be packaged with module
   • Can be auto-generated or manually written
   
   File Priority (Resolution Order):
   1. *.pyi stub file (highest)
   2. *.py Python source
   3. *.so compiled module (lowest - no type info)


3. PYTORCH'S ARCHITECTURE
═══════════════════════════════════════════════════════════════════

   Python Layer (torch/__init__.py):
   └─ High-level API functions
   └─ Delegates to C++ layer
   
   Binding Layer (torch._C + pybind11):
   └─ Type conversion Python ↔ C++
   └─ GIL handling
   └─ Exception mapping
   
   C++ Layer (aten/, torch/csrc/):
   └─ Core implementations
   └─ Algorithm logic
   └─ Memory management
   
   Hardware Layer (cuBLAS, cuDNN, CUDA):
   └─ Actual computation
   └─ GPU acceleration
   
   Type Info Layer (.pyi files):
   └─ Static analysis only
   └─ IDE information
   └─ Type checker hints


4. FLOW EXAMPLE: torch.randn(2, 3)
═══════════════════════════════════════════════════════════════════

   Python Code:
   >>> x = torch.randn(2, 3)
   
   ↓ Execution Flow:
   
   1. Python: torch.randn() method called
      └─ Defined in torch/__init__.py
   
   2. pybind11 Binding:
      └─ Converts (2, 3) tuple to C++ IntArrayRef
      └─ Calls torch::randn(IntArrayRef size, ...)
   
   3. C++ Implementation:
      └─ Allocates memory on device (CPU/GPU)
      └─ Initializes with random values
      └─ Returns torch::Tensor object
   
   4. pybind11 Binding:
      └─ Converts torch::Tensor → Python Tensor
      └─ Wraps in Python object with metadata
   
   5. Return to Python:
      └─ Python Tensor object returned
      └─ Ready for further operations


5. TYPE CHECKING WITH .PYI FILES
═══════════════════════════════════════════════════════════════════

   Without .pyi:
   >>> x = torch.randn(2, 3)
   Type of x: Unknown (type checker gives up)
   
   With .pyi:
   >>> x = torch.randn(2, 3)  # x: torch.Tensor
   Type of x: torch.Tensor
   x.shape  # IDE knows this is torch.Size
   x.to(device)  # IDE knows method exists
   mypy can verify: ✓ Type checking enabled


6. PERFORMANCE IMPLICATIONS
═══════════════════════════════════════════════════════════════════

   Overhead:
   • Python → C++ conversion: < 1 microsecond
   • Negligible for most operations (> 1 millisecond)
   • High for many small operations (kernel launch overhead)
   
   Optimization:
   • Batch operations: Reduce Python/C++ boundary crossings
   • GPU computation: Amortizes conversion overhead
   • Compiled code: No conversion needed (torch.jit.script)


7. DEBUGGING TIPS
═══════════════════════════════════════════════════════════════════

   Python Side:
   • torch.backends.cudnn.benchmark = False  # Reproducibility
   • torch.autograd.profiler  # Profile C++ operations
   • torch.autograd.set_detect_anomaly(True)  # NaN detection
   
   C++ Side:
   • Use gdb/lldb with --pdb-search-path for symbols
   • TORCH_CPP_LOG_LEVEL=1 environment variable
   • torch.distributed.launch --nprocs_per_node=1 --no_python


8. KEY TAKEAWAYS
═══════════════════════════════════════════════════════════════════

   ✓ PyTorch is primarily C++ with Python bindings via pybind11
   ✓ .pyi files enable IDE/type checker support for compiled modules
   ✓ Type checking uses .pyi, runtime ignores it
   ✓ Calling convention is optimized and low-overhead
   ✓ Understanding this improves debugging and optimization
   ✓ Look at torch._C to access raw C++ layer
""")

print("\n✓ Comprehensive understanding of PyTorch internals complete!")