# Trace of a Matrix

The trace of a matrix is a fundamental concept in linear algebra with applications in machine learning, optimization, and tensor analysis.

## Definition

The **trace** of a square matrix $\mathbf{A}$ of size $n \times n$ is the sum of its diagonal elements:

$$\text{tr}(\mathbf{A}) = \sum_{i=1}^{n} a_{ii} = a_{11} + a_{22} + \cdots + a_{nn}$$

Where $a_{ii}$ represents the diagonal elements of the matrix.

### Important Notes:
- The trace is only defined for **square matrices** (n × n)
- It is a **scalar value** (single number)
- It is independent of the coordinate system chosen (invariant under similarity transformations)
- The trace equals the sum of the eigenvalues: $\text{tr}(\mathbf{A}) = \sum_{i=1}^{n} \lambda_i$

In [ ]:
import torch
import numpy as np

## Computing Trace Using PyTorch

In [ ]:
# Create a square matrix
A = torch.tensor([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]], dtype=torch.float32)

print("Matrix A:")
print(A)
print(f"\nShape: {A.shape}")

Matrix A:
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

Shape: torch.Size([3, 3])


In [ ]:
# Method 1: Using torch.trace()
trace_A = torch.trace(A)
print(f"Trace of A using torch.trace(): {trace_A}")

# Method 2: Manual calculation
manual_trace = A[0, 0] + A[1, 1] + A[2, 2]
print(f"Trace of A (manual calculation): {manual_trace}")

# Method 3: Using diagonal and sum
diagonal_trace = torch.sum(torch.diag(A))
print(f"Trace of A using diagonal and sum: {diagonal_trace}")

Trace of A using torch.trace(): 15.0
Trace of A (manual calculation): 15.0
Trace of A using diagonal and sum: 15.0


## Properties of Trace

### 1. Linearity: tr(αA + βB) = α·tr(A) + β·tr(B)

In [ ]:
B = torch.tensor([[2, 0, 1],
                   [1, 3, 2],
                   [0, 1, 4]], dtype=torch.float32)

alpha = 2
beta = 3

# Left side: tr(αA + βB)
left_side = torch.trace(alpha * A + beta * B)

# Right side: α·tr(A) + β·tr(B)
right_side = alpha * torch.trace(A) + beta * torch.trace(B)

print(f"tr(αA + βB) = {left_side}")
print(f"α·tr(A) + β·tr(B) = {right_side}")
print(f"Linearity property holds: {torch.allclose(left_side, right_side)}")

tr(αA + βB) = 57.0
α·tr(A) + β·tr(B) = 57.0
Linearity property holds: True


### 2. Trace of Transpose: tr(A^T) = tr(A)

In [ ]:
trace_A = torch.trace(A)
trace_A_T = torch.trace(A.T)

print(f"tr(A) = {trace_A}")
print(f"tr(A^T) = {trace_A_T}")
print(f"Transpose property holds: {torch.allclose(trace_A, trace_A_T)}")

tr(A) = 15.0
tr(A^T) = 15.0
Transpose property holds: True


### 3. Trace of Product (Cyclic Property): tr(AB) = tr(BA)

In [ ]:
C = torch.tensor([[1, 2],
                   [3, 4]], dtype=torch.float32)

D = torch.tensor([[5, 6],
                   [7, 8]], dtype=torch.float32)

trace_CD = torch.trace(torch.matmul(C, D))
trace_DC = torch.trace(torch.matmul(D, C))

print(f"C @ D = \n{torch.matmul(C, D)}")
print(f"\nD @ C = \n{torch.matmul(D, C)}")
print(f"\ntr(CD) = {trace_CD}")
print(f"tr(DC) = {trace_DC}")
print(f"Cyclic property holds: {torch.allclose(trace_CD, trace_DC)}")

C @ D = 
tensor([[19., 22.],
        [43., 50.]])

D @ C = 
tensor([[23., 34.],
        [31., 46.]])

tr(CD) = 69.0
tr(DC) = 69.0
Cyclic property holds: True


### 4. Trace and Eigenvalues: tr(A) = Σ λᵢ

In [ ]:
# Create a symmetric matrix (to ensure real eigenvalues)
E = torch.tensor([[4, 1],
                   [1, 3]], dtype=torch.float32)

# Calculate trace
trace_E = torch.trace(E)

# Calculate eigenvalues
eigenvalues = torch.linalg.eigvalsh(E)  # eigvalsh for symmetric/Hermitian matrices
sum_eigenvalues = torch.sum(eigenvalues)

print(f"Matrix E:\n{E}")
print(f"\nTrace of E: {trace_E}")
print(f"Eigenvalues: {eigenvalues}")
print(f"Sum of eigenvalues: {sum_eigenvalues}")
print(f"Eigenvalue property holds: {torch.allclose(trace_E, sum_eigenvalues)}")

Matrix E:
tensor([[4., 1.],
        [1., 3.]])

Trace of E: 7.0
Eigenvalues: tensor([2.3820, 4.6180])
Sum of eigenvalues: 7.0
Eigenvalue property holds: True


## Applications of Trace

1. **Frobenius Norm**: $\|\mathbf{A}\|_F = \sqrt{\text{tr}(\mathbf{A}^T\mathbf{A})}$
2. **Total Variance**: In PCA, the trace of the covariance matrix represents total variance
3. **Optimization**: Trace operations appear in gradient computations
4. **Matrix Regularization**: Trace is used in nuclear norm regularization

In [ ]:
# Example: Frobenius Norm using trace
F = torch.tensor([[1, 2],
                   [3, 4]], dtype=torch.float32)

# Method 1: Using torch.norm()
frobenius_norm_1 = torch.norm(F, 'fro')

# Method 2: Using trace
frobenius_norm_2 = torch.sqrt(torch.trace(torch.matmul(F.T, F)))

print(f"Frobenius norm (using torch.norm): {frobenius_norm_1}")
print(f"Frobenius norm (using trace): {frobenius_norm_2}")
print(f"Both methods match: {torch.allclose(frobenius_norm_1, frobenius_norm_2)}")

Frobenius norm (using torch.norm): 5.4772257804870605
Frobenius norm (using trace): 5.4772257804870605
Both methods match: True
