# Introduction to Vectors and Matrices

Vectors and matrices are fundamental concepts in mathematics and computer science, particularly in machine learning, data science, and linear algebra. This notebook explores the basics of vectors and matrices, their properties, operations, and applications.

## What are Vectors?
- A vector is a mathematical object that has both magnitude and direction.
- In machine learning, vectors often represent data points, features, or weights.
- Examples: position vectors, feature vectors in datasets.

## What are Matrices?
- A matrix is a rectangular array of numbers arranged in rows and columns.
- Matrices can represent transformations, datasets, or systems of equations.
- Common operations: addition, multiplication, transposition, inversion.

This notebook will guide you through creating, manipulating, and understanding vectors and matrices using PyTorch.

In [7]:
import torch

## Vector as a Matrix

We consider **vector** as a specific case of **matrix of size d × 1**

**Representation:**

$$\mathbf{x} = (x_1, x_2, \ldots, x_d)$$

**Vector (Column Form):**

$$\mathbf{x} = \begin{bmatrix} x_1 \\ x_2 \\ \vdots \\ x_d \end{bmatrix}, \quad \mathbf{x} \in \mathbb{R}^d$$

**Transpose (Row form):**

$$\mathbf{x}^T = \begin{bmatrix} x_1 & x_2 & \cdots & x_d \end{bmatrix}, \quad \mathbf{x}^T \in \mathbb{R}^{1 \times d}$$

**Key Points:**
- Feature vector **x** is an element of the set called $\mathbb{R}^d$
- **ℝ** denotes the real numbers (space of real numbers)
- The number of real values is denoted by $d$
- **x^T** (x transpose) converts a column vector to a row vector

In [8]:
# Creating a Vector using PyTorch

# Vectors can be created using torch.tensor()
vector = torch.tensor([1, 2, 3, 4, 5])
print("Vector:", vector)
print("Shape:", vector.shape)
print("Data type:", vector.dtype)

Vector: tensor([1, 2, 3, 4, 5])
Shape: torch.Size([5])
Data type: torch.int64


In [9]:
# Reshaping Vectors to Matrices

# A vector can be reshaped into a matrix with 1 column (column vector)
column_matrix_1 = vector.unsqueeze(1)  # Add a dimension at position 1
print("Column Matrix using unsqueeze(1):")
print(column_matrix_1)
print("Shape:", column_matrix_1.shape)

# Alternative way using view
column_matrix_2 = vector.view(-1, 1)
print()
print("Using view(-1, 1):")
print(column_matrix_2)
print("Shape:", column_matrix_2.shape)

# Using reshape() method
column_matrix_3 = vector.reshape(-1, 1)
print()
print("Using reshape(-1, 1):")
print(column_matrix_3)
print("Shape:", column_matrix_3.shape)

# Using torch.unsqueeze() function
column_matrix_4 = torch.unsqueeze(vector, 1)
print()
print("Using torch.unsqueeze(vector, 1):")
print(column_matrix_4)
print("Shape:", column_matrix_4.shape)

# Using None indexing to add dimension
column_matrix_5 = vector[:, None]
print()
print("Using vector[:, None]:")
print(column_matrix_5)
print("Shape:", column_matrix_5.shape)

# Creating a row matrix (1 row, multiple columns)
row_matrix = vector.unsqueeze(0)  # Add dimension at position 0
print()
print("Row Matrix (using unsqueeze(0)):")
print(row_matrix)
print("Shape:", row_matrix.shape)

Column Matrix using unsqueeze(1):
tensor([[1],
        [2],
        [3],
        [4],
        [5]])
Shape: torch.Size([5, 1])

Using view(-1, 1):
tensor([[1],
        [2],
        [3],
        [4],
        [5]])
Shape: torch.Size([5, 1])

Using reshape(-1, 1):
tensor([[1],
        [2],
        [3],
        [4],
        [5]])
Shape: torch.Size([5, 1])

Using torch.unsqueeze(vector, 1):
tensor([[1],
        [2],
        [3],
        [4],
        [5]])
Shape: torch.Size([5, 1])

Using vector[:, None]:
tensor([[1],
        [2],
        [3],
        [4],
        [5]])
Shape: torch.Size([5, 1])

Row Matrix (using unsqueeze(0)):
tensor([[1, 2, 3, 4, 5]])
Shape: torch.Size([1, 5])


In [10]:
# Creating a Matrix using PyTorch

# Matrices can be created using torch.tensor() with nested lists
matrix = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix:")
print(matrix)
print("Shape:", matrix.shape)
print("Data type:", matrix.dtype)

Matrix:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Shape: torch.Size([3, 3])
Data type: torch.int64
