# Inverse of a Rectangular Matrix (Moore-Penrose Pseudo-Inverse)

Unlike square matrices, rectangular matrices cannot have a traditional inverse. However, the **Moore-Penrose pseudo-inverse** $\mathbf{A}^{+}$ provides a generalized inverse for any rectangular matrix, enabling solutions to overdetermined and underdetermined linear systems.

## Definition

For a rectangular matrix $\mathbf{A}$ of size $m \times n$, the **Moore-Penrose pseudo-inverse** $\mathbf{A}^{+}$ is the unique matrix of size $n \times m$ satisfying four Penrose conditions.

### Primary Equation:

$$\mathbf{A}^{+} = (\mathbf{A}^{\text{T}} \mathbf{A})^{-1} \mathbf{A}^{\text{T}}$$

This formulation applies when $m > n$ (tall/overdetermined case where we have more equations than unknowns).

## Mathematical Formulation

### Case 1: Tall Matrix ($m > n$) - Overdetermined System

When the matrix has more rows than columns:

$$\mathbf{A}^{+} = (\mathbf{A}^{\text{T}} \mathbf{A})^{-1} \mathbf{A}^{\text{T}}$$

**Derivation from Primary Equation:**
- $\mathbf{A}^{\text{T}} \mathbf{A}$ is $n \times n$ and invertible if $\mathbf{A}$ has full column rank
- The pseudo-inverse satisfies: $\mathbf{A} \mathbf{A}^{+} = \mathbf{I}_m$ (only when $m = n$; for $m > n$ this is projection)

### Case 2: Wide Matrix ($m < n$) - Underdetermined System

When the matrix has more columns than rows:

$$\mathbf{A}^{+} = \mathbf{A}^{\text{T}} (\mathbf{A} \mathbf{A}^{\text{T}})^{-1}$$

**Derivation from Primary Equation:**
- $\mathbf{A} \mathbf{A}^{\text{T}}$ is $m \times m$ and invertible if $\mathbf{A}$ has full row rank
- The pseudo-inverse satisfies: $\mathbf{A}^{+} \mathbf{A} = \mathbf{I}_n$ (only when $m = n$; for $m < n$ this is projection)

### Case 3: Square Matrix ($m = n$) - Regular Inverse

When the matrix is square and invertible:

$$\mathbf{A}^{+} = \mathbf{A}^{-1}$$

**Derivation from Primary Equation:**
- The pseudo-inverse reduces to the traditional matrix inverse
- Both forms satisfy: $\mathbf{A} \mathbf{A}^{-1} = \mathbf{A}^{-1} \mathbf{A} = \mathbf{I}$

## Key Properties Derived from Primary Equation

These four properties are derived from the primary equation and characterize the pseudo-inverse:

### Property 1: $\mathbf{A} \mathbf{A}^{+} \mathbf{A} = \mathbf{A}$

Starting from $\mathbf{A}^{+} = (\mathbf{A}^{\text{T}} \mathbf{A})^{-1} \mathbf{A}^{\text{T}}$:

$$\mathbf{A} \mathbf{A}^{+} \mathbf{A} = \mathbf{A} \cdot (\mathbf{A}^{\text{T}} \mathbf{A})^{-1} \mathbf{A}^{\text{T}} \cdot \mathbf{A}$$

Since $(\mathbf{A}^{\text{T}} \mathbf{A})^{-1} (\mathbf{A}^{\text{T}} \mathbf{A}) = \mathbf{I}$:

$$\mathbf{A} \mathbf{A}^{+} \mathbf{A} = \mathbf{A}$$

### Property 2: $\mathbf{A}^{+} \mathbf{A} \mathbf{A}^{+} = \mathbf{A}^{+}$

Left-multiplying by $\mathbf{A}^{+}$ and right-multiplying by $\mathbf{A}^{+}$:

$$\mathbf{A}^{+} \mathbf{A} \mathbf{A}^{+} = (\mathbf{A}^{\text{T}} \mathbf{A})^{-1} \mathbf{A}^{\text{T}} \cdot \mathbf{A} \cdot (\mathbf{A}^{\text{T}} \mathbf{A})^{-1} \mathbf{A}^{\text{T}} = \mathbf{A}^{+}$$

### Property 3: $(\mathbf{A} \mathbf{A}^{+})^{\text{T}} = \mathbf{A} \mathbf{A}^{+}$ (Symmetric)

$$\left( \mathbf{A} \cdot (\mathbf{A}^{\text{T}} \mathbf{A})^{-1} \mathbf{A}^{\text{T}} \right)^{\text{T}} = \mathbf{A} \cdot (\mathbf{A}^{\text{T}} \mathbf{A})^{-1} \mathbf{A}^{\text{T}}$$

### Property 4: $(\mathbf{A}^{+} \mathbf{A})^{\text{T}} = \mathbf{A}^{+} \mathbf{A}$ (Symmetric)

$$\left( (\mathbf{A}^{\text{T}} \mathbf{A})^{-1} \mathbf{A}^{\text{T}} \cdot \mathbf{A} \right)^{\text{T}} = (\mathbf{A}^{\text{T}} \mathbf{A})^{-1} \mathbf{A}^{\text{T}} \cdot \mathbf{A}$$

In [32]:
import torch
import numpy as np

## Computing Pseudo-Inverse Using PyTorch

In [33]:
# Tall matrix (overdetermined, m > n)
A_tall = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]], dtype=torch.float32)

print("Tall Matrix A (3×2):")
print(A_tall)
print(f"Shape: {A_tall.shape}")

# Method 1: Using torch.linalg.pinv()
A_tall_pinv = torch.linalg.pinv(A_tall)
print(f"\nPseudo-Inverse A^+ using torch.linalg.pinv():")
print(A_tall_pinv)
print(f"Shape: {A_tall_pinv.shape}")

Tall Matrix A (3×2):
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
Shape: torch.Size([3, 2])

Pseudo-Inverse A^+ using torch.linalg.pinv():
tensor([[-1.3333, -0.3333,  0.6667],
        [ 1.0833,  0.3333, -0.4167]])
Shape: torch.Size([2, 3])


In [34]:
# Verify Property 1: A · A^+ · A = A
result_1 = torch.matmul(torch.matmul(A_tall, A_tall_pinv), A_tall)

print("Property 1: A · A^+ · A = A")
print(f"A · A^+ · A =")
print(result_1)
print(f"\nMatches A: {torch.allclose(result_1, A_tall)}")

Property 1: A · A^+ · A = A
A · A^+ · A =
tensor([[1.0000, 2.0000],
        [3.0000, 4.0000],
        [5.0000, 6.0000]])

Matches A: True


In [35]:
# Verify Property 2: A^+ · A · A^+ = A^+
result_2 = torch.matmul(torch.matmul(A_tall_pinv, A_tall), A_tall_pinv)

print("Property 2: A^+ · A · A^+ = A^+")
print(f"A^+ · A · A^+ =")
print(result_2)
print(f"\nMatches A^+: {torch.allclose(result_2, A_tall_pinv)}")

Property 2: A^+ · A · A^+ = A^+
A^+ · A · A^+ =
tensor([[-1.3333, -0.3333,  0.6667],
        [ 1.0833,  0.3333, -0.4167]])

Matches A^+: True


In [36]:
# Wide matrix (underdetermined, m < n)
B = torch.tensor([[1, 2, 3],
                   [4, 5, 6]], dtype=torch.float32)

print("Wide Matrix B (2×3):")
print(B)
print(f"Shape: {B.shape}")

B_pinv = torch.linalg.pinv(B)
print(f"\nPseudo-Inverse B^+:")
print(B_pinv)
print(f"Shape: {B_pinv.shape}")

Wide Matrix B (2×3):
tensor([[1., 2., 3.],
        [4., 5., 6.]])
Shape: torch.Size([2, 3])

Pseudo-Inverse B^+:
tensor([[-0.9444,  0.4444],
        [-0.1111,  0.1111],
        [ 0.7222, -0.2222]])
Shape: torch.Size([3, 2])


In [37]:
# Verify Property 1 for wide matrix: B · B^+ · B = B
result_B = torch.matmul(torch.matmul(B, B_pinv), B)

print("Property 1 (Wide): B · B^+ · B = B")
print(f"Result:")
print(result_B)
print(f"\nMatches B: {torch.allclose(result_B, B)}")

Property 1 (Wide): B · B^+ · B = B
Result:
tensor([[1.0000, 2.0000, 3.0000],
        [4.0000, 5.0000, 6.0000]])

Matches B: True


## Manual Computation of Pseudo-Inverse

In [38]:
# For tall matrix: A^+ = (A^T · A)^-1 · A^T

A_T = A_tall.T  # 2×3
ATA = torch.matmul(A_T, A_tall)  # 2×3 · 3×2 = 2×2
ATA_inv = torch.linalg.inv(ATA)  # 2×2
A_pinv_manual = torch.matmul(ATA_inv, A_T)  # 2×2 · 2×3 = 2×3

print("Tall Matrix Manual Computation:")
print(f"A^T · A =")
print(ATA)
print(f"\n(A^T · A)^-1 =")
print(ATA_inv)
print(f"\nA^+ = (A^T · A)^-1 · A^T =")
print(A_pinv_manual)
print(f"\nMatches torch.linalg.pinv result: {torch.allclose(A_pinv_manual, A_tall_pinv)}")

Tall Matrix Manual Computation:
A^T · A =
tensor([[35., 44.],
        [44., 56.]])

(A^T · A)^-1 =
tensor([[ 2.3333, -1.8333],
        [-1.8333,  1.4583]])

A^+ = (A^T · A)^-1 · A^T =
tensor([[-1.3333, -0.3333,  0.6667],
        [ 1.0833,  0.3333, -0.4167]])

Matches torch.linalg.pinv result: True


In [39]:
# For wide matrix: A^+ = A^T · (A · A^T)^-1

B_T = B.T  # 3×2
BBT = torch.matmul(B, B_T)  # 2×3 · 3×2 = 2×2
BBT_inv = torch.linalg.inv(BBT)  # 2×2
B_pinv_manual = torch.matmul(B_T, BBT_inv)  # 3×2 · 2×2 = 3×2

print("Wide Matrix Manual Computation:")
print(f"B · B^T =")
print(BBT)
print(f"\n(B · B^T)^-1 =")
print(BBT_inv)
print(f"\nB^+ = B^T · (B · B^T)^-1 =")
print(B_pinv_manual)
print(f"\nMatches torch.linalg.pinv result: {torch.allclose(B_pinv_manual, B_pinv)}")

Wide Matrix Manual Computation:
B · B^T =
tensor([[14., 32.],
        [32., 77.]])

(B · B^T)^-1 =
tensor([[ 1.4259, -0.5926],
        [-0.5926,  0.2593]])

B^+ = B^T · (B · B^T)^-1 =
tensor([[-0.9444,  0.4444],
        [-0.1111,  0.1111],
        [ 0.7222, -0.2222]])

Matches torch.linalg.pinv result: True


## Computing Pseudo-Inverse Using SVD

In [40]:
# Singular Value Decomposition: A = U · Σ · V^T
# Pseudo-Inverse: A^+ = V · Σ^+ · U^T

# Compute SVD
U, S, Vh = torch.linalg.svd(A_tall, full_matrices=False)

print("SVD Decomposition:")
print(f"U shape: {U.shape}")
print(f"S shape: {S.shape}")
print(f"Vh shape: {Vh.shape}")

print(f"\nU (3×2):\n{U}")
print(f"\nSingular values S:\n{S}")
print(f"\nVh (2×2):\n{Vh}")

SVD Decomposition:
U shape: torch.Size([3, 2])
S shape: torch.Size([2])
Vh shape: torch.Size([2, 2])

U (3×2):
tensor([[-0.2298,  0.8835],
        [-0.5247,  0.2408],
        [-0.8196, -0.4019]])

Singular values S:
tensor([9.5255, 0.5143])

Vh (2×2):
tensor([[-0.6196, -0.7849],
        [-0.7849,  0.6196]])


In [41]:
# Compute pseudo-inverse of S
# For diagonal matrix, pseudo-inverse just reciprocals non-zero values

S_pinv = 1.0 / S  # Element-wise reciprocal
print(f"S^+ (reciprocals of singular values):\n{S_pinv}")

# Create diagonal matrix S_pinv_diag (2×3)
S_pinv_diag = torch.zeros(Vh.shape[0], U.shape[0])  # 2×3
for i in range(len(S_pinv)):
    S_pinv_diag[i, i] = S_pinv[i]

print(f"\nS^+ as diagonal matrix (2×3):\n{S_pinv_diag}")

S^+ (reciprocals of singular values):
tensor([0.1050, 1.9444])

S^+ as diagonal matrix (2×3):
tensor([[0.1050, 0.0000, 0.0000],
        [0.0000, 1.9444, 0.0000]])


In [42]:
# A^+ = V · Σ^+ · U^T
# Note: torch.linalg.svd returns (U, S, Vh) where Vh = V^T
# So V = Vh.T and we need U^T which is U.T

V = Vh.T  # Transform Vh back to V: 2×2
U_T = U.T  # Transpose U to get U^T: 2×3

print(f"V shape: {V.shape}")
print(f"S_pinv_diag shape: {S_pinv_diag.shape}")
print(f"U_T shape: {U_T.shape}")

# Compute A^+ = V · Σ^+ · U^T
# (2×2) · (2×3) · (3×?) - Wait, this is wrong!
# Actually torch.linalg.svd with full_matrices=False returns:
# U: m×k, S: k, Vh: k×n (where k = min(m,n))
# For A (3×2): U is 3×2, S is 2, Vh is 2×2
# So A^+ should use U NOT U^T
# A^+ = V · Σ^+ · U^T where V comes from SVD's Vh
# The correct formula: A^+ = (Vh^T) · Σ^+ · (U^T)
# But simpler: A^+ = Vh^T · Σ^+ · U^T

# Actually, let me reconsider:
# SVD: A = U · Σ · V^T  (PyTorch returns Vh = V^T)
# A^+ = V · Σ^+ · U^T = Vh^T · Σ^+ · U^T

# For our case with A (3×2): U (3×2), Σ (2), Vh (2×2)
# We need: Vh^T (2×2) · Σ^+ (2×3) · U^T (2×3)
# But 2×3 · 2×3 doesn't work!

# The correct order should be: Vh^T · Σ^+ · U^T
# which is (2×2) · (2×3) · (2×3) - still wrong!

# Let me recalculate: If A = U · Σ · Vh, then
# A^+ = Vh^T · Σ^+ · U^T
# For shapes: (2×2) · (2×3) · (3×2) = (2×3)
# So we don't need U.T, we need just U^T as computed from U!
# Wait: U is 3×2, so U.T is 2×3 ✓

# The issue is S_pinv_diag: it should be (2×3)
# But we multiply (2×2) · (2×3) which gives (2×3)
# Then (2×3) · (2×3) which is wrong!

# Let me fix: S_pinv_diag should be used as (2×3) diagonal
# So multiplication should be: V (2×2) · S_pinv_diag (2×3) = result (2×3)
# Then result (2×3) · U.T (2×3) is still wrong!

# Aha! U.T should be (3×2)^T = (2×3), but we need the transpose
# to give us a (2×3) on the right side
# Actually: U (3×2) means U.T is (2×3)

# Let me think differently:
# A (m×n) = U (m×k) · Σ (k×k) · Vh (k×n)
# A^+ (n×m) = Vh^T (n×k) · Σ^+ (k×k) · U^T (k×m)
# For A (3×2): U (3×2), Σ (2), Vh (2×2)
# A^+ (2×3) = Vh^T (2×2) · Σ^+ (2×2) · U^T (2×3)
# Result: (2×2) · (2×2) · (2×3) = (2×3) ✓

# So the fix: don't make S_pinv_diag (2×3), keep it (2×2)!

# Recalculate with proper dimensions
U_actual_T = U.T  # This will be 2×3 - WRONG! Should use U as is
# For formula A^+ = Vh^T · Σ^+ · U^T, where U^T means transpose of U
# U is 3×2, so U^T is 2×3 - but that's wrong for our formula!

# Correct formula using SVD factors:
# A^+ = Vh^T · diag(1/σ) · U^T  (where σ are singular values from Σ)
# But torch.linalg.svd returns U, S (vector), Vh
# So: A^+ = Vh.T · diag(1/S) · U.T

# For shapes: A (3×2) with k=2
# Vh is 2×2, U is 3×2
# Vh.T is 2×2, diag(1/S) is 2×2, U.T is 2×3
# (2×2) · (2×2) · (2×3) = (2×3) ✓ BUT that's wrong!

# CORRECT INTERPRETATION:
# torch.linalg.svd(A) gives U, S, Vh where A = U @ diag(S) @ Vh
# For A (3×2): U (3×2), S (2,), Vh (2×2)
# A^+ = Vh^T @ diag(1/S) @ U^T
# Dimensions: (2×2) @ (2×2) @ (2×3) - STILL WRONG!

# WAIT - I need to think about which U and which formula!
# If A = U @ Σ @ V^T, then A^+ = V @ Σ^+ @ U^T
# torch.linalg.svd returns U, S, Vh=V^T
# So A^+ = (Vh^T) @ Σ^+ @ U^T
# Vh^T = V (the actual V matrix)
# U^T = transpose of U

# For shapes with torch output:
# U: (3×2), S: (2,), Vh: (2×2)
# V = Vh^T: (2×2), U^T: (2×3)
# Σ^+: (2×2) diagonal

# A^+ formula: V @ Σ^+ @ U^T
# = (2×2) @ (2×2) @ (2×3) = WRONG multiply!

# ARGH! The issue is U^T has the WRONG dimensions!
# U is (3×2), so U^T is (2×3)
# But formula needs the transpose operation to reduce from m to k!

# Let me look at this differently:
# Standard: A^+ = V @ Σ^+ @ U^T where shapes are
# V (n×k) @ Σ^+ (k×k) @ U^T (k×m) = A^+ (n×m)
# For us: (2×2) @ (2×2) @ (2×3) = (2×3) ✓ but that's wrong!

# OH! I see the bug - U^T should be (2×3) NOT (3×2)!
# If U is (3×2), U^T is (2×3) which is WRONG!
# We need something (k×m) = (2×3) to multiply from the right

# Actually wait - (2×2) @ (2×2) @ (2×3) should give (2×3)!
# Let me recalculate: (2×2) @ (2×2) = (2×2)
# Then (2×2) @ (2×3) = (2×3) ✓

# So the issue must be that S_pinv_diag is WRONG shape
# It should be (2×2) not (2×3)!

# Let's use the correct approach: don't make S_pinv_diag at all
# Just use S_pinv directly as a vector and handle it properly

S_pinv_matrix = torch.diag(S_pinv)  # (2×2) diagonal matrix
print(f"S_pinv as diagonal matrix (2×2):\n{S_pinv_matrix}")

# Now: V (2×2) @ S_pinv_matrix (2×2) @ U.T (2×3)
# = (2×2) @ (2×2) @ (2×3)
# = (2×2) @ (2×3)
# = (2×3) ✓

A_pinv_svd = torch.matmul(torch.matmul(V, S_pinv_matrix), U.T)

print(f"\nA^+ from SVD (2×3):\n{A_pinv_svd}")
print(f"A^+ from torch.linalg.pinv (2×3):\n{A_tall_pinv}")
print(f"\nMatches: {torch.allclose(A_pinv_svd, A_tall_pinv)}")


V shape: torch.Size([2, 2])
S_pinv_diag shape: torch.Size([2, 3])
U_T shape: torch.Size([2, 3])
S_pinv as diagonal matrix (2×2):
tensor([[0.1050, 0.0000],
        [0.0000, 1.9444]])

A^+ from SVD (2×3):
tensor([[-1.3333, -0.3333,  0.6667],
        [ 1.0833,  0.3333, -0.4167]])
A^+ from torch.linalg.pinv (2×3):
tensor([[-1.3333, -0.3333,  0.6667],
        [ 1.0833,  0.3333, -0.4167]])

Matches: True


## Applications of Pseudo-Inverse

### Application 1: Solving Overdetermined Systems (Least Squares)

In [43]:
# Overdetermined system: A·x = b with more equations than unknowns
# Best solution (least squares): x = A^+ · b

A = torch.tensor([[1, 0],
                   [1, 1],
                   [1, 2]], dtype=torch.float32)  # 3×2
b = torch.tensor([[1],
                   [2],
                   [2]], dtype=torch.float32)  # 3×1

print("Overdetermined System:")
print(f"A (3×2) =\n{A}")
print(f"b (3×1) =\n{b}")

A_pinv = torch.linalg.pinv(A)
x = torch.matmul(A_pinv, b)

print(f"\nLeast squares solution x = A^+ · b:\n{x}")

# Compute residual
residual = torch.matmul(A, x) - b
print(f"\nResidual A·x - b:\n{residual}")
print(f"Residual norm: {torch.linalg.norm(residual).item():.4f}")

Overdetermined System:
A (3×2) =
tensor([[1., 0.],
        [1., 1.],
        [1., 2.]])
b (3×1) =
tensor([[1.],
        [2.],
        [2.]])

Least squares solution x = A^+ · b:
tensor([[1.1667],
        [0.5000]])

Residual A·x - b:
tensor([[ 0.1667],
        [-0.3333],
        [ 0.1667]])
Residual norm: 0.4082


### Application 2: Solving Underdetermined Systems (Minimum Norm)

In [44]:
# Underdetermined system: A·x = b with fewer equations than unknowns
# Minimum norm solution: x = A^+ · b

A = torch.tensor([[1, 2, 3],
                   [4, 5, 6]], dtype=torch.float32)  # 2×3
b = torch.tensor([[10],
                   [20]], dtype=torch.float32)  # 2×1

print("Underdetermined System:")
print(f"A (2×3) =\n{A}")
print(f"b (2×1) =\n{b}")

A_pinv = torch.linalg.pinv(A)
x = torch.matmul(A_pinv, b)

print(f"\nMinimum norm solution x = A^+ · b:\n{x}")

# Verify solution
check = torch.matmul(A, x)
print(f"\nVerification A·x =\n{check}")
print(f"Matches b: {torch.allclose(check, b)}")
print(f"\nSolution norm: {torch.linalg.norm(x).item():.4f}")

Underdetermined System:
A (2×3) =
tensor([[1., 2., 3.],
        [4., 5., 6.]])
b (2×1) =
tensor([[10.],
        [20.]])

Minimum norm solution x = A^+ · b:
tensor([[-0.5556],
        [ 1.1111],
        [ 2.7778]])

Verification A·x =
tensor([[10.0000],
        [20.0000]])
Matches b: True

Solution norm: 3.0429


### Application 3: Polynomial Fitting (Data Fitting)

In [45]:
# Fit polynomial to data points using pseudo-inverse
# Fit quadratic: y = a + bx + cx^2

x_data = torch.tensor([0, 1, 2, 3, 4], dtype=torch.float32)
y_data = torch.tensor([1, 3, 7, 13, 21], dtype=torch.float32)  # Actual: y = 1 + x + x^2

# Build design matrix (each row is [1, x, x^2])
X = torch.stack([torch.ones_like(x_data), x_data, x_data**2], dim=1)

print("Polynomial Fitting Example:")
print(f"X (design matrix, 5×3) =\n{X}")
print(f"y (data, 5×1) = {y_data}")

# Compute coefficients using pseudo-inverse
X_pinv = torch.linalg.pinv(X)
coeffs = torch.matmul(X_pinv, y_data)

print(f"\nCoefficients [a, b, c]: {coeffs}")
print(f"Fitted polynomial: y = {coeffs[0]:.1f} + {coeffs[1]:.1f}x + {coeffs[2]:.1f}x²")

# Verify fit
y_pred = torch.matmul(X, coeffs)
print(f"\nPredicted values: {y_pred}")
print(f"Actual values: {y_data}")
print(f"Perfect fit: {torch.allclose(y_pred, y_data)}")

Polynomial Fitting Example:
X (design matrix, 5×3) =
tensor([[ 1.,  0.,  0.],
        [ 1.,  1.,  1.],
        [ 1.,  2.,  4.],
        [ 1.,  3.,  9.],
        [ 1.,  4., 16.]])
y (data, 5×1) = tensor([ 1.,  3.,  7., 13., 21.])

Coefficients [a, b, c]: tensor([1.0000, 1.0000, 1.0000])
Fitted polynomial: y = 1.0 + 1.0x + 1.0x²

Predicted values: tensor([ 1.0000,  3.0000,  7.0000, 13.0000, 21.0000])
Actual values: tensor([ 1.,  3.,  7., 13., 21.])
Perfect fit: True


### Application 4: Image Deblurring (Deconvolution)

In [46]:
# Simple 1D deblurring example using pseudo-inverse
# Blur operator: A (convolution matrix)
# Blurred image: b = A · x_original
# Recovered image: x_recovered = A^+ · b

# Simple blur kernel [0.25, 0.5, 0.25] (averaging filter)
# Create blur matrix for signal of length 5
A = torch.tensor([[0.5, 0.25, 0.0, 0.0, 0.0],
                   [0.25, 0.5, 0.25, 0.0, 0.0],
                   [0.0, 0.25, 0.5, 0.25, 0.0],
                   [0.0, 0.0, 0.25, 0.5, 0.25],
                   [0.0, 0.0, 0.0, 0.25, 0.5]], dtype=torch.float32)

# Original signal
x_original = torch.tensor([1, 0, 1, 0, 1], dtype=torch.float32)

print("Image Deblurring Example:")
print(f"Original signal: {x_original}")

# Apply blur
b = torch.matmul(A, x_original)
print(f"Blurred signal: {b}")

# Recover using pseudo-inverse
A_pinv = torch.linalg.pinv(A)
x_recovered = torch.matmul(A_pinv, b)
print(f"Recovered signal: {x_recovered}")
print(f"Recovery error norm: {torch.linalg.norm(x_recovered - x_original).item():.4f}")

Image Deblurring Example:
Original signal: tensor([1., 0., 1., 0., 1.])
Blurred signal: tensor([0.5000, 0.5000, 0.5000, 0.5000, 0.5000])
Recovered signal: tensor([1.0000e+00, 0.0000e+00, 1.0000e+00, 2.9802e-07, 1.0000e+00])
Recovery error norm: 0.0000


## Square vs Rectangular Inverses

In [47]:
# Comparison of square and rectangular matrix inverses

# Square matrix
A_square = torch.tensor([[4, 7],
                          [2, 6]], dtype=torch.float32)

# Rectangular (tall) matrix
A_tall = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]], dtype=torch.float32)

print("Square Matrix (2×2):")
print(f"A ={A_square}")
A_sq_inv = torch.linalg.inv(A_square)
print(f"A^-1 ={A_sq_inv}")
print(f"A · A^-1 ={torch.matmul(A_square, A_sq_inv)}")

print(f"\nRectangular Matrix (3×2):")
print(f"A ={A_tall}")
A_tall_pinv = torch.linalg.pinv(A_tall)
print(f"A^+ ={A_tall_pinv}")
print(f"A · A^+ ={torch.matmul(A_tall, A_tall_pinv)}")
print(f"Note: A · A^+ is projection matrix (not identity)")

Square Matrix (2×2):
A =tensor([[4., 7.],
        [2., 6.]])
A^-1 =tensor([[ 0.6000, -0.7000],
        [-0.2000,  0.4000]])
A · A^-1 =tensor([[1.0000, 0.0000],
        [0.0000, 1.0000]])

Rectangular Matrix (3×2):
A =tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
A^+ =tensor([[-1.3333, -0.3333,  0.6667],
        [ 1.0833,  0.3333, -0.4167]])
A · A^+ =tensor([[ 0.8333,  0.3333, -0.1667],
        [ 0.3333,  0.3333,  0.3333],
        [-0.1667,  0.3333,  0.8333]])
Note: A · A^+ is projection matrix (not identity)


# Inverse of a Rectangular Matrix

Rectangular matrices (non-square) do not have a traditional inverse, but they have a **pseudo-inverse** (Moore-Penrose inverse) which generalizes the concept of matrix inversion to rectangular matrices.

## Definition

For a rectangular matrix $\mathbf{A}$ of size $m \times n$ (where $m \neq n$), the **pseudo-inverse** (Moore-Penrose inverse) denoted as $\mathbf{A}^{+}$ is a generalized inverse that extends the concept of matrix inversion to non-square matrices.

### Primary Equation (General Formula):

$$\mathbf{A}^{+} = (\mathbf{A}^T\mathbf{A})^{-1} \mathbf{A}^T$$

This is the fundamental formula for the pseudo-inverse.

## Mathematical Formulation

The pseudo-inverse formula varies depending on the dimensions of the matrix. All cases are derived from the primary principle of least-squares solutions.

### Case 1: Tall Matrices (m > n) - More Rows than Columns

**Derivation:** When a matrix has more rows than columns, we use the formula:

$$\mathbf{A}^{+} = (\mathbf{A}^T \mathbf{A})^{-1} \mathbf{A}^T$$

**Why this works:** $\mathbf{A}^T \mathbf{A}$ is a square $(n \times n)$ matrix and is invertible when $\mathbf{A}$ has full column rank.

**Result:** 
$$\mathbf{A}^{+} \mathbf{A} = \mathbf{I}_{n \times n}$$

This is called the **left pseudo-inverse** because left-multiplying $\mathbf{A}$ by $\mathbf{A}^{+}$ gives the identity.

---

### Case 2: Wide Matrices (m < n) - More Columns than Rows

**Derivation:** When a matrix has more columns than rows, we use a different approach:

$$\mathbf{A}^{+} = \mathbf{A}^T (\mathbf{A} \mathbf{A}^T)^{-1}$$

**Why this works:** $\mathbf{A} \mathbf{A}^T$ is a square $(m \times m)$ matrix and is invertible when $\mathbf{A}$ has full row rank.

**Result:** 
$$\mathbf{A} \mathbf{A}^{+} = \mathbf{I}_{m \times m}$$

This is called the **right pseudo-inverse** because right-multiplying by $\mathbf{A}^{+}$ gives the identity.

---

### Case 3: Square Matrices (m = n) - Equal Rows and Columns

**Derivation:** For square matrices, if $\mathbf{A}$ is non-singular (invertible):

$$\mathbf{A}^{+} = (\mathbf{A}^T \mathbf{A})^{-1} \mathbf{A}^T = \mathbf{A}^{-1}$$

**Result:** 
$$\mathbf{A}^{+} \mathbf{A} = \mathbf{A} \mathbf{A}^{+} = \mathbf{I}_{n \times n}$$

The pseudo-inverse **equals** the traditional inverse for non-singular square matrices.

In [48]:
import torch

## Computing Pseudo-Inverse Using PyTorch

## Key Properties Derived from Primary Equation

### Property 1: Product with Original Matrix

From $\mathbf{A}^{+} = (\mathbf{A}^T\mathbf{A})^{-1} \mathbf{A}^T$, we derive:

$$\mathbf{A}^{+} \mathbf{A} = (\mathbf{A}^T\mathbf{A})^{-1} \mathbf{A}^T \mathbf{A} = (\mathbf{A}^T\mathbf{A})^{-1} (\mathbf{A}^T\mathbf{A}) = \mathbf{I}$$

**Property:** The product of the pseudo-inverse to its original matrix is an identity matrix (for tall matrices).

---

### Property 2: Inverse Symmetry

From the definition:

$$\mathbf{A}^{+} \mathbf{A} \mathbf{A}^{+} = \mathbf{I} \cdot \mathbf{A}^{+} = \mathbf{A}^{+}$$

$$\mathbf{A} \mathbf{A}^{+} \mathbf{A} = \mathbf{A} \cdot \mathbf{I} = \mathbf{A}$$

**Property:** Both products satisfy the Moore-Penrose conditions due to the symmetry of the formulation.

---

### Property 3: Double Pseudo-Inverse

Taking the pseudo-inverse of the pseudo-inverse returns the original:

$$(\mathbf{A}^{+})^{+} = \mathbf{A}$$

**Property:** The operation is involutive (applying it twice gives back the original).

---

### Property 4: Transpose Relationship

From $\mathbf{A}^{+} = (\mathbf{A}^T\mathbf{A})^{-1} \mathbf{A}^T$:

$$(A^{+})^T = (\mathbf{A}^T)^{+}$$

**Property:** The pseudo-inverse of the transpose equals the transpose of the pseudo-inverse.

In [49]:
# Tall matrix (3×2)
A_tall = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]], dtype=torch.float32)

print("Tall Matrix A (3×2):")
print(A_tall)
print(f"Shape: {A_tall.shape}")

# Compute pseudo-inverse
A_tall_pinv = torch.linalg.pinv(A_tall)
print(f"\nPseudo-inverse A+ (2×3):")
print(A_tall_pinv)
print(f"Shape: {A_tall_pinv.shape}")

Tall Matrix A (3×2):
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
Shape: torch.Size([3, 2])

Pseudo-inverse A+ (2×3):
tensor([[-1.3333, -0.3333,  0.6667],
        [ 1.0833,  0.3333, -0.4167]])
Shape: torch.Size([2, 3])


In [50]:
# Wide matrix (2×3)
A_wide = torch.tensor([[1, 2, 3],
                        [4, 5, 6]], dtype=torch.float32)

print("Wide Matrix A (2×3):")
print(A_wide)
print(f"Shape: {A_wide.shape}")

# Compute pseudo-inverse
A_wide_pinv = torch.linalg.pinv(A_wide)
print(f"\nPseudo-inverse A+ (3×2):")
print(A_wide_pinv)
print(f"Shape: {A_wide_pinv.shape}")

Wide Matrix A (2×3):
tensor([[1., 2., 3.],
        [4., 5., 6.]])
Shape: torch.Size([2, 3])

Pseudo-inverse A+ (3×2):
tensor([[-0.9444,  0.4444],
        [-0.1111,  0.1111],
        [ 0.7222, -0.2222]])
Shape: torch.Size([3, 2])


## Properties of Pseudo-Inverse

### Property 1: A+ · A = I (for tall matrices)

In [51]:
# For tall matrix: A+ · A should be identity
product_tall = torch.matmul(A_tall_pinv, A_tall)
identity_n = torch.eye(A_tall.shape[1])

print("A+ · A (should be I for tall matrix):")
print(product_tall)
print(f"\nIdentity matrix I:")
print(identity_n)
print(f"\nA+ · A = I: {torch.allclose(product_tall, identity_n)}")

A+ · A (should be I for tall matrix):
tensor([[1.0000e+00, 2.3842e-07],
        [9.5367e-07, 1.0000e+00]])

Identity matrix I:
tensor([[1., 0.],
        [0., 1.]])

A+ · A = I: False


### Property 2: A · A+ = I (for wide matrices)

In [52]:
# For wide matrix: A · A+ should be identity
product_wide = torch.matmul(A_wide, A_wide_pinv)
identity_m = torch.eye(A_wide.shape[0])

print("A · A+ (should be I for wide matrix):")
print(product_wide)
print(f"\nIdentity matrix I:")
print(identity_m)
print(f"\nA · A+ = I: {torch.allclose(product_wide, identity_m)}")

A · A+ (should be I for wide matrix):
tensor([[ 1.0000e+00, -5.9605e-08],
        [-4.7684e-07,  1.0000e+00]])

Identity matrix I:
tensor([[1., 0.],
        [0., 1.]])

A · A+ = I: False


### Property 3: (A+)+ = A

In [53]:
# Double pseudo-inverse should give back original matrix
A_tall_pinv_pinv = torch.linalg.pinv(A_tall_pinv)

print("(A+)+ (should equal A):")
print(A_tall_pinv_pinv)
print(f"\nOriginal A:")
print(A_tall)
print(f"\n(A+)+ = A: {torch.allclose(A_tall_pinv_pinv, A_tall)}")

(A+)+ (should equal A):
tensor([[1.0000, 2.0000],
        [3.0000, 4.0000],
        [5.0000, 6.0000]])

Original A:
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

(A+)+ = A: True


### Property 4: (A+)T = (AT)+

The pseudo-inverse of the transpose equals the transpose of the pseudo-inverse

In [54]:
A_T_pinv = torch.linalg.pinv(A_tall.T)
A_pinv_T = A_tall_pinv.T

print("(A+)T:")
print(A_pinv_T)
print(f"\n(AT)+:")
print(A_T_pinv)
print(f"\n(A+)T = (AT)+: {torch.allclose(A_pinv_T, A_T_pinv)}")

(A+)T:
tensor([[-1.3333,  1.0833],
        [-0.3333,  0.3333],
        [ 0.6667, -0.4167]])

(AT)+:
tensor([[-1.3333,  1.0833],
        [-0.3333,  0.3333],
        [ 0.6667, -0.4167]])

(A+)T = (AT)+: True


## Computing Pseudo-Inverse Manually

### For Tall Matrix (m > n): A+ = (AT·A)^-1·AT

In [55]:
# Manual computation for tall matrix
A = torch.tensor([[1, 2],
                   [3, 4],
                   [5, 6]], dtype=torch.float32)

print("Matrix A (3×2):")
print(A)

# Compute (AT·A)^-1·AT
A_T = A.T
ATA = torch.matmul(A_T, A)
ATA_inv = torch.linalg.inv(ATA)
A_pinv_manual = torch.matmul(ATA_inv, A_T)

print(f"\nAT·A = \n{ATA}")
print(f"\n(AT·A)^-1 = \n{ATA_inv}")
print(f"\nA+ = (AT·A)^-1·AT = \n{A_pinv_manual}")

# Compare with PyTorch result
A_pinv_pytorch = torch.linalg.pinv(A)
print(f"\nPyTorch result:\n{A_pinv_pytorch}")
print(f"\nManual matches PyTorch: {torch.allclose(A_pinv_manual, A_pinv_pytorch)}")

Matrix A (3×2):
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

AT·A = 
tensor([[35., 44.],
        [44., 56.]])

(AT·A)^-1 = 
tensor([[ 2.3333, -1.8333],
        [-1.8333,  1.4583]])

A+ = (AT·A)^-1·AT = 
tensor([[-1.3333, -0.3333,  0.6667],
        [ 1.0833,  0.3333, -0.4167]])

PyTorch result:
tensor([[-1.3333, -0.3333,  0.6667],
        [ 1.0833,  0.3333, -0.4167]])

Manual matches PyTorch: True


### For Wide Matrix (m < n): A+ = AT·(A·AT)^-1

In [56]:
# Manual computation for wide matrix
B = torch.tensor([[1, 2, 3],
                   [4, 5, 6]], dtype=torch.float32)

print("Matrix B (2×3):")
print(B)

# Compute AT·(A·AT)^-1
B_T = B.T
BB_T = torch.matmul(B, B_T)
BB_T_inv = torch.linalg.inv(BB_T)
B_pinv_manual = torch.matmul(B_T, BB_T_inv)

print(f"\nB·BT = \n{BB_T}")
print(f"\n(B·BT)^-1 = \n{BB_T_inv}")
print(f"\nB+ = BT·(B·BT)^-1 = \n{B_pinv_manual}")

# Compare with PyTorch result
B_pinv_pytorch = torch.linalg.pinv(B)
print(f"\nPyTorch result:\n{B_pinv_pytorch}")
print(f"\nManual matches PyTorch: {torch.allclose(B_pinv_manual, B_pinv_pytorch)}")

Matrix B (2×3):
tensor([[1., 2., 3.],
        [4., 5., 6.]])

B·BT = 
tensor([[14., 32.],
        [32., 77.]])

(B·BT)^-1 = 
tensor([[ 1.4259, -0.5926],
        [-0.5926,  0.2593]])

B+ = BT·(B·BT)^-1 = 
tensor([[-0.9444,  0.4444],
        [-0.1111,  0.1111],
        [ 0.7222, -0.2222]])

PyTorch result:
tensor([[-0.9444,  0.4444],
        [-0.1111,  0.1111],
        [ 0.7222, -0.2222]])

Manual matches PyTorch: True


## Applications of Pseudo-Inverse

### Application 1: Solving Overdetermined Systems (Least Squares)

In [57]:
# Overdetermined system: more equations than unknowns (m > n)
# A·x = b has no exact solution, find least squares solution

A = torch.tensor([[1, 0],
                   [1, 1],
                   [1, 2],
                   [1, 3]], dtype=torch.float32)
b = torch.tensor([[1],
                   [2],
                   [2],
                   [3]], dtype=torch.float32)

print("Overdetermined System: A·x = b")
print(f"A (4×2):\n{A}")
print(f"b (4×1):\n{b}")

# Solve using pseudo-inverse
x = torch.matmul(torch.linalg.pinv(A), b)
print(f"\nLeast squares solution x = A+·b:\n{x}")

# Check residual
residual = torch.matmul(A, x) - b
residual_norm = torch.norm(residual)
print(f"\nResidual: A·x - b =\n{residual}")
print(f"Residual norm: {residual_norm}")

Overdetermined System: A·x = b
A (4×2):
tensor([[1., 0.],
        [1., 1.],
        [1., 2.],
        [1., 3.]])
b (4×1):
tensor([[1.],
        [2.],
        [2.],
        [3.]])

Least squares solution x = A+·b:
tensor([[1.1000],
        [0.6000]])

Residual: A·x - b =
tensor([[ 0.1000],
        [-0.3000],
        [ 0.3000],
        [-0.1000]])
Residual norm: 0.44721361994743347


### Application 2: Solving Underdetermined Systems

In [58]:
# Underdetermined system: fewer equations than unknowns (m < n)
# A·x = b has infinite solutions, find minimum norm solution

A = torch.tensor([[1, 2, 3],
                   [4, 5, 6]], dtype=torch.float32)
b = torch.tensor([[7],
                   [8]], dtype=torch.float32)

print("Underdetermined System: A·x = b")
print(f"A (2×3):\n{A}")
print(f"b (2×1):\n{b}")

# Solve using pseudo-inverse (minimum norm solution)
x = torch.matmul(torch.linalg.pinv(A), b)
print(f"\nMinimum norm solution x = A+·b:\n{x}")

# Verify the solution
result = torch.matmul(A, x)
print(f"\nVerification: A·x =\n{result}")
print(f"Matches b: {torch.allclose(result, b)}")

# Check norm
x_norm = torch.norm(x)
print(f"\nNorm of solution: ||x|| = {x_norm}")

Underdetermined System: A·x = b
A (2×3):
tensor([[1., 2., 3.],
        [4., 5., 6.]])
b (2×1):
tensor([[7.],
        [8.]])

Minimum norm solution x = A+·b:
tensor([[-3.0556],
        [ 0.1111],
        [ 3.2778]])

Verification: A·x =
tensor([[7.0000],
        [8.0000]])
Matches b: True

Norm of solution: ||x|| = 4.482475757598877


### Application 3: Data Fitting and Linear Regression

In [59]:
# Fit a polynomial to data points
# Data: fit y = a + b*x + c*x^2

# Data points
x_data = torch.tensor([0, 1, 2, 3, 4], dtype=torch.float32)
y_data = torch.tensor([1, 2, 4, 7, 11], dtype=torch.float32)

# Design matrix for quadratic: [1, x, x^2]
ones = torch.ones(len(x_data), 1)
x_col = x_data.unsqueeze(1)
x2_col = (x_data ** 2).unsqueeze(1)
A = torch.cat([ones, x_col, x2_col], dim=1)
b = y_data.unsqueeze(1)

print("Design matrix A (fit y = a + b*x + c*x^2):")
print(A)
print(f"\nData points b:\n{b.squeeze()}")

# Solve for coefficients using pseudo-inverse
coeffs = torch.matmul(torch.linalg.pinv(A), b)
a, b_coeff, c = coeffs.squeeze()

print(f"\nCoefficients:")
print(f"a = {a:.4f}")
print(f"b = {b_coeff:.4f}")
print(f"c = {c:.4f}")
print(f"\nFitted curve: y = {a:.4f} + {b_coeff:.4f}*x + {c:.4f}*x^2")

Design matrix A (fit y = a + b*x + c*x^2):
tensor([[ 1.,  0.,  0.],
        [ 1.,  1.,  1.],
        [ 1.,  2.,  4.],
        [ 1.,  3.,  9.],
        [ 1.,  4., 16.]])

Data points b:
tensor([ 1.,  2.,  4.,  7., 11.])

Coefficients:
a = 1.0000
b = 0.5000
c = 0.5000

Fitted curve: y = 1.0000 + 0.5000*x + 0.5000*x^2


### Application 4: Image Processing (Blur/Noise Removal)

In [60]:
# Simulate image deblurring using pseudo-inverse
# Blurred image: b = A·x (A is blur operator, x is original)
# Recover x: x = A+·b

# Create a simple blur operator (3×5)
A_blur = torch.tensor([[1, 1, 0, 0, 0],
                        [0, 1, 1, 0, 0],
                        [0, 0, 1, 1, 0]], dtype=torch.float32) / 2

# Original image (5 pixels)
original = torch.tensor([[100],
                          [50],
                          [200],
                          [150],
                          [75]], dtype=torch.float32)

# Blurred image
blurred = torch.matmul(A_blur, original)

print("Original image (5 pixels):")
print(original.squeeze())
print(f"\nBlur operator A (3×5):\n{A_blur}")
print(f"\nBlurred image (3 pixels):\n{blurred.squeeze()}")

# Recover using pseudo-inverse
recovered = torch.matmul(torch.linalg.pinv(A_blur), blurred)
print(f"\nRecovered image (using A+):\n{recovered.squeeze()}")
print(f"\nRecovery error:\n{torch.abs(recovered - original).squeeze()}")

Original image (5 pixels):
tensor([100.,  50., 200., 150.,  75.])

Blur operator A (3×5):
tensor([[0.5000, 0.5000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.5000, 0.5000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.5000, 0.5000, 0.0000]])

Blurred image (3 pixels):
tensor([ 75., 125., 175.])

Recovered image (using A+):
tensor([ 75.0000,  75.0000, 175.0000, 175.0000,   0.0000])

Recovery error:
tensor([25.0000, 25.0000, 25.0000, 25.0000, 75.0000])


## Comparison with Square Matrix Inverse

In [61]:
# Square matrix: pseudo-inverse = true inverse (if non-singular)
A_square = torch.tensor([[1, 2],
                          [3, 4]], dtype=torch.float32)

A_inv = torch.linalg.inv(A_square)
A_pinv = torch.linalg.pinv(A_square)

print("Square Matrix A:")
print(A_square)
print(f"\nTrue Inverse A^-1:\n{A_inv}")
print(f"\nPseudo-Inverse A+:\n{A_pinv}")
print(f"\nA^-1 ≈ A+: {torch.allclose(A_inv, A_pinv)}")

Square Matrix A:
tensor([[1., 2.],
        [3., 4.]])

True Inverse A^-1:
tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])

Pseudo-Inverse A+:
tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])

A^-1 ≈ A+: True


## Singular Value Decomposition (SVD) and Pseudo-Inverse

The pseudo-inverse can be computed efficiently using SVD:
$$\mathbf{A} = \mathbf{U} \mathbf{\Sigma} \mathbf{V}^T$$
$$\mathbf{A}^{+} = \mathbf{V} \mathbf{\Sigma}^{+} \mathbf{U}^T$$

In [62]:
# Compute pseudo-inverse using SVD
A = torch.tensor([[1, 2],
                   [3, 4],
                   [5, 6]], dtype=torch.float32)

print("Matrix A:")
print(A)

# SVD decomposition: A = Utorch.matmul(diag(S)torch.matmul(V^T
# torch.svd returns U, S, V (where V is V, not V^T)
U, S, V = torch.svd(A)

print(f"\nU (3×2):\n{U}")
print(f"\nSingular values: {S}")
print(f"\nV (2×2):\n{V}")

# Compute pseudo-inverse from SVD
# A+ = Vtorch.matmul(Σ+torch.matmul(U^T
S_pinv = torch.where(S > 1e-10, 1/S, torch.zeros_like(S))
S_pinv_diag = torch.diag(S_pinv)

# Construct pseudo-inverse: Vtorch.matmul(diag(S+)torch.matmul(U^T
# V is (2×2), S_pinv_diag is (2×2), U.T is (2×3)
# (2×2)torch.matmul((2×2)torch.matmul((2×3) = (2×3) ✓
A_pinv_svd = torch.matmul(torch.matmul(V, S_pinv_diag), U.T)

print(f"\nPseudo-inverse from SVD:\n{A_pinv_svd}")

# Compare with PyTorch result
A_pinv_pytorch = torch.linalg.pinv(A)
print(f"\nPyTorch result:\n{A_pinv_pytorch}")
print(f"\nSVD matches PyTorch: {torch.allclose(A_pinv_svd, A_pinv_pytorch)}")

Matrix A:
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

U (3×2):
tensor([[-0.2298,  0.8835],
        [-0.5247,  0.2408],
        [-0.8196, -0.4019]])

Singular values: tensor([9.5255, 0.5143])

V (2×2):
tensor([[-0.6196, -0.7849],
        [-0.7849,  0.6196]])

Pseudo-inverse from SVD:
tensor([[-1.3333, -0.3333,  0.6667],
        [ 1.0833,  0.3333, -0.4167]])

PyTorch result:
tensor([[-1.3333, -0.3333,  0.6667],
        [ 1.0833,  0.3333, -0.4167]])

SVD matches PyTorch: True
