# Theorems and Proofs: Eigen Analysis

This notebook consolidates all key theorems, definitions, and mathematical properties from eigen analysis. Each theorem is accompanied by formal definitions, rigorous proofs, and computational verification.

In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

## I. Fundamental Definitions

### Definition 1.1: Eigenvalue and Eigenvector

For a square matrix $\mathbf{M} \in \mathbb{R}^{d \times d}$ and a vector $\mathbf{q} \in \mathbb{R}^{d}$, a **scalar** $\lambda$ and **non-zero vector** $\mathbf{q}$ are called an eigenvalue-eigenvector pair if they satisfy:

$$\mathbf{M}\mathbf{q} = \lambda\mathbf{q}$$

**Terminology:**
- $\lambda$ is the **eigenvalue** (characteristic value)
- $\mathbf{q}$ is the **eigenvector** (characteristic vector)

**Key Property:** The eigenvector satisfies the characteristic equation:
$$\det(\mathbf{M} - \lambda\mathbf{I}) = 0$$

This polynomial equation is of degree $d$, so a $d \times d$ matrix has exactly $d$ eigenvalues (counting multiplicities).

### Definition 1.2: Basis and Linear Independence

A set of $d$ vectors $\{\mathbf{q}_1, \mathbf{q}_2, \ldots, \mathbf{q}_d\} \in \mathbb{R}^d$ is called a **basis** if:
1. The vectors are **linearly independent**
2. Every vector $\mathbf{z} \in \mathbb{R}^d$ can be expressed as a linear combination of these basis vectors

**Definition of Linear Independence:**
A set of vectors is **linearly independent** if the only solution to:
$$c_1\mathbf{q}_1 + c_2\mathbf{q}_2 + \cdots + c_d\mathbf{q}_d = \mathbf{0}$$
is $c_1 = c_2 = \cdots = c_d = 0$ (all coefficients are zero).

**Equivalently:** Rank of the matrix $[\mathbf{q}_1 | \mathbf{q}_2 | \cdots | \mathbf{q}_d]$ equals $d$.

### Definition 1.3: Orthonormal Basis

A basis $\{\mathbf{q}_1, \mathbf{q}_2, \ldots, \mathbf{q}_d\}$ is **orthonormal** if:

$$\mathbf{q}_i^T\mathbf{q}_i = 1 \quad \text{(unit norm)}$$
$$\mathbf{q}_i^T\mathbf{q}_j = 0 \quad \forall i \neq j \text{ (orthogonal)}$$

**Matrix form:** If $\mathbf{Q} = [\mathbf{q}_1 | \mathbf{q}_2 | \cdots | \mathbf{q}_d]$, then:
$$\mathbf{Q}^T\mathbf{Q} = \mathbf{I}$$

Such matrices are called **orthogonal matrices**.

### Definition 1.4: Positive Definite and Semidefinite Matrices

A symmetric matrix $\mathbf{M} \in \mathbb{R}^{d \times d}$ is:

**Positive Definite (PD)** if:
$$\mathbf{x}^T\mathbf{M}\mathbf{x} > 0 \quad \text{for all non-zero vectors } \mathbf{x} \in \mathbb{R}^d$$

**Positive Semidefinite (PSD)** if:
$$\mathbf{x}^T\mathbf{M}\mathbf{x} \geq 0 \quad \text{for all vectors } \mathbf{x} \in \mathbb{R}^d$$

## II. Core Theorems

### Theorem 2.1: Linear Independence of Eigenvectors

**Statement:** The eigenvectors of a square symmetric matrix $\mathbf{M} \in \mathbb{R}^{d \times d}$ corresponding to **distinct eigenvalues are linearly independent**.

**Proof Sketch:**
Let $\lambda_1, \lambda_2, \ldots, \lambda_k$ be distinct eigenvalues with corresponding eigenvectors $\mathbf{q}_1, \mathbf{q}_2, \ldots, \mathbf{q}_k$.

Suppose $c_1\mathbf{q}_1 + c_2\mathbf{q}_2 + \cdots + c_k\mathbf{q}_k = \mathbf{0}$.

Multiply both sides by $(\mathbf{M} - \lambda_2\mathbf{I})$:
$$c_1(\lambda_1 - \lambda_2)\mathbf{q}_1 + 0 + c_3(\lambda_3 - \lambda_2)\mathbf{q}_3 + \cdots = \mathbf{0}$$

Repeating this process $k-1$ times eliminates all but one term, showing each coefficient must be zero.

**Consequence:** Eigenvectors with distinct eigenvalues can form a basis for $\mathbb{R}^d$.

### Theorem 2.2: Orthonormality of Eigenvectors (Symmetric Matrices)

**Statement:** The eigenvectors of a **symmetric** matrix are **orthogonal** with respect to each other, and can be chosen to be **orthonormal**.

**Proof:**
Let $\mathbf{M}$ be symmetric and $\lambda_i, \lambda_j$ be distinct eigenvalues with eigenvectors $\mathbf{q}_i, \mathbf{q}_j$.

By definition:
$$\mathbf{M}\mathbf{q}_i = \lambda_i\mathbf{q}_i$$
$$\mathbf{M}\mathbf{q}_j = \lambda_j\mathbf{q}_j$$

Take the dot product of the first equation with $\mathbf{q}_j$:
$$(\mathbf{M}\mathbf{q}_i)^T\mathbf{q}_j = \lambda_i(\mathbf{q}_i^T\mathbf{q}_j)$$

Since $\mathbf{M}$ is symmetric: $(\mathbf{M}\mathbf{q}_i)^T = \mathbf{q}_i^T\mathbf{M}^T = \mathbf{q}_i^T\mathbf{M}$

$$\mathbf{q}_i^T(\mathbf{M}\mathbf{q}_j) = \lambda_j(\mathbf{q}_i^T\mathbf{q}_j)$$

Comparing the two expressions:
$$\lambda_i(\mathbf{q}_i^T\mathbf{q}_j) = \lambda_j(\mathbf{q}_i^T\mathbf{q}_j)$$
$$(\lambda_i - \lambda_j)(\mathbf{q}_i^T\mathbf{q}_j) = 0$$

Since $\lambda_i \neq \lambda_j$, we have $\mathbf{q}_i^T\mathbf{q}_j = 0$ ✓

**Consequence:** For symmetric matrices, eigenvectors can be normalized to form an **orthonormal basis** (achieved by dividing each eigenvector by its norm).

### Theorem 2.3: Trace Property

**Statement:** For any square matrix $\mathbf{M}$:
$$\text{Trace}(\mathbf{M}) = \sum_{i=1}^{d} \lambda_i$$

where $\lambda_1, \lambda_2, \ldots, \lambda_d$ are the eigenvalues of $\mathbf{M}$.

**Proof Sketch:**
The characteristic polynomial is:
$$p(\lambda) = \det(\mathbf{M} - \lambda\mathbf{I}) = (-1)^d[\lambda^d - \text{Trace}(\mathbf{M})\lambda^{d-1} + \cdots + (-1)^d\det(\mathbf{M})]$$

Also, the characteristic polynomial factors as:
$$p(\lambda) = (\lambda - \lambda_1)(\lambda - \lambda_2)\cdots(\lambda - \lambda_d)$$

Comparing coefficients of $\lambda^{d-1}$ gives: $\sum_{i=1}^{d} \lambda_i = \text{Trace}(\mathbf{M})$ ✓

### Theorem 2.4: Determinant Property

**Statement:** For any square matrix $\mathbf{M}$:
$$\det(\mathbf{M}) = \prod_{i=1}^{d} \lambda_i$$

where $\lambda_1, \lambda_2, \ldots, \lambda_d$ are the eigenvalues of $\mathbf{M}$.

**Proof Sketch:**
The characteristic polynomial is:
$$p(\lambda) = \det(\mathbf{M} - \lambda\mathbf{I})$$

Evaluate at $\lambda = 0$:
$$p(0) = \det(\mathbf{M}) = (0 - \lambda_1)(0 - \lambda_2)\cdots(0 - \lambda_d) = (-1)^d\prod_{i=1}^{d}\lambda_i$$

For $d$ even: $\det(\mathbf{M}) = \prod_{i=1}^{d}\lambda_i$ ✓

### Theorem 2.5: Eigenvalues Characterize Positive Definiteness

**Statement:** A symmetric matrix $\mathbf{M}$ is:
- **Positive Definite** if and only if **all eigenvalues are positive** ($\lambda_i > 0$)
- **Positive Semidefinite** if and only if **all eigenvalues are non-negative** ($\lambda_i \geq 0$)

**Proof:**
Since $\mathbf{M}$ is symmetric, it can be decomposed as:
$$\mathbf{M} = \mathbf{Q}\boldsymbol{\Lambda}\mathbf{Q}^T$$

where $\mathbf{Q}$ contains orthonormal eigenvectors and $\boldsymbol{\Lambda}$ is diagonal with eigenvalues.

For any non-zero vector $\mathbf{x}$:
$$\mathbf{x}^T\mathbf{M}\mathbf{x} = \mathbf{x}^T\mathbf{Q}\boldsymbol{\Lambda}\mathbf{Q}^T\mathbf{x} = \mathbf{y}^T\boldsymbol{\Lambda}\mathbf{y}$$

where $\mathbf{y} = \mathbf{Q}^T\mathbf{x}$ (change of basis).

$$= \sum_{i=1}^{d} \lambda_i y_i^2$$

Since $y_i^2 \geq 0$ for all $i$:
- If all $\lambda_i > 0$ and $\mathbf{x} \neq \mathbf{0}$, then $\mathbf{x}^T\mathbf{M}\mathbf{x} > 0$ (PD) ✓
- If all $\lambda_i \geq 0$, then $\mathbf{x}^T\mathbf{M}\mathbf{x} \geq 0$ (PSD) ✓

## III. Major Decomposition

### Theorem 3.1: Eigenvalue Decomposition (Spectral Theorem)

**Statement:** For a symmetric matrix $\mathbf{M} \in \mathbb{R}^{d \times d}$:
$$\mathbf{M} = \mathbf{Q}\boldsymbol{\Lambda}\mathbf{Q}^T$$

where:
- $\mathbf{Q} \in \mathbb{R}^{d \times d}$ is an orthogonal matrix (columns are orthonormal eigenvectors)
- $\boldsymbol{\Lambda}$ is a diagonal matrix with eigenvalues on the diagonal

**Reconstruction:** Since $\mathbf{Q}^T\mathbf{Q} = \mathbf{I}$:
$$\mathbf{M} = \mathbf{Q}\boldsymbol{\Lambda}\mathbf{Q}^T \quad \Rightarrow \quad \mathbf{Q}^T\mathbf{M}\mathbf{Q} = \boldsymbol{\Lambda}$$

**Proof:**
By Theorem 2.1, eigenvectors with distinct eigenvalues are linearly independent and form a basis.
By Theorem 2.2, we can choose them to be orthonormal.

So $\mathbf{M}\mathbf{q}_i = \lambda_i\mathbf{q}_i$ for each eigenvector $\mathbf{q}_i$.

In matrix form:
$$\mathbf{M}[\mathbf{q}_1 | \mathbf{q}_2 | \cdots | \mathbf{q}_d] = [\lambda_1\mathbf{q}_1 | \lambda_2\mathbf{q}_2 | \cdots | \lambda_d\mathbf{q}_d]$$
$$\mathbf{M}\mathbf{Q} = \mathbf{Q}\boldsymbol{\Lambda}$$
$$\mathbf{M} = \mathbf{Q}\boldsymbol{\Lambda}\mathbf{Q}^T \quad \text{(since } \mathbf{Q}^T\mathbf{Q} = \mathbf{I}\text{)} \quad ✓$$

## IV. Practical Implications

### Corollary 4.1: Advantages of Orthonormal Basis (Eigenvector Basis)

For an orthonormal basis $\{\mathbf{q}_1, \mathbf{q}_2, \ldots, \mathbf{q}_d\}$, any vector $\mathbf{z} \in \mathbb{R}^d$ can be expressed as:
$$\mathbf{z} = c_1\mathbf{q}_1 + c_2\mathbf{q}_2 + \cdots + c_d\mathbf{q}_d$$

**Simple computation of coefficients:**
$$c_i = \mathbf{q}_i^T\mathbf{z}$$

**Why this works:** Multiply the decomposition by $\mathbf{q}_i^T$:
$$\mathbf{q}_i^T\mathbf{z} = c_1(\mathbf{q}_i^T\mathbf{q}_1) + c_2(\mathbf{q}_i^T\mathbf{q}_2) + \cdots + c_i(\mathbf{q}_i^T\mathbf{q}_i) + \cdots$$

Due to orthonormality, only the $i$-th term survives:
$$\mathbf{q}_i^T\mathbf{z} = c_i \cdot 1 = c_i$$

**Advantage over general basis:** No need to solve a linear system; just compute dot products!

In [2]:
# Computational Verification: All Theorems
print("="*70)
print("VERIFICATION: All Theorems with Computational Examples")
print("="*70)

# Example symmetric matrix
M = torch.tensor([[6.0, -1.0],
                   [-1.0, 5.0]], dtype=torch.float32)

print(f"\nExample Matrix M:")
print(M)

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = torch.linalg.eigh(M)

print(f"\nEigenvalues: {eigenvalues.numpy()}")
print(f"\nEigenvectors:\n{eigenvectors.numpy()}")

VERIFICATION: All Theorems with Computational Examples

Example Matrix M:
tensor([[ 6., -1.],
        [-1.,  5.]])

Eigenvalues: [4.381966 6.618034]

Eigenvectors:
[[-0.52573115 -0.85065085]
 [-0.85065085  0.52573115]]


In [3]:
# Theorem 2.1: Linear Independence of Eigenvectors
print("\n" + "="*70)
print("THEOREM 2.1: Linear Independence of Eigenvectors")
print("="*70)

# Check rank
Q = eigenvectors
rank = torch.linalg.matrix_rank(Q)
print(f"\nMatrix Q (eigenvectors as columns):")
print(Q)
print(f"\nRank of Q: {rank}")
print(f"Number of eigenvectors: {Q.shape[1]}")
print(f"\n✓ Eigenvectors are linearly independent: {rank == Q.shape[1]}")


THEOREM 2.1: Linear Independence of Eigenvectors

Matrix Q (eigenvectors as columns):
tensor([[-0.5257, -0.8507],
        [-0.8507,  0.5257]])

Rank of Q: 2
Number of eigenvectors: 2

✓ Eigenvectors are linearly independent: True


In [4]:
# Theorem 2.2: Orthonormality of Eigenvectors
print("\n" + "="*70)
print("THEOREM 2.2: Orthonormality of Eigenvectors (Symmetric Matrix)")
print("="*70)

# Check Q^T @ Q = I (orthonormality)
QtQ = Q.T @ Q
print(f"\nQ^T @ Q (should be identity):")
print(QtQ)
print(f"\nIs identity? {torch.allclose(QtQ, torch.eye(2))}")

# Check norms
print(f"\nNorms of eigenvectors (should be 1):")
for i in range(len(eigenvalues)):
    norm = torch.linalg.norm(Q[:, i])
    print(f"||q_{i+1}|| = {norm:.6f}")

# Check orthogonality
print(f"\nOrthogonality check (dot products between different eigenvectors):")
for i in range(len(eigenvalues)):
    for j in range(i+1, len(eigenvalues)):
        dot_prod = torch.dot(Q[:, i], Q[:, j])
        print(f"q_{i+1}^T @ q_{j+1} = {dot_prod:.6f} (should be 0)")

print(f"\n✓ Eigenvectors are orthonormal")


THEOREM 2.2: Orthonormality of Eigenvectors (Symmetric Matrix)

Q^T @ Q (should be identity):
tensor([[1.0000, 0.0000],
        [0.0000, 1.0000]])

Is identity? True

Norms of eigenvectors (should be 1):
||q_1|| = 1.000000
||q_2|| = 1.000000

Orthogonality check (dot products between different eigenvectors):
q_1^T @ q_2 = 0.000000 (should be 0)

✓ Eigenvectors are orthonormal


In [5]:
# Theorem 2.3: Trace Property
print("\n" + "="*70)
print("THEOREM 2.3: Trace Property")
print("="*70)

trace_M = torch.trace(M)
sum_eigenvalues = torch.sum(eigenvalues)

print(f"\nTrace(M) = {trace_M:.6f}")
print(f"Sum of eigenvalues = {sum_eigenvalues:.6f}")
print(f"\nDifference: {abs(trace_M - sum_eigenvalues):.10f}")
print(f"\n✓ Theorem verified: Trace(M) = Σλᵢ")


THEOREM 2.3: Trace Property

Trace(M) = 11.000000
Sum of eigenvalues = 11.000000

Difference: 0.0000000000

✓ Theorem verified: Trace(M) = Σλᵢ


In [6]:
# Theorem 2.4: Determinant Property
print("\n" + "="*70)
print("THEOREM 2.4: Determinant Property")
print("="*70)

det_M = torch.det(M)
prod_eigenvalues = torch.prod(eigenvalues)

print(f"\ndet(M) = {det_M:.6f}")
print(f"Product of eigenvalues = {prod_eigenvalues:.6f}")
print(f"\nDifference: {abs(det_M - prod_eigenvalues):.10f}")
print(f"\n✓ Theorem verified: det(M) = ∏λᵢ")


THEOREM 2.4: Determinant Property

det(M) = 29.000000
Product of eigenvalues = 29.000000

Difference: 0.0000000000

✓ Theorem verified: det(M) = ∏λᵢ


In [7]:
# Theorem 2.5: Positive Definiteness from Eigenvalues
print("\n" + "="*70)
print("THEOREM 2.5: Eigenvalues Characterize Positive Definiteness")
print("="*70)

print(f"\nEigenvalues of M: {eigenvalues.numpy()}")
all_positive = torch.all(eigenvalues > 0)
print(f"All eigenvalues positive? {all_positive}")

if all_positive:
    print("\n→ Matrix M is POSITIVE DEFINITE")
    # Verify by checking quadratic form
    print("\nQuadratic form verification (x^T M x for random vectors):")
    for i in range(3):
        x = torch.randn(2)
        quad_form = x @ M @ x
        print(f"Vector {i+1}: x^T M x = {quad_form:.6f} (positive ✓)")
else:
    print("\n→ Matrix M is NOT positive definite")

print(f"\n✓ Theorem verified: Eigenvalue signs determine positive definiteness")


THEOREM 2.5: Eigenvalues Characterize Positive Definiteness

Eigenvalues of M: [4.381966 6.618034]
All eigenvalues positive? True

→ Matrix M is POSITIVE DEFINITE

Quadratic form verification (x^T M x for random vectors):
Vector 1: x^T M x = 29.613966 (positive ✓)
Vector 2: x^T M x = 1.493122 (positive ✓)
Vector 3: x^T M x = 7.098722 (positive ✓)

✓ Theorem verified: Eigenvalue signs determine positive definiteness


In [8]:
# Theorem 3.1: Eigenvalue Decomposition
print("\n" + "="*70)
print("THEOREM 3.1: Eigenvalue Decomposition (M = Q Λ Q^T)")
print("="*70)

print(f"\nOriginal Matrix M:")
print(M)

print(f"\nEigenvector Matrix Q:")
print(Q)

Lambda = torch.diag(eigenvalues)
print(f"\nEigenvalue Matrix Λ:")
print(Lambda)

M_reconstructed = Q @ Lambda @ Q.T
print(f"\nReconstructed M = Q Λ Q^T:")
print(M_reconstructed)

print(f"\nReconstruction error: {torch.norm(M - M_reconstructed):.10f}")
print(f"\n✓ Theorem verified: M = Q Λ Q^T (perfect reconstruction)")


THEOREM 3.1: Eigenvalue Decomposition (M = Q Λ Q^T)

Original Matrix M:
tensor([[ 6., -1.],
        [-1.,  5.]])

Eigenvector Matrix Q:
tensor([[-0.5257, -0.8507],
        [-0.8507,  0.5257]])

Eigenvalue Matrix Λ:
tensor([[4.3820, 0.0000],
        [0.0000, 6.6180]])

Reconstructed M = Q Λ Q^T:
tensor([[ 6.0000, -1.0000],
        [-1.0000,  5.0000]])

Reconstruction error: 0.0000010795

✓ Theorem verified: M = Q Λ Q^T (perfect reconstruction)


In [9]:
# Corollary 4.1: Orthonormal Basis Computation
print("\n" + "="*70)
print("COROLLARY 4.1: Simple Coefficient Computation in Orthonormal Basis")
print("="*70)

# Random vector
z = torch.tensor([4.0, 3.0])
print(f"\nVector z: {z.numpy()}")
print(f"\nOrthonormal basis (eigenvectors):")
for i in range(len(eigenvalues)):
    print(f"q_{i+1}: {Q[:, i].numpy()}")

# Method 1: Simple dot products (orthonormal basis)
print(f"\nMethod 1: Coefficients in orthonormal basis (just dot products):")
coeffs_orthonormal = torch.tensor([torch.dot(Q[:, i], z) for i in range(len(eigenvalues))])
for i, c in enumerate(coeffs_orthonormal):
    print(f"c_{i+1} = q_{i+1}^T · z = {c:.6f}")

# Verify reconstruction
z_recon = sum(coeffs_orthonormal[i] * Q[:, i] for i in range(len(eigenvalues)))
print(f"\nReconstruction: Σ cᵢ qᵢ = {z_recon.numpy()}")
print(f"Original z: {z.numpy()}")
print(f"Match? {torch.allclose(z_recon, z)}")

print(f"\n✓ Corollary verified: Orthonormal basis allows simple dot product computation")


COROLLARY 4.1: Simple Coefficient Computation in Orthonormal Basis

Vector z: [4. 3.]

Orthonormal basis (eigenvectors):
q_1: [-0.52573115 -0.85065085]
q_2: [-0.85065085  0.52573115]

Method 1: Coefficients in orthonormal basis (just dot products):
c_1 = q_1^T · z = -4.654877
c_2 = q_2^T · z = -1.825410

Reconstruction: Σ cᵢ qᵢ = [4.0000005 3.0000005]
Original z: [4. 3.]
Match? True

✓ Corollary verified: Orthonormal basis allows simple dot product computation


## V. Complete Theorem Summary Table

| # | Theorem/Definition | Formula | Key Insight |
|---|---|---|---|
| 1.1 | Eigenvalue & Eigenvector | $\mathbf{M}\mathbf{q} = \lambda\mathbf{q}$ | Special vectors don't change direction |
| 1.2 | Basis & Linear Independence | $\text{rank} = d$ | Complete spanning set, unique decomposition |
| 1.3 | Orthonormal Basis | $\mathbf{Q}^T\mathbf{Q} = \mathbf{I}$ | Simplest basis for computation |
| 1.4 | Positive Definiteness | $\mathbf{x}^T\mathbf{M}\mathbf{x} > 0$ | Important for optimization |
| 2.1 | Linear Independence of Eigenvectors | Distinct eigenvalues | Eigenvectors form a basis |
| 2.2 | Orthonormality (Symmetric) | $\mathbf{q}_i^T\mathbf{q}_j = \delta_{ij}$ | Symmetric matrices have orthogonal eigenvectors |
| 2.3 | Trace Property | $\text{Tr}(\mathbf{M}) = \sum\lambda_i$ | Sum of diagonal = sum of eigenvalues |
| 2.4 | Determinant Property | $\det(\mathbf{M}) = \prod\lambda_i$ | Invertibility from eigenvalues |
| 2.5 | Eigenvalues & Positivity | $\lambda_i > 0 \Leftrightarrow \text{PD}$ | Check eigenvalues for definiteness |
| 3.1 | Spectral Decomposition | $\mathbf{M} = \mathbf{Q}\boldsymbol{\Lambda}\mathbf{Q}^T$ | Matrix reconstruction from eigencomponents |
| 4.1 | Orthonormal Basis Advantage | $c_i = \mathbf{q}_i^T\mathbf{z}$ | Fast coefficient computation |

## VI. Applications

These theorems form the foundation for:

1. **Principal Component Analysis (PCA)**: Uses eigenvalue decomposition of covariance matrix
2. **Matrix Inversion & Linear Systems**: Using spectral decomposition
3. **Optimization**: Checking positive definiteness via eigenvalues
4. **Dimensionality Reduction**: Selecting eigenvectors with largest eigenvalues
5. **Stability Analysis**: Eigenvalues determine system behavior
6. **Graph Theory**: Spectral methods based on graph Laplacian eigenvalues
7. **Machine Learning**: Kernel methods, spectral clustering, etc.