# Rank of a Matrix

The rank of a matrix is a fundamental concept in linear algebra that describes the dimension of the vector space spanned by its rows or columns. Understanding rank is crucial for solving linear systems, data analysis, and machine learning.

## Definition

The **rank** of a matrix $\mathbf{A}$ is the dimension of the vector space spanned by its rows (or columns). It is denoted as $\text{rank}(\mathbf{A})$ or $r(\mathbf{A})$.

### Key Properties:
- For a matrix of size $m \times n$: $\text{rank}(\mathbf{A}) \leq \min(m, n)$
- **Full rank**: $\text{rank}(\mathbf{A}) = \min(m, n)$
- **Rank deficient**: $\text{rank}(\mathbf{A}) < \min(m, n)$
- A square matrix is **invertible** if and only if it has **full rank** (i.e., $\text{rank}(\mathbf{A}) = n$)
- Rank is **invariant** under row and column operations
- $\text{rank}(\mathbf{A}) = \text{rank}(\mathbf{A}^T)$

## Computing Rank

### Method 1: Row Reduction (Gaussian Elimination)
The rank is the number of non-zero rows in the row echelon form of the matrix.

### Method 2: Using Singular Value Decomposition (SVD)
The rank is the number of non-zero singular values in the SVD decomposition.

### Method 3: Using Linear Independence
The rank is the maximum number of linearly independent row (or column) vectors.

In [15]:
import torch
import numpy as np

## Computing Rank Using PyTorch

In [16]:
# Full Rank Matrix (2×2)
A_full = torch.tensor([[1, 2],
                         [3, 4]], dtype=torch.float32)

print("Full Rank Matrix A:")
print(A_full)

rank_A_full = torch.linalg.matrix_rank(A_full)
print(f"\nRank: {rank_A_full}")
print(f"Expected max rank for 2×2: 2")
print(f"Is full rank: {rank_A_full == 2}")

Full Rank Matrix A:
tensor([[1., 2.],
        [3., 4.]])

Rank: 2
Expected max rank for 2×2: 2
Is full rank: True


In [17]:
# Rank Deficient Matrix (2×2)
# Second row is 2 times the first row
A_rank_1 = torch.tensor([[1, 2],
                           [2, 4]], dtype=torch.float32)

print("Rank Deficient Matrix B:")
print(A_rank_1)

rank_A_rank_1 = torch.linalg.matrix_rank(A_rank_1)
print(f"\nRank: {rank_A_rank_1}")
print(f"Expected max rank for 2×2: 2")
print(f"Note: Row 2 = 2 × Row 1 (linearly dependent)")

Rank Deficient Matrix B:
tensor([[1., 2.],
        [2., 4.]])

Rank: 1
Expected max rank for 2×2: 2
Note: Row 2 = 2 × Row 1 (linearly dependent)


In [18]:
# 3×3 Full Rank Matrix
A_3x3_full = torch.tensor([[1, 0, 0],
                             [0, 1, 0],
                             [0, 0, 1]], dtype=torch.float32)

print("3×3 Full Rank Matrix (Identity):")
print(A_3x3_full)

rank_identity = torch.linalg.matrix_rank(A_3x3_full)
print(f"\nRank: {rank_identity}")

3×3 Full Rank Matrix (Identity):
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

Rank: 3


In [19]:
# 3×3 Rank Deficient Matrix
A_3x3_def = torch.tensor([[1, 2, 3],
                            [2, 4, 6],
                            [3, 6, 9]], dtype=torch.float32)

print("3×3 Rank Deficient Matrix:")
print(A_3x3_def)

rank_3x3_def = torch.linalg.matrix_rank(A_3x3_def)
print(f"\nRank: {rank_3x3_def}")
print(f"Note: All rows are multiples of [1, 2, 3]")

3×3 Rank Deficient Matrix:
tensor([[1., 2., 3.],
        [2., 4., 6.],
        [3., 6., 9.]])

Rank: 1
Note: All rows are multiples of [1, 2, 3]


## Rank of Rectangular Matrices

In [20]:
# Tall Matrix (3×2)
A_tall = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

print("Tall Matrix (3×2):")
print(A_tall)

rank_tall = torch.linalg.matrix_rank(A_tall)
print(f"\nRank: {rank_tall}")
print(f"Max possible rank: {min(3, 2)}")
print(f"Is full rank: {rank_tall == min(3, 2)}")

Tall Matrix (3×2):
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

Rank: 2
Max possible rank: 2
Is full rank: True


In [21]:
# Wide Matrix (2×4)
A_wide = torch.tensor([[1, 2, 3, 4],
                         [5, 6, 7, 8]], dtype=torch.float32)

print("Wide Matrix (2×4):")
print(A_wide)

rank_wide = torch.linalg.matrix_rank(A_wide)
print(f"\nRank: {rank_wide}")
print(f"Max possible rank: {min(2, 4)}")
print(f"Is full rank: {rank_wide == min(2, 4)}")

Wide Matrix (2×4):
tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

Rank: 2
Max possible rank: 2
Is full rank: True


## Rank and Invertibility

In [22]:
# Square Full Rank Matrix (Invertible)
A_inv = torch.tensor([[2, 3],
                       [1, 4]], dtype=torch.float32)

print("Square Full Rank Matrix:")
print(A_inv)

rank_inv = torch.linalg.matrix_rank(A_inv)
n = A_inv.shape[0]

print(f"\nRank: {rank_inv}")
print(f"Matrix size: {n}×{n}")
print(f"Is invertible (rank == n): {rank_inv == n}")

# Compute inverse
A_inv_computed = torch.linalg.inv(A_inv)
print(f"\nInverse exists: {A_inv_computed is not None}")

Square Full Rank Matrix:
tensor([[2., 3.],
        [1., 4.]])

Rank: 2
Matrix size: 2×2
Is invertible (rank == n): True

Inverse exists: True


In [23]:
# Square Rank Deficient Matrix (Not Invertible)
A_singular = torch.tensor([[1, 2],
                            [2, 4]], dtype=torch.float32)

print("Square Rank Deficient Matrix:")
print(A_singular)

rank_singular = torch.linalg.matrix_rank(A_singular)
n = A_singular.shape[0]

print(f"\nRank: {rank_singular}")
print(f"Matrix size: {n}×{n}")
print(f"Is invertible (rank == n): {rank_singular == n}")

# Determinant is zero for singular matrix
det = torch.det(A_singular)
print(f"\nDeterminant: {det}")
print(f"Determinant is zero: {abs(det) < 1e-6}")

Square Rank Deficient Matrix:
tensor([[1., 2.],
        [2., 4.]])

Rank: 1
Matrix size: 2×2
Is invertible (rank == n): False

Determinant: -0.0
Determinant is zero: True


## Rank Using Singular Value Decomposition (SVD)

In [24]:
# SVD for rank computation
A = torch.tensor([[1, 2, 3],
                   [4, 5, 6]], dtype=torch.float32)

print("Matrix A:")
print(A)

# Compute SVD
U, S, Vh = torch.svd(A)

print(f"\nSingular values:")
print(S)

# Count non-zero singular values (with tolerance)
tolerance = 1e-6
rank_from_svd = torch.sum(S > tolerance)

print(f"\nRank (from SVD): {rank_from_svd}")
print(f"Rank (using torch.linalg.matrix_rank): {torch.linalg.matrix_rank(A)}")

Matrix A:
tensor([[1., 2., 3.],
        [4., 5., 6.]])

Singular values:
tensor([9.5080, 0.7729])

Rank (from SVD): 2
Rank (using torch.linalg.matrix_rank): 2


## Rank-Nullity Theorem

In [25]:
# Rank-Nullity Theorem: rank(A) + nullity(A) = n (number of columns)

A = torch.tensor([[1, 2, 3, 4],
                   [2, 4, 6, 8],
                   [3, 6, 9, 12]], dtype=torch.float32)

print("Matrix A (3×4):")
print(A)

rank = torch.linalg.matrix_rank(A)
n_cols = A.shape[1]
nullity = n_cols - rank

print(f"\nNumber of columns (n): {n_cols}")
print(f"Rank: {rank}")
print(f"Nullity: {nullity}")
print(f"\nRank + Nullity = {rank} + {nullity} = {rank + nullity}")
print(f"Equals n: {rank + nullity == n_cols}")

Matrix A (3×4):
tensor([[ 1.,  2.,  3.,  4.],
        [ 2.,  4.,  6.,  8.],
        [ 3.,  6.,  9., 12.]])

Number of columns (n): 4
Rank: 1
Nullity: 3

Rank + Nullity = 1 + 3 = 4
Equals n: True


## Properties of Rank

In [26]:
# Property 1: rank(A) = rank(A^T)
A = torch.tensor([[1, 2, 3],
                   [4, 5, 6]], dtype=torch.float32)

rank_A = torch.linalg.matrix_rank(A)
rank_A_T = torch.linalg.matrix_rank(A.T)

print("Property 1: rank(A) = rank(A^T)")
print(f"rank(A): {rank_A}")
print(f"rank(A^T): {rank_A_T}")
print(f"Equal: {rank_A == rank_A_T}")

Property 1: rank(A) = rank(A^T)
rank(A): 2
rank(A^T): 2
Equal: True


In [27]:
# Property 2: rank(AB) <= min(rank(A), rank(B))
A = torch.tensor([[1, 2],
                   [3, 4]], dtype=torch.float32)
B = torch.tensor([[5, 6],
                   [7, 8]], dtype=torch.float32)

rank_A = torch.linalg.matrix_rank(A)
rank_B = torch.linalg.matrix_rank(B)
AB = A @ B
rank_AB = torch.linalg.matrix_rank(AB)

print("Property 2: rank(AB) <= min(rank(A), rank(B))")
print(f"rank(A): {rank_A}")
print(f"rank(B): {rank_B}")
print(f"rank(AB): {rank_AB}")
print(f"min(rank(A), rank(B)): {min(rank_A, rank_B)}")
print(f"Property holds: {rank_AB <= min(rank_A, rank_B)}")

Property 2: rank(AB) <= min(rank(A), rank(B))
rank(A): 2
rank(B): 2
rank(AB): 2
min(rank(A), rank(B)): 2
Property holds: True


In [28]:
# Property 3: rank(A + B) <= rank(A) + rank(B)
A = torch.tensor([[1, 0],
                   [0, 1]], dtype=torch.float32)
B = torch.tensor([[0, 1],
                   [1, 0]], dtype=torch.float32)

rank_A = torch.linalg.matrix_rank(A)
rank_B = torch.linalg.matrix_rank(B)
A_plus_B = A + B
rank_A_plus_B = torch.linalg.matrix_rank(A_plus_B)

print("Property 3: rank(A + B) <= rank(A) + rank(B)")
print(f"rank(A): {rank_A}")
print(f"rank(B): {rank_B}")
print(f"rank(A + B): {rank_A_plus_B}")
print(f"rank(A) + rank(B): {rank_A + rank_B}")
print(f"Property holds: {rank_A_plus_B <= rank_A + rank_B}")

Property 3: rank(A + B) <= rank(A) + rank(B)
rank(A): 2
rank(B): 2
rank(A + B): 1
rank(A) + rank(B): 4
Property holds: True
