# Determinant of a Matrix

The determinant is a scalar value that can be computed from the elements of a square matrix and has important applications in linear algebra, calculus, and machine learning.

## Definition

The **determinant** of a square matrix $\mathbf{A}$ of size $n \times n$ is a scalar value denoted as $\det(\mathbf{A})$ or $|\mathbf{A}|$.

### Key Properties:
- The determinant is only defined for **square matrices**
- It is a **scalar value** (single number)
- A matrix is **invertible** if and only if its determinant is **non-zero**
- The determinant is **invariant** under certain matrix operations
- The absolute value of the determinant represents the **volume scaling factor** of the linear transformation

## Computing Determinant for Small Matrices

### 2×2 Matrix:
For a matrix $\mathbf{A} = \begin{bmatrix} a & b \\ c & d \end{bmatrix}$:

$$\det(\mathbf{A}) = ad - bc$$

### 3×3 Matrix (Rule of Sarrus):
For a matrix $\mathbf{A} = \begin{bmatrix} a & b & c \\ d & e & f \\ g & h & i \end{bmatrix}$:

$$\det(\mathbf{A}) = aei + bfg + cdh - ceg - afh - bdi$$

In [1]:
import torch
import numpy as np

## Computing Determinant Using PyTorch

In [2]:
# 2×2 Matrix Example
A_2x2 = torch.tensor([[4, 7],
                        [2, 6]], dtype=torch.float32)

print("2×2 Matrix A:")
print(A_2x2)

# Calculate determinant
det_A_2x2 = torch.det(A_2x2)
print(f"\nDeterminant: {det_A_2x2}")

# Manual calculation
manual_det = A_2x2[0, 0] * A_2x2[1, 1] - A_2x2[0, 1] * A_2x2[1, 0]
print(f"Manual calculation: {4*6 - 7*2} = {manual_det}")

2×2 Matrix A:
tensor([[4., 7.],
        [2., 6.]])

Determinant: 10.000000953674316
Manual calculation: 10 = 10.0


In [3]:
# 3×3 Matrix Example
A_3x3 = torch.tensor([[1, 2, 3],
                        [0, 1, 4],
                        [5, 6, 0]], dtype=torch.float32)

print("3×3 Matrix A:")
print(A_3x3)

det_A_3x3 = torch.det(A_3x3)
print(f"\nDeterminant: {det_A_3x3}")

3×3 Matrix A:
tensor([[1., 2., 3.],
        [0., 1., 4.],
        [5., 6., 0.]])

Determinant: 0.9999996423721313


In [4]:
# Larger Matrix Example (4×4)
A_4x4 = torch.tensor([[1, 2, 3, 4],
                        [5, 6, 7, 8],
                        [9, 10, 11, 12],
                        [13, 14, 15, 16]], dtype=torch.float32)

print("4×4 Matrix A:")
print(A_4x4)

det_A_4x4 = torch.det(A_4x4)
print(f"\nDeterminant: {det_A_4x4}")

4×4 Matrix A:
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])

Determinant: 0.0


## Properties of Determinant

### 1. Determinant of Transpose: det(A^T) = det(A)

In [5]:
A = torch.tensor([[2, 3],
                   [1, 4]], dtype=torch.float32)

det_A = torch.det(A)
det_A_T = torch.det(A.T)

print(f"det(A) = {det_A}")
print(f"det(A^T) = {det_A_T}")
print(f"Property holds: {torch.allclose(det_A, det_A_T)}")

det(A) = 5.0
det(A^T) = 5.0
Property holds: True


### 2. Determinant of Product: det(AB) = det(A)·det(B)

In [ ]:
B = torch.tensor([[4, 1],
                   [2, 3]], dtype=torch.float32)

det_A = torch.det(A)
det_B = torch.det(B)
det_AB = torch.det(torch.matmul(A, B))
product_det = det_A * det_B

print(f"det(A) = {det_A}")
print(f"det(B) = {det_B}")
print(f"det(A·B) = {det_AB}")
print(f"det(A)·det(B) = {product_det}")
print(f"Property holds: {torch.allclose(det_AB, product_det)}")

det(A) = 5.0
det(B) = 10.0
det(A·B) = 50.000003814697266
det(A)·det(B) = 50.0
Property holds: True


### 3. Determinant of Scalar Multiple: det(kA) = k^n·det(A) for n×n matrix

In [7]:
C = torch.tensor([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]], dtype=torch.float32)

k = 2
n = C.shape[0]

det_C = torch.det(C)
det_kC = torch.det(k * C)
expected = (k ** n) * det_C

print(f"det(C) = {det_C}")
print(f"det(2C) = {det_kC}")
print(f"2^3 · det(C) = {expected}")
print(f"Property holds: {torch.allclose(det_kC, expected)}")

det(C) = 0.0
det(2C) = 0.0
2^3 · det(C) = 0.0
Property holds: True


### 4. Determinant of Inverse: det(A^-1) = 1/det(A)

In [8]:
# Create an invertible matrix
D = torch.tensor([[3, 1],
                   [2, 2]], dtype=torch.float32)

det_D = torch.det(D)
D_inv = torch.linalg.inv(D)
det_D_inv = torch.det(D_inv)
expected_inv = 1 / det_D

print(f"Matrix D:\n{D}")
print(f"\ndet(D) = {det_D}")
print(f"det(D^-1) = {det_D_inv}")
print(f"1/det(D) = {expected_inv}")
print(f"Property holds: {torch.allclose(det_D_inv, expected_inv)}")

Matrix D:
tensor([[3., 1.],
        [2., 2.]])

det(D) = 3.999999761581421
det(D^-1) = 0.25
1/det(D) = 0.2500000298023224
Property holds: True


### 5. Singular Matrix: det(A) = 0 ⟹ Matrix is Singular (Non-invertible)

In [9]:
# Singular matrix (linearly dependent rows)
E = torch.tensor([[1, 2, 3],
                   [2, 4, 6],
                   [3, 6, 9]], dtype=torch.float32)

det_E = torch.det(E)
print(f"Singular Matrix E:\n{E}")
print(f"\ndet(E) = {det_E}")
print(f"Matrix is singular: {torch.allclose(det_E, torch.tensor(0.0))}")

# Try to compute inverse (will fail or give nan)
try:
    E_inv = torch.linalg.inv(E)
    print(f"Inverse:\n{E_inv}")
except:
    print("Cannot compute inverse (matrix is singular)")

Singular Matrix E:
tensor([[1., 2., 3.],
        [2., 4., 6.],
        [3., 6., 9.]])

det(E) = 0.0
Matrix is singular: True
Cannot compute inverse (matrix is singular)


## Determinant and Eigenvalues

The determinant equals the product of eigenvalues:
$$\det(\mathbf{A}) = \prod_{i=1}^{n} \lambda_i$$

In [10]:
# Symmetric matrix (real eigenvalues)
F = torch.tensor([[4, 1],
                   [1, 3]], dtype=torch.float32)

det_F = torch.det(F)

# Compute eigenvalues
eigenvalues = torch.linalg.eigvalsh(F)
product_eigenvalues = torch.prod(eigenvalues)

print(f"Matrix F:\n{F}")
print(f"\ndet(F) = {det_F}")
print(f"Eigenvalues: {eigenvalues}")
print(f"Product of eigenvalues: {product_eigenvalues}")
print(f"Property holds: {torch.allclose(det_F, product_eigenvalues)}")

Matrix F:
tensor([[4., 1.],
        [1., 3.]])

det(F) = 11.0
Eigenvalues: tensor([2.3820, 4.6180])
Product of eigenvalues: 11.0
Property holds: True


## Applications of Determinant

1. **Invertibility**: Matrix is invertible ⟺ det(A) ≠ 0
2. **Linear Independence**: Vectors are linearly independent ⟺ det(A) ≠ 0
3. **Volume Scaling**: |det(A)| represents the scaling factor of volume under transformation
4. **Cramer's Rule**: Solving systems of linear equations
5. **Change of Variables**: In integration (Jacobian determinant)
6. **Stability Analysis**: In differential equations and systems

In [11]:
# Example: Volume scaling in 2D
# Identity matrix (no scaling)
I = torch.eye(2)
det_I = torch.det(I)
print(f"Identity matrix determinant: {det_I}")
print(f"Volume scaling factor: {abs(det_I.item())}")

# Scaling matrix (scales by factor of 2 in both directions)
S = torch.tensor([[2, 0],
                   [0, 2]], dtype=torch.float32)
det_S = torch.det(S)
print(f"\nScaling matrix determinant: {det_S}")
print(f"Volume scaling factor: {abs(det_S.item())} (4x area scaling)")

# Rotation matrix (preserves volume)
theta = torch.tensor(0.5)  # radians
R = torch.tensor([[torch.cos(theta), -torch.sin(theta)],
                   [torch.sin(theta), torch.cos(theta)]])
det_R = torch.det(R)
print(f"\nRotation matrix determinant: {det_R}")
print(f"Volume scaling factor: {abs(det_R.item())} (preserves volume)")

Identity matrix determinant: 1.0
Volume scaling factor: 1.0

Scaling matrix determinant: 4.0
Volume scaling factor: 4.0 (4x area scaling)

Rotation matrix determinant: 1.0
Volume scaling factor: 1.0 (preserves volume)
