# Inverse of a Square Matrix

The inverse of a matrix is a fundamental concept in linear algebra that plays a crucial role in solving linear systems, optimization, and numerous machine learning algorithms.

## Definition

For a square matrix $\mathbf{A}$ of size $n \times n$, the **inverse** denoted as $\mathbf{A}^{-1}$ is a matrix such that:

$$\mathbf{A} \cdot \mathbf{A}^{-1} = \mathbf{A}^{-1} \cdot \mathbf{A} = \mathbf{I}$$

where $\mathbf{I}$ is the identity matrix.

### Conditions for Invertibility:
- The matrix must be **square** (n × n)
- The matrix must be **non-singular**, i.e., $\det(\mathbf{A}) \neq 0$
- The matrix must have **full rank** (all rows/columns are linearly independent)
- The matrix is **invertible** ⟺ it has **full rank** ⟺ $\det(\mathbf{A}) \neq 0$

## Mathematical Formulation

### For a 2×2 Matrix:
$$\mathbf{A} = \begin{bmatrix} a & b \\ c & d \end{bmatrix}$$

The inverse is:
$$\mathbf{A}^{-1} = \frac{1}{ad - bc} \begin{bmatrix} d & -b \\ -c & a \end{bmatrix}$$

where $ad - bc = \det(\mathbf{A}) \neq 0$

### General Case (Adjugate Matrix Method):
$$\mathbf{A}^{-1} = \frac{1}{\det(\mathbf{A})} \text{adj}(\mathbf{A})$$

where $\text{adj}(\mathbf{A})$ is the adjugate (adjoint) matrix of $\mathbf{A}$.

In [1]:
import torch
import numpy as np

## Computing Matrix Inverse Using PyTorch

In [2]:
# 2×2 Matrix Example
A = torch.tensor([[4, 7],
                   [2, 6]], dtype=torch.float32)

print("Matrix A:")
print(A)

# Method 1: Using torch.linalg.inv()
A_inv = torch.linalg.inv(A)
print("\nInverse A^-1 using torch.linalg.inv():")
print(A_inv)

Matrix A:
tensor([[4., 7.],
        [2., 6.]])

Inverse A^-1 using torch.linalg.inv():
tensor([[ 0.6000, -0.7000],
        [-0.2000,  0.4000]])


In [3]:
# Verify that A · A^-1 = I
product = torch.matmul(A, A_inv)
identity = torch.eye(2)

print("A · A^-1 =")
print(product)
print("\nIdentity Matrix I =")
print(identity)


A · A^-1 =
tensor([[1.0000, 0.0000],
        [0.0000, 1.0000]])

Identity Matrix I =
tensor([[1., 0.],
        [0., 1.]])


In [4]:
# 3×3 Matrix Example
B = torch.tensor([[1, 2, 3],
                   [0, 1, 4],
                   [5, 6, 0]], dtype=torch.float32)

print("Matrix B:")
print(B)

B_inv = torch.linalg.inv(B)
print("\nInverse B^-1:")
print(B_inv)

# Verify
product_B = B.matmul(B_inv)
print("\nB · B^-1 (should be identity):")
print(product_B)

Matrix B:
tensor([[1., 2., 3.],
        [0., 1., 4.],
        [5., 6., 0.]])

Inverse B^-1:
tensor([[-24.0000,  18.0000,   5.0000],
        [ 20.0000, -15.0000,  -4.0000],
        [ -5.0000,   4.0000,   1.0000]])

B · B^-1 (should be identity):
tensor([[ 1.0000e+00, -1.9073e-06,  0.0000e+00],
        [ 0.0000e+00,  1.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  1.0000e+00]])


## Manual Computation for 2×2 Matrix

In [5]:
# For a 2×2 matrix: A = [[a, b], [c, d]]
# A^-1 = (1/(ad-bc)) * [[d, -b], [-c, a]]

a, b = A[0, 0], A[0, 1]
c, d = A[1, 0], A[1, 1]

det = a*d - b*c
print(f"Matrix A = [[{a}, {b}], [{c}, {d}]]")
print(f"det(A) = {a}*{d} - {b}*{c} = {det}")

A_inv_manual = (1/det) * torch.tensor([[d, -b],
                                         [-c, a]], dtype=torch.float32)

print("\nA^-1 (manual calculation):")
print(A_inv_manual)
print(f"\nMatches PyTorch result: {torch.allclose(A_inv, A_inv_manual)}")

Matrix A = [[4.0, 7.0], [2.0, 6.0]]
det(A) = 4.0*6.0 - 7.0*2.0 = 10.0

A^-1 (manual calculation):
tensor([[ 0.6000, -0.7000],
        [-0.2000,  0.4000]])

Matches PyTorch result: True


## Properties of Matrix Inverse

### Property 1: (A^-1)^-1 = A

In [6]:
A_inv_inv = torch.linalg.inv(A_inv)

print("(A^-1)^-1 =")
print(A_inv_inv)
print("\nOriginal A =")
print(A)
print(f"\n(A^-1)^-1 = A: {torch.allclose(A_inv_inv, A)}")

(A^-1)^-1 =
tensor([[4.0000, 7.0000],
        [2.0000, 6.0000]])

Original A =
tensor([[4., 7.],
        [2., 6.]])

(A^-1)^-1 = A: True


### Property 2: (A·B)^-1 = B^-1 · A^-1 (order matters!)

In [7]:
C = torch.tensor([[2, 1],
                   [3, 2]], dtype=torch.float32)

C_inv = torch.linalg.inv(C)

# (A·C)^-1
AC = torch.matmul(A, C)
AC_inv = torch.linalg.inv(AC)

# C^-1 · A^-1
C_inv_A_inv = torch.matmul(C_inv, A_inv)

print("(A·C)^-1 =")
print(AC_inv)
print("\nC^-1 · A^-1 =")
print(C_inv_A_inv)


(A·C)^-1 =
tensor([[ 1.4000, -1.8000],
        [-2.2000,  2.9000]])

C^-1 · A^-1 =
tensor([[ 1.4000, -1.8000],
        [-2.2000,  2.9000]])


### Property 3: (A^T)^-1 = (A^-1)^T

In [8]:
# (A^T)^-1
A_T = A.T
A_T_inv = torch.linalg.inv(A_T)

# (A^-1)^T
A_inv_T = A_inv.T

print("(A^T)^-1 =")
print(A_T_inv)
print("\n(A^-1)^T =")
print(A_inv_T)
print(f"\n(A^T)^-1 = (A^-1)^T: {torch.allclose(A_T_inv, A_inv_T)}")

(A^T)^-1 =
tensor([[ 0.6000, -0.2000],
        [-0.7000,  0.4000]])

(A^-1)^T =
tensor([[ 0.6000, -0.2000],
        [-0.7000,  0.4000]])

(A^T)^-1 = (A^-1)^T: True


### Property 4: det(A^-1) = 1/det(A)

In [9]:
det_A = torch.det(A)
det_A_inv = torch.det(A_inv)
expected_det = 1 / det_A

print(f"det(A) = {det_A}")
print(f"det(A^-1) = {det_A_inv}")
print(f"1/det(A) = {expected_det}")
print(f"\ndet(A^-1) = 1/det(A): {torch.allclose(det_A_inv, expected_det)}")

det(A) = 10.000000953674316
det(A^-1) = 0.10000001639127731
1/det(A) = 0.09999999403953552

det(A^-1) = 1/det(A): True


## Singular and Near-Singular Matrices

In [10]:
# Singular matrix (determinant = 0)
Singular = torch.tensor([[1, 2],
                          [2, 4]], dtype=torch.float32)

det_singular = torch.det(Singular)
print(f"Singular Matrix:\n{Singular}")
print(f"Determinant: {det_singular}")
print(f"Is singular (det ≈ 0): {torch.allclose(det_singular, torch.tensor(0.0))}")

# Try to compute inverse
try:
    Singular_inv = torch.linalg.inv(Singular)
    print(f"Inverse:\n{Singular_inv}")
except Exception as e:
    print(f"Error: Cannot invert singular matrix")

Singular Matrix:
tensor([[1., 2.],
        [2., 4.]])
Determinant: -0.0
Is singular (det ≈ 0): True
Error: Cannot invert singular matrix


In [11]:
# Near-singular matrix (very small determinant, numerically problematic)
NearSingular = torch.tensor([[1, 2],
                              [2, 4.0001]], dtype=torch.float32)

det_near = torch.det(NearSingular)
print(f"Near-Singular Matrix:\n{NearSingular}")
print(f"Determinant: {det_near}")

NearSingular_inv = torch.linalg.inv(NearSingular)
print(f"\nInverse:\n{NearSingular_inv}")
print(f"\nNote: Very large values indicate numerical instability")

Near-Singular Matrix:
tensor([[1.0000, 2.0000],
        [2.0000, 4.0001]])
Determinant: 0.00010013580322265625

Inverse:
tensor([[ 39946.7539, -19972.8770],
        [-19972.8770,   9986.4385]])

Note: Very large values indicate numerical instability


## Applications of Matrix Inverse

### Application 1: Solving Linear Systems (Ax = b)

In [12]:
# Solve: A·x = b
# Solution: x = A^-1 · b

A = torch.tensor([[3, 1],
                   [2, 2]], dtype=torch.float32)
b = torch.tensor([[9],
                   [8]], dtype=torch.float32)

print("System: A·x = b")
print(f"A = \n{A}")
print(f"b = \n{b}")

# Method 1: Using inverse
x_using_inv = torch.matmul(torch.linalg.inv(A), b)
print(f"\nSolution using A^-1: x = \n{x_using_inv}")

# Method 2: Using torch.linalg.solve() (more numerically stable)
x_using_solve = torch.linalg.solve(A, b)
print(f"\nSolution using torch.linalg.solve(): x = \n{x_using_solve}")

# Verify
result = torch.matmul(A, x_using_solve)
print(f"\nVerification: A·x = \n{result}")
print(f"Matches b: {torch.allclose(result, b)}")

System: A·x = b
A = 
tensor([[3., 1.],
        [2., 2.]])
b = 
tensor([[9.],
        [8.]])

Solution using A^-1: x = 
tensor([[2.5000],
        [1.5000]])

Solution using torch.linalg.solve(): x = 
tensor([[2.5000],
        [1.5000]])

Verification: A·x = 
tensor([[9.],
        [8.]])
Matches b: True


### Application 2: Change of Basis

In [13]:
# Transformation matrix
P = torch.tensor([[1, 2],
                   [3, 4]], dtype=torch.float32)

# A vector in original basis
v_original = torch.tensor([[1],
                             [1]], dtype=torch.float32)

print("Transformation matrix P:")
print(P)
print(f"\nVector in original basis: v = \n{v_original}")

# Transform to new basis
v_new = torch.matmul(P, v_original)
print(f"\nVector in new basis: P·v = \n{v_new}")

# Transform back to original basis
P_inv = torch.linalg.inv(P)
v_back = torch.matmul(P_inv, v_new)
print(f"\nVector back to original basis: P^-1·(P·v) = \n{v_back}")
print(f"Matches original: {torch.allclose(v_back, v_original)}")

Transformation matrix P:
tensor([[1., 2.],
        [3., 4.]])

Vector in original basis: v = 
tensor([[1.],
        [1.]])

Vector in new basis: P·v = 
tensor([[3.],
        [7.]])

Vector back to original basis: P^-1·(P·v) = 
tensor([[1.0000],
        [1.0000]])
Matches original: True


### Application 3: Matrix Diagonalization

In [14]:
# For a symmetric matrix A, we can find P and D such that:
# A = P·D·P^-1 where D is diagonal

A = torch.tensor([[4, 1],
                   [1, 3]], dtype=torch.float32)

print("Matrix A:")
print(A)

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = torch.linalg.eigh(A)

print(f"\nEigenvalues: {eigenvalues}")
print(f"Eigenvectors (P):\n{eigenvectors}")

# Create diagonal matrix
D = torch.diag(eigenvalues)
P = eigenvectors
P_inv = torch.linalg.inv(P)

# Reconstruct A = P·D·P^-1
A_reconstructed = torch.matmul(torch.matmul(P, D), P_inv)

print(f"\nDiagonal matrix D:\n{D}")
print(f"\nReconstructed A = P·D·P^-1:\n{A_reconstructed}")
print(f"\nMatches original A: {torch.allclose(A, A_reconstructed)}")

Matrix A:
tensor([[4., 1.],
        [1., 3.]])

Eigenvalues: tensor([2.3820, 4.6180])
Eigenvectors (P):
tensor([[ 0.5257, -0.8507],
        [-0.8507, -0.5257]])

Diagonal matrix D:
tensor([[2.3820, 0.0000],
        [0.0000, 4.6180]])

Reconstructed A = P·D·P^-1:
tensor([[4.0000, 1.0000],
        [1.0000, 3.0000]])

Matches original A: True


## Numerical Stability and Condition Number

In [15]:
# Condition number indicates how sensitive the inverse is to perturbations
# Higher condition number = more numerically unstable

# Well-conditioned matrix
Well = torch.tensor([[1, 0],
                      [0, 1]], dtype=torch.float32)

# Ill-conditioned matrix (near-singular)
Ill = torch.tensor([[1, 1],
                     [1, 1.0001]], dtype=torch.float32)

cond_well = torch.linalg.cond(Well)
cond_ill = torch.linalg.cond(Ill)

print(f"Well-conditioned matrix condition number: {cond_well}")
print(f"Ill-conditioned matrix condition number: {cond_ill}")
print(f"\nThe ill-conditioned matrix is {(cond_ill/cond_well).item():.0f}x less stable")

Well-conditioned matrix condition number: 1.0
Ill-conditioned matrix condition number: 39949.3671875

The ill-conditioned matrix is 39949x less stable
