# Matrix Inverse

The **inverse** of a square matrix $A$, denoted $A^{-1}$, is a matrix such that:

$$A \cdot A^{-1} = A^{-1} \cdot A = I$$

where $I$ is the **identity matrix**.

**Key Intuition:**
- For scalars: the inverse of $x$ is $1/x$ (e.g., the inverse of 5 is 0.2, since $5 \times 0.2 = 1$)
- For matrices: $A^{-1}$ plays the same role — it "undoes" the transformation applied by $A$

### Real-world Applications
- **Solving linear systems:** $A\mathbf{x} = \mathbf{b}$ → $\mathbf{x} = A^{-1}\mathbf{b}$
- **Computer graphics:** Reversing transformations (e.g., undoing a camera rotation)
- **Cryptography:** Decrypting RSA and Hill cipher messages
- **Robotics:** Computing joint angles from end-effector position (inverse kinematics)
- **Signal processing:** Deconvolution and filter inversion
- **Control systems:** Designing feedback gains and compensators


## When Does a Matrix Inverse Exist?

### ✅ Conditions for Invertibility
A square matrix $A$ is **invertible** if and only if:
1. It is **square** (same number of rows and columns)
2. Its **determinant is non-zero**: $\det(A) \neq 0$
3. Its **rank equals its dimension**: $\text{rank}(A) = n$ for an $n \times n$ matrix
4. Its **rows (and columns) are linearly independent**

### ❌ Non-invertible (Singular) Matrices
A matrix is **singular** (non-invertible) if:
- $\det(A) = 0$ — the matrix is **degenerate**
- Rank < dimension — some rows/columns are redundant
- At least one row/column is a linear combination of others

**Example of non-invertible matrix:**
$$A = \begin{bmatrix} 1 & 2 \\ 2 & 4 \end{bmatrix}$$
Row 2 = 2 × Row 1, so $\det(A) = 0$ and $A^{-1}$ does not exist.

### Determinant Quick Reference
$$\det \begin{bmatrix} a & b \\ c & d \end{bmatrix} = ad - bc$$

If $ad - bc = 0$, the matrix is singular.


In [33]:
import numpy as np
from numpy.linalg import inv, det
import matplotlib.pyplot as plt

print('Libraries loaded: numpy.linalg.inv, numpy.linalg.det')


Libraries loaded: numpy.linalg.inv, numpy.linalg.det


## Example 1: Simple 2×2 Matrix Inverse

Let's invert the matrix:
$$A = \begin{bmatrix} 4 & 7 \\ 2 & 6 \end{bmatrix}$$

**Step 1: Check if invertible**
- Determinant: $\det(A) = 4 \cdot 6 - 7 \cdot 2 = 24 - 14 = 10 \neq 0$ ✓

**Step 2: Compute the inverse** using the formula:
$$A^{-1} = \frac{1}{\det(A)} \begin{bmatrix} d & -b \\ -c & a \end{bmatrix} = \frac{1}{10} \begin{bmatrix} 6 & -7 \\ -2 & 4 \end{bmatrix}$$

**Step 3: Verify**
$$A \cdot A^{-1} = I$$


In [34]:
# Define a 2x2 matrix
A = np.array([[4, 7],
              [2, 6]], dtype=float)

print("Matrix A:")
print(A)
print()

# Step 1: Compute determinant
det_A = det(A)
print(f"Determinant of A: {det_A}")
print(f"Invertible? {det_A != 0}")
print()

# Step 2: Compute inverse using numpy
A_inv = inv(A)
print("Inverse of A  (A^-1):")
print(A_inv)
print()

# Step 3: Verify: A @ A_inv should equal I
identity_check = A @ A_inv
print("A @ A^-1 (should be close to identity matrix I):")
print(identity_check)
print()

# Also verify A_inv @ A = I
identity_check2 = A_inv @ A
print("A^-1 @ A (should also be I):")
print(identity_check2)


Matrix A:
[[4. 7.]
 [2. 6.]]

Determinant of A: 10.000000000000002
Invertible? True

Inverse of A  (A^-1):
[[ 0.6 -0.7]
 [-0.2  0.4]]

A @ A^-1 (should be close to identity matrix I):
[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]

A^-1 @ A (should also be I):
[[1.00000000e+00 6.66133815e-16]
 [0.00000000e+00 1.00000000e+00]]


## Example 2: 3×3 Matrix Inverse

For larger matrices, the inverse formula is more complex, but **numpy handles it automatically**.

Let's invert:
$$B = \begin{bmatrix} 1 & 2 & 3 \\ 0 & 1 & 4 \\ 5 & 6 & 0 \end{bmatrix}$$


In [35]:
# Define a 3x3 matrix
B = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]], dtype=float)

print("Matrix B:")
print(B)
print()

# Compute determinant
det_B = det(B)
print(f"Determinant of B: {det_B:.2f}")
print(f"Invertible? {det_B != 0}")
print()

# Compute inverse
B_inv = inv(B)
print("Inverse of B  (B^-1):")
print(B_inv)
print()

# Verify: B @ B_inv = I
identity_check = B @ B_inv
print("B @ B^-1 (should be I):")
print(np.round(identity_check, 10))  # Round to see cleaner output


Matrix B:
[[1. 2. 3.]
 [0. 1. 4.]
 [5. 6. 0.]]

Determinant of B: 1.00
Invertible? True

Inverse of B  (B^-1):
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]

B @ B^-1 (should be I):
[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]


## Example 3: Solving a Linear System with Inverse

### The Mathematical Solution

**Given:** A system of linear equations in matrix form:
$$A\mathbf{x} = \mathbf{b}$$

**Find:** The unknown vector $\mathbf{x}$

### Mathematical Derivation

**Starting equation:**
$$A\mathbf{x} = \mathbf{b} \quad\text{...(1)}$$

**Multiply both sides by} $A^{-1}$ (from the left):**
$$A^{-1} \cdot A\mathbf{x} = A^{-1} \cdot \mathbf{b} \quad\text{...(2)}$$

**Apply the property that $A^{-1} \cdot A = I$ (identity matrix):**
$$I \cdot \mathbf{x} = A^{-1}\mathbf{b} \quad\text{...(3)}$$

**Since multiplying by the identity matrix leaves vectors unchanged ($I \cdot \mathbf{x} = \mathbf{x}$):**
$$\mathbf{x} = A^{-1}\mathbf{b} \quad\text{...(4) ← SOLUTION}$$

### Why This Works

**Analogy with scalar arithmetic:**
- Scalar equation: $5x = 10$ 
- Solution: $x = 5^{-1} \cdot 10 = \frac{1}{5} \cdot 10 = 2$ ✓

**Matrix equation:** $A\mathbf{x} = \mathbf{b}$
- Solution: $\mathbf{x} = A^{-1}\mathbf{b}$ (the matrix inverse plays the role of $1/A$) ✓

### Conditions for This Solution to Exist

For the solution $\mathbf{x} = A^{-1}\mathbf{b}$ to be valid, we need:
1. $A$ must be **square** ($n \times n$ matrix)
2. $A$ must be **invertible**: $\det(A) \neq 0$
3. If these conditions hold, $A^{-1}$ exists and is unique
4. The solution $\mathbf{x}$ is then **unique**

### Concrete Numerical Example

Solve: 
$$\begin{align}
3x + 2y &= 8\\
4x - y &= 5
\end{align}$$


In [36]:
# ═══════════════════════════════════════════════════════════════════════
# SOLVING A LINEAR SYSTEM USING MATRIX INVERSE
# ═══════════════════════════════════════════════════════════════════════
#
# Problem: Solve the system of equations
#   3x + 2y = 8   ... (1)
#   4x - y  = 5   ... (2)
#
# Method: Convert to matrix form A @ x = b, then solve as x = A^-1 @ b
#
# ═══════════════════════════════════════════════════════════════════════

# STEP 1: Define the coefficient matrix A
# A contains the coefficients (multipliers) of x and y from equations (1) and (2)
# Row 1: [3, 2]  represents 3x + 2y
# Row 2: [4, -1] represents 4x - y
A = np.array([[3, 2],
              [4, -1]], dtype=float)

# STEP 2: Define the constants vector b
# b contains the right-hand side values from the equations
# b[0] = 8   (from equation 1: 3x + 2y = 8)
# b[1] = 5   (from equation 2: 4x - y = 5)
b = np.array([[8],
              [5]], dtype=float)

print("=" * 60)
print("LINEAR SYSTEM OF EQUATIONS: A @ x = b")
print("=" * 60)
print()
print("Coefficient matrix A:")
print(A)
print()
print("Constants vector b:")
print(b)
print()
print("Matrix equation: A @ x = b means:")
print("  [3   2] @ [x]   [8]")
print("  [4  -1]   [y] = [5]")
print()

# STEP 3: Compute the inverse of A
# A^-1 is the "inverse" of A such that: A @ A^-1 = I (identity matrix)
# Once we have A^-1, we can multiply both sides of A @ x = b by A^-1:
#   A^-1 @ A @ x = A^-1 @ b
#   I @ x = A^-1 @ b   (since A^-1 @ A = I)
#   x = A^-1 @ b       (since I @ x = x)
A_inv = inv(A)
print("STEP 1: Compute A^-1 (inverse of A)")
print("A^-1 =")
print(A_inv)
print()

# STEP 4: Multiply A^-1 by b to get the solution
# x = A^-1 @ b
x_solution = A_inv @ b
print("STEP 2: Multiply A^-1 @ b to get solution")
print("x_solution = A^-1 @ b =")
print(x_solution)
print()

# STEP 5: Verify the solution by substituting back into original equations
# If x is correct, then A @ x should equal b exactly
verification = A @ x_solution
print("STEP 3: Verify the solution")
print("Check: A @ x_solution =")
print(verification)
print()
print("This should match b =")
print(b)
print()
print(f"✓ Match? {np.allclose(verification, b)}")
print()

# STEP 6: Extract the individual solutions
# x_solution is a 2D array [[x], [y]], so extract the scalar values
x, y = x_solution[0, 0], x_solution[1, 0]
print("=" * 60)
print(f"SOLUTION: x = {x:.4f}, y = {y:.4f}")
print("=" * 60)
print()

# STEP 7: Double-check by plugging back into the original equations
eq1_result = 3*x + 2*y
eq2_result = 4*x - y
print("VERIFICATION (plug into original equations):")
print(f"  Equation 1: 3({x:.4f}) + 2({y:.4f}) = {eq1_result:.4f}  ✓ (should be 8)")
print(f"  Equation 2: 4({x:.4f}) - ({y:.4f}) = {eq2_result:.4f}  ✓ (should be 5)")
print()
print("✓ Both equations are satisfied!")


LINEAR SYSTEM OF EQUATIONS: A @ x = b

Coefficient matrix A:
[[ 3.  2.]
 [ 4. -1.]]

Constants vector b:
[[8.]
 [5.]]

Matrix equation: A @ x = b means:
  [3   2] @ [x]   [8]
  [4  -1]   [y] = [5]

STEP 1: Compute A^-1 (inverse of A)
A^-1 =
[[ 0.09090909  0.18181818]
 [ 0.36363636 -0.27272727]]

STEP 2: Multiply A^-1 @ b to get solution
x_solution = A^-1 @ b =
[[1.63636364]
 [1.54545455]]

STEP 3: Verify the solution
Check: A @ x_solution =
[[8.]
 [5.]]

This should match b =
[[8.]
 [5.]]

✓ Match? True

SOLUTION: x = 1.6364, y = 1.5455

VERIFICATION (plug into original equations):
  Equation 1: 3(1.6364) + 2(1.5455) = 8.0000  ✓ (should be 8)
  Equation 2: 4(1.6364) - (1.5455) = 5.0000  ✓ (should be 5)

✓ Both equations are satisfied!


## Example 4: Non-invertible (Singular) Matrix

If a matrix is singular ($\det(A) = 0$), its inverse **does not exist**.

Example:
$$C = \begin{bmatrix} 2 & 4 \\ 3 & 6 \end{bmatrix}$$

Notice: Row 2 = 1.5 × Row 1, so the rows are **linearly dependent** and $\det(C) = 0$.

Attempting to invert this matrix will raise an error or return an invalid result.


In [37]:
# Define a singular (non-invertible) matrix
C = np.array([[2, 4],
              [3, 6]], dtype=float)

print("Matrix C:")
print(C)
print()

# Compute determinant
det_C = det(C)
print(f"Determinant of C: {det_C}")
print(f"Invertible? {det_C != 0}")
print()

# Try to compute inverse — this will fail
try:
    C_inv = inv(C)
    print("C_inv =")
    print(C_inv)
except np.linalg.LinAlgError as e:
    print(f"ERROR: Cannot invert C because it is singular")
    print(f"Details: {e}")


Matrix C:
[[2. 4.]
 [3. 6.]]

Determinant of C: 0.0
Invertible? False

ERROR: Cannot invert C because it is singular
Details: Singular matrix


## Example 5: Undoing a Transformation with Inverse

A key application: if matrix $T$ represents a transformation, then $T^{-1}$ **reverses** it.

**Example:** Rotate by 45°, then rotate back using $R^{-1}$

Rotation matrix for angle $\theta$:
$$R(\theta) = \begin{bmatrix} \cos\theta & -\sin\theta \\ \sin\theta & \cos\theta \end{bmatrix}$$

Its inverse is:
$$R^{-1}(\theta) = R(-\theta) = \begin{bmatrix} \cos\theta & \sin\theta \\ -\sin\theta & \cos\theta \end{bmatrix}$$

Notice: For rotation matrices, $R^{-1} = R^T$ (the inverse equals the transpose).


In [38]:
# Forward rotation by 45 degrees
theta = np.radians(45)
R = np.array([[np.cos(theta), -np.sin(theta)],
              [np.sin(theta),  np.cos(theta)]])

print("Rotation matrix R (45°):")
print(R)
print()

# Point to rotate
point = np.array([[1], [0]])  # Start at (1, 0)

# Apply rotation
rotated = R @ point

print(f"Original point: {point.T}")
print(f"After rotation by 45°: {rotated.T}")
print()

# Compute inverse
R_inv = inv(R)
print("Inverse of R (should be R(-45°)):")
print(R_inv)
print()

# Apply inverse to undo the rotation
restored = R_inv @ rotated
print(f"After applying R^-1 (undo rotation): {restored.T}")
print(f"(Should match original point {point.T})")
print()

# For rotation matrices, R^-1 = R^T (transpose)
R_transpose = R.T
print("R^T (transpose):")
print(R_transpose)
print()
print(f"Is R^-1 == R^T? {np.allclose(R_inv, R_transpose)}")


Rotation matrix R (45°):
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Original point: [[1 0]]
After rotation by 45°: [[0.70710678 0.70710678]]

Inverse of R (should be R(-45°)):
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]

After applying R^-1 (undo rotation): [[1.00000000e+00 1.01465364e-17]]
(Should match original point [[1 0]])

R^T (transpose):
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]

Is R^-1 == R^T? True


## Bonus: `inv()` vs `solve()` for Solving Systems

When solving $A\mathbf{x} = \mathbf{b}$, you have two options:

### Method 1: Using Inverse
$$\mathbf{x} = A^{-1}\mathbf{b}$$

```python
x = inv(A) @ b
```

### Method 2: Using Direct Solver
$$\mathbf{x} = \text{solve}(A, b)$$

```python
x = np.linalg.solve(A, b)
```

**Which is better?**
- **Solve is faster and more numerically stable** — it uses optimized algorithms (LU decomposition) that don't explicitly compute the inverse
- **Inverse is more intuitive** for understanding (mathematically)
- **Rule:** Always prefer `solve()` for solving systems; use `inv()` only when you need the actual inverse matrix itself

Let's compare both methods:


In [39]:
from numpy.linalg import solve

# Define system A @ x = b
A = np.array([[3, 2],
              [4, -1]], dtype=float)
b = np.array([8, 5], dtype=float)

print("System: A @ x = b")
print("A =")
print(A)
print("b =", b)
print()

# Method 1: Using inverse
x_inv = inv(A) @ b
print("Method 1 (using inverse): x = inv(A) @ b")
print(x_inv)
print()

# Method 2: Using solver
x_solve = solve(A, b)
print("Method 2 (using solve): x = solve(A, b)")
print(x_solve)
print()

# They give the same result (up to numerical precision)
print(f"Results are identical? {np.allclose(x_inv, x_solve)}")
print()

# For production code, prefer solve() because it's more efficient
print("✓ In practice, always use np.linalg.solve() for solving systems")
print("✓ Use inv() only when you specifically need the inverse matrix")


System: A @ x = b
A =
[[ 3.  2.]
 [ 4. -1.]]
b = [8. 5.]

Method 1 (using inverse): x = inv(A) @ b
[1.63636364 1.54545455]

Method 2 (using solve): x = solve(A, b)
[1.63636364 1.54545455]

Results are identical? True

✓ In practice, always use np.linalg.solve() for solving systems
✓ Use inv() only when you specifically need the inverse matrix


## Key Properties of Matrix Inverse

| Property | Formula | Meaning |
|----------|---------|---------|
| **Definition** | $AA^{-1} = A^{-1}A = I$ | Inverse undoes the original matrix |
| **Inverse of inverse** | $(A^{-1})^{-1} = A$ | Inverting twice gives back the original |
| **Product rule** | $(AB)^{-1} = B^{-1}A^{-1}$ | Inverse of a product (note the order!) |
| **Determinant** | $\det(A^{-1}) = \frac{1}{\det(A)}$ | Inverse's determinant is the reciprocal |
| **Transpose** | $(A^T)^{-1} = (A^{-1})^T$ | Can transpose before or after inverting |
| **Scalar mult.** | $(cA)^{-1} = \frac{1}{c}A^{-1}$ | Inverse distributes over scalar multiplication |
| **Orthogonal** | $Q^{-1} = Q^T$ | For orthogonal matrices, inverse is the transpose |

### Important: Order Matters in $(AB)^{-1} = B^{-1}A^{-1}$

Notice the reversal: $(AB)^{-1}$ is **NOT** $A^{-1}B^{-1}$, but rather $B^{-1}A^{-1}$ ✓


In [40]:
# Verify the property: (AB)^-1 = B^-1 @ A^-1

A = np.array([[4, 7],
              [2, 6]], dtype=float)

B = np.array([[1, 2],
              [3, 4]], dtype=float)

print("Matrix A:")
print(A)
print()
print("Matrix B:")
print(B)
print()

# Method 1: Inverse of the product
AB = A @ B
AB_inv = inv(AB)
print("Method 1: (AB)^-1 =")
print(AB_inv)
print()

# Method 2: Product of inverses (in reverse order!)
B_inv = inv(B)
A_inv = inv(A)
B_inv_A_inv = B_inv @ A_inv
print("Method 2: B^-1 @ A^-1 =")
print(B_inv_A_inv)
print()

# Verify they are equal
print(f"Are they equal? {np.allclose(AB_inv, B_inv_A_inv)}")
print()

# What if we get the order wrong?
wrong_order = A_inv @ B_inv
print("Wrong order (A^-1 @ B^-1):")
print(wrong_order)
print()
print(f"Is wrong order equal? {np.allclose(AB_inv, wrong_order)}")
print("➜ Order MATTERS!")


Matrix A:
[[4. 7.]
 [2. 6.]]

Matrix B:
[[1. 2.]
 [3. 4.]]

Method 1: (AB)^-1 =
[[-1.4   1.8 ]
 [ 1.   -1.25]]

Method 2: B^-1 @ A^-1 =
[[-1.4   1.8 ]
 [ 1.   -1.25]]

Are they equal? True

Wrong order (A^-1 @ B^-1):
[[-2.25  0.95]
 [ 1.   -0.4 ]]

Is wrong order equal? False
➜ Order MATTERS!


## Summary & Key Takeaways

✅ **When to use matrix inverse:**
- Solving systems: $\mathbf{x} = A^{-1}\mathbf{b}$ (though `solve()` is often better)
- Understanding transformations and their reversal
- Computing properties ($\det(A^{-1}) = 1/\det(A)$)
- Theoretical analysis and proofs

✅ **How to check if a matrix is invertible:**
1. Compute $\det(A)$
2. If $\det(A) \neq 0$, the matrix is invertible
3. If $\det(A) = 0$, the matrix is singular (no inverse)

✅ **NumPy functions:**
- `np.linalg.inv(A)` — compute the inverse explicitly
- `np.linalg.det(A)` — compute the determinant
- `np.linalg.solve(A, b)` — solve $A\mathbf{x} = \mathbf{b}$ (faster and more stable than using inverse)

✅ **Common gotchas:**
- $(AB)^{-1} \neq A^{-1}B^{-1}$ — order matters! It's $B^{-1}A^{-1}$
- Singular matrices have no inverse — always check $\det(A) \neq 0$ first
- For very large or ill-conditioned matrices, numerical errors can accumulate

🎓 **Next steps:**
- Practice computing inverses by hand for 2×2 matrices
- Use `np.linalg.solve()` for real-world linear systems
- Explore eigenvalues and eigenvectors for deeper matrix understanding
