In [28]:
import numpy as np

# Operations on array

### Addition

In [29]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])

arr = arr_1 + arr_2

print('arr_1: ', arr_1)
print('arr_2: ', arr_2)
print('sum: ')
print(arr)

arr_1:  [1 2 3]
arr_2:  [4 5 6]
sum: 
[5 7 9]


### Substraction

In [30]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])

arr = arr_1 - arr_2

print('arr_1: ', arr_1)
print('arr_2: ', arr_2)
print('diff: ')
print(arr)

arr_1:  [1 2 3]
arr_2:  [4 5 6]
diff: 
[-3 -3 -3]


### Multiplication

In [31]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])

arr = arr_1 * arr_2

print('arr_1: ', arr_1)
print('arr_2: ', arr_2)
print('product: ')
print(arr)

arr_1:  [1 2 3]
arr_2:  [4 5 6]
product: 
[ 4 10 18]


### Scalar Addition, Substraction, Multiplication

In [32]:
arr = np.array([1,2,3,4])
print(arr)
arr = arr + 1
print(arr)
arr = arr - 1
print(arr)

arr = arr * 3
print(arr)

[1 2 3 4]
[2 3 4 5]
[1 2 3 4]
[ 3  6  9 12]


### Indexing 

In [33]:
arr = np.array([1,2,3,4])
for i in range(arr.size):
    print(arr[i])

1
2
3
4


### Slicing
`
arr = np.array(...)
arr[start:end:step]
`
start if not provided, defaults to 0
end   if not provided, defaults to size of array
step  if not provided, defaults to 1

In [55]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])

sub_array = arr[::]
print(sub_array)

sub_array_0_10_1 = arr[0:10:1]
print(sub_array_0_10_1)

sub_array_0_3_1 = arr[0:3:1]
print(sub_array_0_3_1)

sub_array_0_4_2 = arr[0:4:2]
print(sub_array_0_4_2)

sub_array_0__2 = arr[0::2]
print(sub_array_0__2)

sub_array_1__2 = arr[1::2]
print(sub_array_1__2)

rev_array = arr[::-1]
print(rev_array)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
[0 2]
[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]


### Horizontal Stacking

In [56]:
arr_1 = np.array([1,2,3,4])
arr_2 = np.array([5,6,7,8])

arr = np.hstack((arr_1, arr_2))
print(arr)

[1 2 3 4 5 6 7 8]


### Vertical Stacking

In [57]:
arr_1 = np.array([1,2,3,4])
arr_2 = np.array([5,6,7,8])

arr_3 = arr_1[::-1]
arr_4 = arr_2[::-1]

arr_5 = np.array([1,2,3,4,5])

arr_6 = np.vstack((arr_1, arr_2))
print(arr_6)
arr_6 = np.vstack((arr_6, arr_3))
print(arr_6)
arr_6 = np.vstack((arr_6, arr_4))
print(arr_6)

# uncommenting would result in error.
# arr_7 = np.vstack((arr_6, arr_5))

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [4 3 2 1]]
[[1 2 3 4]
 [5 6 7 8]
 [4 3 2 1]
 [8 7 6 5]]


### Horizontal Splitting

In [60]:
mat = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [4, 3, 2, 1],
                [8, 7, 6, 5]])

print("Matrix:")
print(mat)
print("Shape:", mat.shape)

# Horizontal splitting example
left, right = np.hsplit(mat, 2)

print(left)
print("Shape:", left.shape)

print(right)
print("Shape:", right.shape)

Matrix:
[[1 2 3 4]
 [5 6 7 8]
 [4 3 2 1]
 [8 7 6 5]]
Shape: (4, 4)
[[1 2]
 [5 6]
 [4 3]
 [8 7]]
Shape: (4, 2)
[[3 4]
 [7 8]
 [2 1]
 [6 5]]
Shape: (4, 2)


### Vertical Splitting

In [61]:
mat = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [4, 3, 2, 1],
                [8, 7, 6, 5]])

print("Matrix:")
print(mat)
print("Shape:", mat.shape)

# Vertical splitting example
top, bottom = np.vsplit(mat, 2)
print(top)
print("Shape:", top.shape)

print(bottom)
print("Shape:", bottom.shape)

Matrix:
[[1 2 3 4]
 [5 6 7 8]
 [4 3 2 1]
 [8 7 6 5]]
Shape: (4, 4)
[[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4)
[[4 3 2 1]
 [8 7 6 5]]
Shape: (2, 4)
