# Gaussian Elimination (Step by Step)

## Executive Summary
- Convert a linear system into an augmented matrix.
- Use row operations to create zeros below each pivot.
- Perform back substitution to get $x$, $y$, and $z$.
- Verify the result by checking $A\cdot\mathbf{x}=\mathbf{b}$.

In [99]:
import numpy as np

## Step 1: Define the system
We will solve:
$$
\begin{aligned}
x + y + z &= 6 \\n
2x + 3y + 7z &= 20 \\n
2x + y - z &= 1
\end{aligned}
$$

In [100]:
coefficients = np.array([
    [1, 1, 1],
    [2, 3, 7],
    [2, 1, -1]
], dtype=float)

constants_row = np.array([[6, 20, 1]], dtype=float)
constants = constants_row.T

aug_step1 = np.hstack([coefficients, constants])

print('Coefficient matrix A:')
print(coefficients)
print()
print('Constant vector b:')
print(constants)
print()
print('Augmented matrix [A|b]:')
print(aug_step1)

Coefficient matrix A:
[[ 1.  1.  1.]
 [ 2.  3.  7.]
 [ 2.  1. -1.]]

Constant vector b:
[[ 6.]
 [20.]
 [ 1.]]

Augmented matrix [A|b]:
[[ 1.  1.  1.  6.]
 [ 2.  3.  7. 20.]
 [ 2.  1. -1.  1.]]


## Step 2: Pivot at Row 1, Column 1
Pivot is at Row 1, Column 1 (value 1).
Apply:
- $R_2 \leftarrow R_2 - m_{21}R_1$, where $m_{21}=\dfrac{a_{21}}{a_{11}}$
- $R_3 \leftarrow R_3 - m_{31}R_1$, where $m_{31}=\dfrac{a_{31}}{a_{11}}$

In [101]:
aug_step2 = aug_step1.copy()

pivot_11 = aug_step2[0, 0]
multiplier_21 = aug_step2[1, 0] / pivot_11
multiplier_31 = aug_step2[2, 0] / pivot_11

aug_step2[1] = aug_step2[1] - multiplier_21 * aug_step2[0]
aug_step2[2] = aug_step2[2] - multiplier_31 * aug_step2[0]

print('Multiplier m21 =', multiplier_21)
print('Multiplier m31 =', multiplier_31)
print('After Step 2:')
print(aug_step2)

Multiplier m21 = 2.0
Multiplier m31 = 2.0
After Step 2:
[[  1.   1.   1.   6.]
 [  0.   1.   5.   8.]
 [  0.  -1.  -3. -11.]]


## Step 3: Pivot at Row 2, Column 2
Now pivot is at Row 2, Column 2.
Apply:
- $R_3 \leftarrow R_3 - m_{32}R_2$, where $m_{32} = \dfrac{a_{32}}{a_{22}}$

In [102]:
aug_step3 = aug_step2.copy()

pivot_22 = aug_step3[1, 1]
multiplier_32 = aug_step3[2, 1] / pivot_22
aug_step3[2] = aug_step3[2] - multiplier_32 * aug_step3[1]

print('Multiplier m32 =', multiplier_32)
print('After Step 3:')
print(aug_step3)

Multiplier m32 = -1.0
After Step 3:
[[ 1.  1.  1.  6.]
 [ 0.  1.  5.  8.]
 [ 0.  0.  2. -3.]]


## Step 4: Pivot at Row 3, Column 3
Make the pivot at [3,3] equal to 1 before solving:
- $R_3 \leftarrow \dfrac{1}{a_{33}}R_3$

In [103]:
aug_step4 = aug_step3.copy()

pivot_33_step4 = aug_step4[2, 2]
aug_step4[2] = aug_step4[2] / pivot_33_step4

print('Row-3 scaling factor =', 1 / pivot_33_step4)
print('After Step 4:')
print(aug_step4)

Row-3 scaling factor = 0.5
After Step 4:
[[ 1.   1.   1.   6. ]
 [ 0.   1.   5.   8. ]
 [ 0.   0.   1.  -1.5]]


## Step 5: Back substitution (as elimination sub-steps)
Using pivot rows to create zeros above pivots:
1. Zero out Row 2, Column 3
2. Zero out Row 1, Column 3
3. Zero out Row 1, Column 2
Display the matrix after each sub-step.

In [104]:
aug_step5 = aug_step4.copy()

# Sub-step 5.1: Zero out Row 2, Column 3 (1-based indexing)
factor_23 = aug_step5[1, 2]
aug_step5[1] = aug_step5[1] - factor_23 * aug_step5[2]
print('After Sub-step 5.1 (zero out Row 2, Column 3):')
print(aug_step5)
print()

# Sub-step 5.2: Zero out Row 1, Column 3
factor_13 = aug_step5[0, 2]
aug_step5[0] = aug_step5[0] - factor_13 * aug_step5[2]
print('After Sub-step 5.2 (zero out Row 1, Column 3):')
print(aug_step5)
print()

# Sub-step 5.3: Zero out Row 1, Column 2
factor_12 = aug_step5[0, 1]
aug_step5[0] = aug_step5[0] - factor_12 * aug_step5[1]
print('After Sub-step 5.3 (zero out Row 1, Column 2):')
print(aug_step5)
print()

# Use horizontal split to separate [A|b] and read solution from b
coeff_final, b_final = np.hsplit(aug_step5, [3])
solution = b_final.reshape(-1)

print('Final coefficient part after elimination:')
print(coeff_final)
print('Solution [x, y, z]:')
print(solution)

After Sub-step 5.1 (zero out Row 2, Column 3):
[[ 1.   1.   1.   6. ]
 [ 0.   1.   0.  15.5]
 [ 0.   0.   1.  -1.5]]

After Sub-step 5.2 (zero out Row 1, Column 3):
[[ 1.   1.   0.   7.5]
 [ 0.   1.   0.  15.5]
 [ 0.   0.   1.  -1.5]]

After Sub-step 5.3 (zero out Row 1, Column 2):
[[ 1.   0.   0.  -8. ]
 [ 0.   1.   0.  15.5]
 [ 0.   0.   1.  -1.5]]

Final coefficient part after elimination:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Solution [x, y, z]:
[-8.  15.5 -1.5]


## Step 6: Verify with matrix multiplication
Check whether $A\cdot\mathbf{x}$ matches $\mathbf{b}$.

In [105]:
b_check = coefficients @ solution.reshape(-1, 1)

print('A @ solution:')
print(b_check)
print()
print('Original b:')
print(constants)
print()
print('Matches original b:', np.allclose(b_check, constants))

A @ solution:
[[ 6.]
 [20.]
 [ 1.]]

Original b:
[[ 6.]
 [20.]
 [ 1.]]

Matches original b: True


## Step 7: Verification using NumPy
Solve the same system with `np.linalg.solve` and compare with the elimination result.

In [106]:
numpy_solution = np.linalg.solve(coefficients, constants).reshape(-1)

print('Solution from elimination:')
print(solution)
print()
print('Solution from NumPy (np.linalg.solve):')
print(numpy_solution)
print()
print('Both solutions match:', np.allclose(solution, numpy_solution))

Solution from elimination:
[-8.  15.5 -1.5]

Solution from NumPy (np.linalg.solve):
[-8.  15.5 -1.5]

Both solutions match: True


## Step 8: `gaussian_elimination` function
Implement one function that performs all elimination steps in loops and returns the final solution vector.

In [107]:
def gaussian_elimination(A, b):
    m = np.hstack([A.astype(float).copy(), b.astype(float).copy()])
    rows, cols = m.shape
    n = cols - 1

    # Forward elimination: create zeros below pivots
    for pivot in range(n):
        # Partial pivoting for numerical stability
        max_row = pivot + np.argmax(np.abs(m[pivot:, pivot]))
        if abs(m[max_row, pivot]) < 1e-12:
            raise ValueError('Matrix is singular or nearly singular.')
        if max_row != pivot:
            m[[pivot, max_row]] = m[[max_row, pivot]]

        for r in range(pivot + 1, rows):
            factor = m[r, pivot] / m[pivot, pivot]
            m[r] = m[r] - factor * m[pivot]

    # Normalize pivots to 1
    for pivot in range(n):
        m[pivot] = m[pivot] / m[pivot, pivot]

    # Backward elimination: create zeros above pivots
    for pivot in range(n - 1, -1, -1):
        for r in range(pivot - 1, -1, -1):
            factor = m[r, pivot]
            m[r] = m[r] - factor * m[pivot]

    # Final solution vector from the last column
    return m[:, -1]

solution_from_function = gaussian_elimination(coefficients, constants)
print('Solution from gaussian_elimination function:')
print(solution_from_function)

Solution from gaussian_elimination function:
[-8.  15.5 -1.5]
