# Mathematics Basics Starter
This notebook introduces basic mathematics concepts using NumPy.

### Creating one dimentional array

In [9]:
import numpy as np

# Example: create an array and compute its mean
arr = np.array([1,2,3,4,5])
print('Array:', arr)
print('Mean:', arr.mean())
print('Transpose:', arr.transpose())
print('Size: ', arr.size)
print('Shape: ', arr.shape)
print('Dimension: ', arr.ndim)

# Additional useful prints for arr
print('Data type:', arr.dtype)
print('Item size (bytes per element):', arr.itemsize)
print('Total bytes:', arr.nbytes)
print('Sum:', arr.sum())
print('Standard deviation:', arr.std())
print('Variance:', arr.var())
print('Minimum:', arr.min())
print('Maximum:', arr.max())
print('Cumulative sum:', arr.cumsum())
print('Cumulative product:', arr.cumprod())
print('Sorted array:', np.sort(arr))
print('Unique elements:', np.unique(arr))
print('Flattened array:', arr.flatten())

# get rows and columns from arr.shape
if len(arr.shape) == 1:
    rows = arr.shape[0]
    cols = 1  # assume 1 column for 1D array
else:
    rows, cols = arr.shape

print("Rows:", rows, "Cols:", cols)

# use them in reshape
arr = arr.reshape(rows, cols)
print("Reshaped array:")
print(arr)
print("New shape:", arr.shape)

Array: [1 2 3 4 5]
Mean: 3.0
Transpose: [1 2 3 4 5]
Size:  5
Shape:  (5,)
Dimension:  1
Data type: int64
Item size (bytes per element): 8
Total bytes: 40
Sum: 15
Standard deviation: 1.4142135623730951
Variance: 2.0
Minimum: 1
Maximum: 5
Cumulative sum: [ 1  3  6 10 15]
Cumulative product: [  1   2   6  24 120]
Sorted array: [1 2 3 4 5]
Unique elements: [1 2 3 4 5]
Flattened array: [1 2 3 4 5]
Rows: 5 Cols: 1
Reshaped array:
[[1]
 [2]
 [3]
 [4]
 [5]]
New shape: (5, 1)


### Other ways of creating one dimensional array

In [15]:
arr_1 = np.array([1,2,3])
print(arr_1)

arr_2 = np.arange(1,4,1)
print(arr_2)

arr_3 = np.arange(3)
print(arr_3)

arr_4 = np.linspace(1, 4, 3, dtype=int)
print(arr_4)

arr_5 = np.ones(3, dtype=int)
print(arr_5)

arr_6 = np.zeros(3, dtype=int)
print(arr_6)

arr_7 = np.empty(3, dtype=int)
print(arr_7)

arr_8 = np.random.rand(3)
print(arr_8)

# Random integers instead of floats
arr_9 = np.random.randint(0, 10, 3)  # random ints from 0 to 9
print(arr_9)

[1 2 3]
[1 2 3]
[0 1 2]
[1 2 4]
[1 1 1]
[0 0 0]
[0 0 0]
[0.56087761 0.70051789 0.37011366]
[3 0 2]
