In [48]:
import numpy as np

# Operations on array
## Executive Summary
- Introduces essential NumPy array operations used in data preparation and mathematical computation.
- Covers element-wise arithmetic between arrays:
  - addition
  - subtraction
  - multiplication
- Demonstrates scalar operations on arrays:
  - scalar addition
  - scalar subtraction
  - scalar multiplication
- Explains array access and transformation techniques:
  - indexing
  - slicing
- Shows array combination and partition operations:
  - horizontal and vertical stacking
  - horizontal and vertical splitting
- Concludes with vector dot product to connect array operations with core linear algebra concepts used in machine learning.

### Addition
> **Note:** The code block below performs element-wise addition of two NumPy arrays and prints both inputs with the resulting sum array.

In [49]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])

arr = arr_1 + arr_2

print('arr_1: ', arr_1)
print('arr_2: ', arr_2)
print('sum: ')
print(arr)

arr_1:  [1 2 3]
arr_2:  [4 5 6]
sum: 
[5 7 9]


### Subtraction
> **Note:** The code block below performs element-wise subtraction between two NumPy arrays and displays the input arrays and difference array.

In [50]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])

arr = arr_1 - arr_2

print('arr_1: ', arr_1)
print('arr_2: ', arr_2)
print('diff: ')
print(arr)

arr_1:  [1 2 3]
arr_2:  [4 5 6]
diff: 
[-3 -3 -3]


### Multiplication
> **Note:** The code block below performs element-wise multiplication of two arrays and prints the operands and product array.

In [51]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])

arr = arr_1 * arr_2

print('arr_1: ', arr_1)
print('arr_2: ', arr_2)
print('product: ')
print(arr)

arr_1:  [1 2 3]
arr_2:  [4 5 6]
product: 
[ 4 10 18]


### Scalar Addition, Subtraction, Multiplication
> **Note:** The code block below applies scalar addition, subtraction, and multiplication to a NumPy array to demonstrate broadcasting with a single numeric value.

In [52]:
arr = np.array([1,2,3,4])
print(arr)
arr = arr + 1
print(arr)
arr = arr - 1
print(arr)

arr = arr * 3
print(arr)

[1 2 3 4]
[2 3 4 5]
[1 2 3 4]
[ 3  6  9 12]


### Indexing
> **Note:** The code block below iterates through array indices and prints each element, illustrating positional access in a 1D NumPy array.

In [53]:
arr = np.array([1,2,3,4])
for i in range(arr.size):
    print(arr[i])

1
2
3
4


### Slicing
```python
arr = np.array(...)
arr[start:end:step]
```
- `start` if not provided, defaults to `0`
- `end` if not provided, defaults to the size of the array
- `step` if not provided, defaults to `1`

> **Note:** The code block below demonstrates multiple slicing patterns, including full slices, bounded slices, step-based slices, odd/even index extraction, and array reversal.

In [54]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])

sub_array = arr[::]
print(sub_array)

sub_array_0_10_1 = arr[0:10:1]
print(sub_array_0_10_1)

sub_array_0_3_1 = arr[0:3:1]
print(sub_array_0_3_1)

sub_array_0_4_2 = arr[0:4:2]
print(sub_array_0_4_2)

sub_array_0__2 = arr[0::2]
print(sub_array_0__2)

sub_array_1__2 = arr[1::2]
print(sub_array_1__2)

rev_array = arr[::-1]
print(rev_array)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
[0 2]
[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]


### Horizontal Stacking
> **Note:** The code block below combines two 1D arrays side-by-side using `np.hstack` to create one longer array.

In [55]:
arr_1 = np.array([1,2,3,4])
arr_2 = np.array([5,6,7,8])

arr = np.hstack((arr_1, arr_2))
print(arr)

[1 2 3 4 5 6 7 8]


### Vertical Stacking
> **Note:** The code block below stacks multiple 1D arrays row-wise using `np.vstack` and shows how shape compatibility affects vertical stacking.

In [56]:
arr_1 = np.array([1,2,3,4])
arr_2 = np.array([5,6,7,8])

arr_3 = arr_1[::-1]
arr_4 = arr_2[::-1]

arr_5 = np.array([1,2,3,4,5])

arr_6 = np.vstack((arr_1, arr_2))
print(arr_6)
arr_6 = np.vstack((arr_6, arr_3))
print(arr_6)
arr_6 = np.vstack((arr_6, arr_4))
print(arr_6)

# uncommenting would result in error.
# arr_7 = np.vstack((arr_6, arr_5))

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [4 3 2 1]]
[[1 2 3 4]
 [5 6 7 8]
 [4 3 2 1]
 [8 7 6 5]]


### Horizontal Splitting
> **Note:** The code block below splits a matrix into left and right parts using `np.hsplit` and prints each result with its shape.

In [57]:
mat = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [4, 3, 2, 1],
                [8, 7, 6, 5]])

print("Matrix:")
print(mat)
print("Shape:", mat.shape)

# Horizontal splitting example
left, right = np.hsplit(mat, 2)

print(left)
print("Shape:", left.shape)

print(right)
print("Shape:", right.shape)

Matrix:
[[1 2 3 4]
 [5 6 7 8]
 [4 3 2 1]
 [8 7 6 5]]
Shape: (4, 4)
[[1 2]
 [5 6]
 [4 3]
 [8 7]]
Shape: (4, 2)
[[3 4]
 [7 8]
 [2 1]
 [6 5]]
Shape: (4, 2)


### Vertical Splitting
> **Note:** The code block below splits a matrix into top and bottom parts using `np.vsplit` and prints each split with dimensions.

In [58]:
mat = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [4, 3, 2, 1],
                [8, 7, 6, 5]])

print("Matrix:")
print(mat)
print("Shape:", mat.shape)

# Vertical splitting example
top, bottom = np.vsplit(mat, 2)
print(top)
print("Shape:", top.shape)

print(bottom)
print("Shape:", bottom.shape)

Matrix:
[[1 2 3 4]
 [5 6 7 8]
 [4 3 2 1]
 [8 7 6 5]]
Shape: (4, 4)
[[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4)
[[4 3 2 1]
 [8 7 6 5]]
Shape: (2, 4)


### DOT PRODUCT
> **Note:** The code block below creates two vectors and computes their dot product, a key linear algebra operation for similarity and projection calculations.

In [59]:
import numpy as np

# Create two vectors
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

# Compute dot product
dot_product = np.dot(vector_a, vector_b)

print("Vector A:", vector_a)
print("Vector B:", vector_b)
print("Dot Product:", dot_product)

Vector A: [1 2 3]
Vector B: [4 5 6]
Dot Product: 32
