# Matrix-Vector Multiplication

This notebook defines a custom function to multiply a matrix by a vector and verifies the result using NumPy.

In [ ]:
import numpy as np

## Custom Function

In [ ]:
def multiply_matrix_vector(matrix, vector):
    rows = len(matrix)
    cols = len(matrix[0])

    if len(vector) != cols:
        raise ValueError('Vector length must match matrix column count.')

    result = []
    for i in range(rows):
        total = 0
        for j in range(cols):
            total += matrix[i][j] * vector[j]
        result.append(total)

    return np.array(result, dtype=float)

## Verify Using NumPy

In [ ]:
import time

A = np.array([[2, -1, 3], [0, 4, 1]], dtype=float)
v = np.array([1, 2, -1], dtype=float)

res_1 = multiply_matrix_vector(A, v)
res_2 = np.matmul(A, v)

# Benchmark both approaches over many runs for more stable timing
runs = 100000

time_1 = time.perf_counter()
for _ in range(runs):
    multiply_matrix_vector(A, v)
time_1 = time.perf_counter() - time_1

time_2 = time.perf_counter()
for _ in range(runs):
    np.matmul(A, v)
time_2 = time.perf_counter() - time_2

print('Matrix A:')
print(A)
print()
print('Vector v:')
print(v)
print()
print('Custom A @ v:')
print(res_1)
print('NumPy A @ v:')
print(res_2)
print(f'Match: {np.allclose(res_1, res_2)}')
print()
print(f'Custom function time over {runs} runs: {time_1:.6f} s')
print(f'NumPy matmul time over {runs} runs: {time_2:.6f} s')

Matrix A:
[[ 2. -1.  3.]
 [ 0.  4.  1.]]

Vector v:
[ 1.  2. -1.]

Custom A @ v:
[-3.  7.]
NumPy A @ v:
[-3.  7.]
Match: True

Custom function time over 100000 runs: 0.283567 s
NumPy matmul time over 100000 runs: 0.089966 s
