# Differentiation of Dot Product Between Two Vectors

## Introduction

In this notebook, we explore one of the most fundamental operations in machine learning and optimization:
the **derivative of a dot product**. This is crucial for understanding how gradient descent works in neural networks
and other optimization algorithms.

### Key Question
**How does the dot product between two vectors change when we vary one of the vectors?**

## Theorem: Differentiation of Dot Product

### Setup
Let **x** and **y** be vectors of $d$ elements:

$\mathbf{x} = \begin{bmatrix} x_1 \\ x_2 \\ \vdots \\ x_d \end{bmatrix}, \quad \mathbf{y} = \begin{bmatrix} y_1 \\ y_2 \\ \vdots \\ y_d \end{bmatrix}$

$f(\mathbf{x}, \mathbf{y}) = \mathbf{x}^T\mathbf{y}$

### The Derivative with Respect to **x**

$\dfrac{d f(\mathbf{x}, \mathbf{y})}{d\mathbf{x}} = \nabla_\mathbf{x} f(\mathbf{x}, \mathbf{y}) = \mathbf{y}$

**Interpretation:** The gradient of the dot product with respect to **x** is simply the vector **y**.

### Similarly, with Respect to **y**

$\dfrac{d f(\mathbf{x}, \mathbf{y})}{d\mathbf{y}} = \nabla_\mathbf{y} f(\mathbf{x}, \mathbf{y}) = \mathbf{x}$

## Proof: Step-by-Step Derivation

### Step 1: Express the Dot Product
The dot product can be written as a sum:

$f(\mathbf{x}, \mathbf{y}) = \mathbf{x}^T\mathbf{y} = \sum_{i=1}^{d} x_i y_i = x_1y_1 + x_2y_2 + \cdots + x_dy_d$

### Step 2: Compute Partial Derivatives

$\dfrac{\partial f}{\partial x_1} = \dfrac{\partial(x_1y_1 + x_2y_2 + \cdots + x_dy_d)}{\partial x_1} = y_1$

$\dfrac{\partial f}{\partial x_2} = \dfrac{\partial(x_1y_1 + x_2y_2 + \cdots + x_dy_d)}{\partial x_2} = y_2$

$\vdots$

$\dfrac{\partial f}{\partial x_d} = \dfrac{\partial(x_1y_1 + x_2y_2 + \cdots + x_dy_d)}{\partial x_d} = y_d$

### Step 3: Construct the Gradient Vector
The gradient is the column vector of all partial derivatives:

$\nabla_\mathbf{x} f(\mathbf{x}, \mathbf{y}) = \begin{bmatrix} \dfrac{\partial f}{\partial x_1} \\ \dfrac{\partial f}{\partial x_2} \\ \vdots \\ \dfrac{\partial f}{\partial x_d} \end{bmatrix} = \begin{bmatrix} y_1 \\ y_2 \\ \vdots \\ y_d \end{bmatrix} = \mathbf{y}$

**Therefore:** $\boxed{\nabla_\mathbf{x} (\mathbf{x}^T\mathbf{y}) = \mathbf{y}}$

## Concrete Example: d = 2

### Setup
Let's work with 2-dimensional vectors:

$\mathbf{x} = \begin{bmatrix} x_1 \\ x_2 \end{bmatrix}, \quad \mathbf{y} = \begin{bmatrix} y_1 \\ y_2 \end{bmatrix}$

### The Function

$f(\mathbf{x}, \mathbf{y}) = \mathbf{x}^T\mathbf{y} = x_1y_1 + x_2y_2$

$\nabla_\mathbf{x} f(\mathbf{x}, \mathbf{y}) = \dfrac{d(\mathbf{x}^T\mathbf{y})}{d\mathbf{x}} = \begin{bmatrix} \dfrac{\partial(x_1y_1 + x_2y_2)}{\partial x_1} \\ \dfrac{\partial(x_1y_1 + x_2y_2)}{\partial x_2} \end{bmatrix} = \begin{bmatrix} y_1 \\ y_2 \end{bmatrix} = \mathbf{y}$

### Computing the Gradient with Respect to **y**

$\nabla_\mathbf{y} f(\mathbf{x}, \mathbf{y}) = \dfrac{d(\mathbf{x}^T\mathbf{y})}{d\mathbf{y}} = \begin{bmatrix} \dfrac{\partial(x_1y_1 + x_2y_2)}{\partial y_1} \\ \dfrac{\partial(x_1y_1 + x_2y_2)}{\partial y_2} \end{bmatrix} = \begin{bmatrix} x_1 \\ x_2 \end{bmatrix} = \mathbf{x}$

**Key Insight:** The gradient with respect to **y** is simply **x**, demonstrating the symmetry of the dot product.

## Numerical Verification

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Example 1: Numerical verification with 2D vectors
print("="*80)
print("EXAMPLE 1: Dot Product Differentiation (2D Case)")
print("="*80)

# Define vectors
x = np.array([1.0, 2.0])
y = np.array([3.0, 4.0])

print(f"\nVector x: {x}")
print(f"Vector y: {y}")

# Compute dot product
dot_product = np.dot(x, y)
print(f"\nDot product f(x, y) = x·y = {dot_product}")

# Theoretical gradient
gradient_theoretical = y
print(f"\nTheoretical gradient ∇_x f = y = {gradient_theoretical}")

# Numerical gradient (using finite differences)
epsilon = 1e-5
gradient_numerical = np.zeros_like(x)

for i in range(len(x)):
    x_plus = x.copy()
    x_plus[i] += epsilon
    f_plus = np.dot(x_plus, y)
    
    x_minus = x.copy()
    x_minus[i] -= epsilon
    f_minus = np.dot(x_minus, y)
    
    gradient_numerical[i] = (f_plus - f_minus) / (2 * epsilon)

print(f"Numerical gradient ≈ {gradient_numerical}")
print(f"\nDifference: {np.linalg.norm(gradient_theoretical - gradient_numerical):.2e}")
print("\n✓ Theoretical and numerical gradients match!")

EXAMPLE 1: Dot Product Differentiation (2D Case)

Vector x: [1. 2.]
Vector y: [3. 4.]

Dot product f(x, y) = x·y = 11.0

Theoretical gradient ∇_x f = y = [3. 4.]
Numerical gradient ≈ [3. 4.]

Difference: 3.60e-11

✓ Theoretical and numerical gradients match!


In [2]:
# Example 2: Higher dimensional case
print("\n" + "="*80)
print("EXAMPLE 2: Dot Product Differentiation (5D Case)")
print("="*80)

np.random.seed(42)
d = 5
x = np.random.randn(d)
y = np.random.randn(d)

print(f"\nVector x: {x}")
print(f"Vector y: {y}")

# Compute dot product
dot_product = np.dot(x, y)
print(f"\nDot product f(x, y) = x·y = {dot_product:.6f}")

# Theoretical gradient
gradient_theoretical = y
print(f"\nTheoretical gradient ∇_x f = y = {gradient_theoretical}")

# Numerical gradient
epsilon = 1e-5
gradient_numerical = np.zeros_like(x)

for i in range(len(x)):
    x_plus = x.copy()
    x_plus[i] += epsilon
    f_plus = np.dot(x_plus, y)
    
    x_minus = x.copy()
    x_minus[i] -= epsilon
    f_minus = np.dot(x_minus, y)
    
    gradient_numerical[i] = (f_plus - f_minus) / (2 * epsilon)

print(f"Numerical gradient ≈ {gradient_numerical}")
print(f"\nDifference (L2 norm): {np.linalg.norm(gradient_theoretical - gradient_numerical):.2e}")
print("\n✓ Gradients match perfectly!")


EXAMPLE 2: Dot Product Differentiation (5D Case)

Vector x: [ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]
Vector y: [-0.23413696  1.57921282  0.76743473 -0.46947439  0.54256004]

Dot product f(x, y) = x·y = -0.679655

Theoretical gradient ∇_x f = y = [-0.23413696  1.57921282  0.76743473 -0.46947439  0.54256004]
Numerical gradient ≈ [-0.23413696  1.57921282  0.76743473 -0.46947439  0.54256004]

Difference (L2 norm): 1.52e-11

✓ Gradients match perfectly!


## Applications in Machine Learning

### 1. Linear Models
In linear regression, we compute predictions as:

$\hat{y} = \mathbf{w}^T\mathbf{x}$

The gradient of the loss with respect to **w** involves $\frac{d(\mathbf{w}^T\mathbf{x})}{d\mathbf{w}} = \mathbf{x}$

### 2. Neural Networks
In the forward pass:

$\mathbf{z} = \mathbf{W}\mathbf{x} + \mathbf{b}$

Each element is a dot product: $z_i = \mathbf{w}_i^T\mathbf{x}$

During backpropagation, we need $\frac{d(\mathbf{w}_i^T\mathbf{x})}{d\mathbf{x}} = \mathbf{w}_i$

### 3. Attention Mechanisms
In transformer models, attention is computed using dot products:

$\text{Attention} = \text{softmax}\left(\frac{\mathbf{Q}\mathbf{K}^T}{\sqrt{d_k}}\right)\mathbf{V}$

Understanding dot product gradients is essential for backpropagation through attention layers.

## Chain Rule with Dot Products

In [3]:
# Example: Chain rule applied to dot product
print("="*80)
print("CHAIN RULE: Dot Product through a Function")
print("="*80)

print("\nScenario: L = f(x·y) where f is a nonlinear function")
print("Example: L = (x·y)² (squaring the dot product)")

x = np.array([1.0, 2.0])
y = np.array([3.0, 4.0])

# Forward pass
dot_prod = np.dot(x, y)
loss = dot_prod ** 2

print(f"\nx = {x}")
print(f"y = {y}")
print(f"dot_product = x·y = {dot_prod}")
print(f"loss = (x·y)² = {loss}")

# Using chain rule:
# dL/dx = dL/d(x·y) · d(x·y)/dx
# dL/d(x·y) = 2(x·y)
# d(x·y)/dx = y
# Therefore: dL/dx = 2(x·y) · y

dL_d_dotprod = 2 * dot_prod
gradient_x_theoretical = dL_d_dotprod * y

print(f"\nUsing chain rule:")
print(f"dL/d(x·y) = 2(x·y) = {dL_d_dotprod}")
print(f"d(x·y)/dx = y = {y}")
print(f"dL/dx = dL/d(x·y) · d(x·y)/dx = {dL_d_dotprod} · {y} = {gradient_x_theoretical}")

# Numerical verification
epsilon = 1e-5
gradient_x_numerical = np.zeros_like(x)

for i in range(len(x)):
    x_plus = x.copy()
    x_plus[i] += epsilon
    loss_plus = (np.dot(x_plus, y)) ** 2
    
    x_minus = x.copy()
    x_minus[i] -= epsilon
    loss_minus = (np.dot(x_minus, y)) ** 2
    
    gradient_x_numerical[i] = (loss_plus - loss_minus) / (2 * epsilon)

print(f"\nNumerical gradient: {gradient_x_numerical}")
print(f"Difference: {np.linalg.norm(gradient_x_theoretical - gradient_x_numerical):.2e}")
print("\n✓ Chain rule verification successful!")

CHAIN RULE: Dot Product through a Function

Scenario: L = f(x·y) where f is a nonlinear function
Example: L = (x·y)² (squaring the dot product)

x = [1. 2.]
y = [3. 4.]
dot_product = x·y = 11.0
loss = (x·y)² = 121.0

Using chain rule:
dL/d(x·y) = 2(x·y) = 22.0
d(x·y)/dx = y = [3. 4.]
dL/dx = dL/d(x·y) · d(x·y)/dx = 22.0 · [3. 4.] = [66. 88.]

Numerical gradient: [66. 88.]
Difference: 1.00e-09

✓ Chain rule verification successful!


## Differentiation of Squared Norm of a Vector

### Definition
The **squared norm** (or squared magnitude) of a vector **x** is:

$f(\mathbf{x}) = \|\mathbf{x}\|^2 = \mathbf{x}^T\mathbf{x}$

$f(\mathbf{x}) = \|\mathbf{x}\|^2 = x_1^2 + x_2^2 + \cdots + x_d^2$

### Derivative with Respect to **x**

$\dfrac{df(\mathbf{x})}{d\mathbf{x}} = \nabla_\mathbf{x} f(\mathbf{x}) = 2\mathbf{x}$

**Interpretation:** The gradient points in the direction of the vector itself, scaled by 2.

### Concrete Example: d = 2

$f(\mathbf{x}) = \mathbf{x}^T\mathbf{x} = x_1^2 + x_2^2$

$\nabla_\mathbf{x} f(\mathbf{x}) = \dfrac{d(\mathbf{x}^T\mathbf{x})}{d\mathbf{x}} = \begin{bmatrix} \dfrac{\partial(x_1^2 + x_2^2)}{\partial x_1} \\ \dfrac{\partial(x_1^2 + x_2^2)}{\partial x_2} \end{bmatrix} = \begin{bmatrix} 2x_1 \\ 2x_2 \end{bmatrix} = 2\mathbf{x}$

In [4]:
# Numerical verification of squared norm differentiation
print("="*80)
print("VERIFICATION: Differentiation of Squared Norm")
print("="*80)

# Example 1: 2D case
print("\nExample 1: 2D Vector")
x = np.array([3.0, 4.0])
print(f"Vector x: {x}")

# Compute squared norm
squared_norm = np.dot(x, x)
print(f"\nSquared norm f(x) = x·x = {squared_norm}")

# Theoretical gradient
gradient_theoretical = 2 * x
print(f"Theoretical gradient ∇_x f = 2x = {gradient_theoretical}")

# Numerical gradient
epsilon = 1e-5
gradient_numerical = np.zeros_like(x)

for i in range(len(x)):
    x_plus = x.copy()
    x_plus[i] += epsilon
    f_plus = np.dot(x_plus, x_plus)
    
    x_minus = x.copy()
    x_minus[i] -= epsilon
    f_minus = np.dot(x_minus, x_minus)
    
    gradient_numerical[i] = (f_plus - f_minus) / (2 * epsilon)

print(f"Numerical gradient ≈ {gradient_numerical}")
print(f"Difference: {np.linalg.norm(gradient_theoretical - gradient_numerical):.2e}")
print("✓ Gradients match!")

# Example 2: 5D case
print("\n" + "="*80)
print("Example 2: 5D Vector")
np.random.seed(123)
x = np.random.randn(5)
print(f"Vector x: {x}")

# Compute squared norm
squared_norm = np.dot(x, x)
print(f"\nSquared norm f(x) = x·x = {squared_norm:.6f}")

# Theoretical gradient
gradient_theoretical = 2 * x
print(f"Theoretical gradient ∇_x f = 2x = {gradient_theoretical}")

# Numerical gradient
epsilon = 1e-5
gradient_numerical = np.zeros_like(x)

for i in range(len(x)):
    x_plus = x.copy()
    x_plus[i] += epsilon
    f_plus = np.dot(x_plus, x_plus)
    
    x_minus = x.copy()
    x_minus[i] -= epsilon
    f_minus = np.dot(x_minus, x_minus)
    
    gradient_numerical[i] = (f_plus - f_minus) / (2 * epsilon)

print(f"Numerical gradient ≈ {gradient_numerical}")
print(f"Difference (L2 norm): {np.linalg.norm(gradient_theoretical - gradient_numerical):.2e}")
print("✓ Gradients match perfectly!")

VERIFICATION: Differentiation of Squared Norm

Example 1: 2D Vector
Vector x: [3. 4.]

Squared norm f(x) = x·x = 25.0
Theoretical gradient ∇_x f = 2x = [6. 8.]
Numerical gradient ≈ [6. 8.]
Difference: 1.79e-10
✓ Gradients match!

Example 2: 5D Vector
Vector x: [-1.0856306   0.99734545  0.2829785  -1.50629471 -0.57860025]

Squared norm f(x) = x·x = 4.857071
Theoretical gradient ∇_x f = 2x = [-2.17126121  1.99469089  0.565957   -3.01258943 -1.1572005 ]
Numerical gradient ≈ [-2.17126121  1.99469089  0.565957   -3.01258943 -1.1572005 ]
Difference (L2 norm): 7.66e-11
✓ Gradients match perfectly!


## Quadratic Term: Differentiation of $\mathbf{x}^T\mathbf{M}\mathbf{x}$

### Definition
The **quadratic form** is a generalization of the squared norm. Given:
- **x**: a vector of $d$ elements
- **M**: a square matrix of $d \times d$ elements

The quadratic form is:

$f(\mathbf{x}) = \mathbf{x}^T\mathbf{M}\mathbf{x}$

### Key Cases

#### Case 1: When **M** is NOT Symmetric

$\dfrac{df(\mathbf{x})}{d\mathbf{x}} = \nabla_\mathbf{x} f(\mathbf{x}) = \dfrac{d(\mathbf{x}^T\mathbf{M}\mathbf{x})}{d\mathbf{x}} = (\mathbf{M} + \mathbf{M}^T)\mathbf{x}$

**Key Insight:** We get both the matrix and its transpose!

#### Case 2: When **M** is Symmetric

$\dfrac{df(\mathbf{x})}{d\mathbf{x}} = \nabla_\mathbf{x} f(\mathbf{x}) = \dfrac{d(\mathbf{x}^T\mathbf{M}\mathbf{x})}{d\mathbf{x}} = 2\mathbf{M}\mathbf{x}$

**Special Case:** When $\mathbf{M} = \mathbf{I}$ (identity matrix), this reduces to the squared norm: $2\mathbf{x}$

### Proof Sketch

For the general case, we can expand:

$\mathbf{x}^T\mathbf{M}\mathbf{x} = \sum_{i=1}^{d} \sum_{j=1}^{d} x_i M_{ij} x_j$

Taking the partial derivative with respect to $x_k$:

$\dfrac{\partial(\mathbf{x}^T\mathbf{M}\mathbf{x})}{\partial x_k} = \sum_{j=1}^{d} M_{kj} x_j + \sum_{i=1}^{d} x_i M_{ik}$

This gives us:

$\dfrac{d(\mathbf{x}^T\mathbf{M}\mathbf{x})}{d\mathbf{x}} = \mathbf{M}\mathbf{x} + \mathbf{M}^T\mathbf{x} = (\mathbf{M} + \mathbf{M}^T)\mathbf{x}$

When $\mathbf{M}$ is symmetric, $\mathbf{M} = \mathbf{M}^T$, so:

$\dfrac{d(\mathbf{x}^T\mathbf{M}\mathbf{x})}{d\mathbf{x}} = 2\mathbf{M}\mathbf{x}$

In [5]:
# Numerical verification of quadratic term differentiation
print("="*80)
print("VERIFICATION: Differentiation of Quadratic Term x^T M x")
print("="*80)

# Example 1: Non-symmetric matrix
print("\nExample 1: Non-Symmetric Matrix")
print("-" * 80)

# Create a non-symmetric matrix
M_nonsym = np.array([[2.0, 3.0],
                      [1.0, 4.0]])
x = np.array([2.0, 1.0])

print(f"Matrix M:\n{M_nonsym}")
print(f"Vector x: {x}")

# Compute quadratic form
quadratic_form = x @ M_nonsym @ x
print(f"\nQuadratic form f(x) = x^T M x = {quadratic_form}")

# Theoretical gradient: (M + M^T) x
M_T = M_nonsym.T
gradient_theoretical = (M_nonsym + M_T) @ x
print(f"\nTheoretical gradient ∇_x f = (M + M^T)x")
print(f"M + M^T =\n{M_nonsym + M_T}")
print(f"(M + M^T)x = {gradient_theoretical}")

# Numerical gradient
epsilon = 1e-5
gradient_numerical = np.zeros_like(x)

for i in range(len(x)):
    x_plus = x.copy()
    x_plus[i] += epsilon
    f_plus = x_plus @ M_nonsym @ x_plus
    
    x_minus = x.copy()
    x_minus[i] -= epsilon
    f_minus = x_minus @ M_nonsym @ x_minus
    
    gradient_numerical[i] = (f_plus - f_minus) / (2 * epsilon)

print(f"Numerical gradient ≈ {gradient_numerical}")
print(f"Difference: {np.linalg.norm(gradient_theoretical - gradient_numerical):.2e}")
print("✓ Gradients match!")

# Example 2: Symmetric matrix
print("\n" + "="*80)
print("Example 2: Symmetric Matrix")
print("-" * 80)

# Create a symmetric matrix
M_sym = np.array([[3.0, 2.0],
                   [2.0, 5.0]])
x = np.array([1.0, 2.0])

print(f"Matrix M (symmetric):\n{M_sym}")
print(f"Vector x: {x}")

# Verify it's symmetric
is_symmetric = np.allclose(M_sym, M_sym.T)
print(f"Is M symmetric? {is_symmetric}")

# Compute quadratic form
quadratic_form = x @ M_sym @ x
print(f"\nQuadratic form f(x) = x^T M x = {quadratic_form}")

# Theoretical gradient: 2 M x (simplified for symmetric case)
gradient_theoretical = 2 * (M_sym @ x)
print(f"\nTheoretical gradient ∇_x f = 2Mx = {gradient_theoretical}")

# Numerical gradient
epsilon = 1e-5
gradient_numerical = np.zeros_like(x)

for i in range(len(x)):
    x_plus = x.copy()
    x_plus[i] += epsilon
    f_plus = x_plus @ M_sym @ x_plus
    
    x_minus = x.copy()
    x_minus[i] -= epsilon
    f_minus = x_minus @ M_sym @ x_minus
    
    gradient_numerical[i] = (f_plus - f_minus) / (2 * epsilon)

print(f"Numerical gradient ≈ {gradient_numerical}")
print(f"Difference: {np.linalg.norm(gradient_theoretical - gradient_numerical):.2e}")
print("✓ Gradients match!")

# Example 3: Special case - Identity matrix (should reduce to 2x)
print("\n" + "="*80)
print("Example 3: Identity Matrix (Special Case)")
print("-" * 80)

M_identity = np.eye(3)
x = np.array([1.0, -2.0, 3.0])

print(f"Matrix M = I (identity):\n{M_identity}")
print(f"Vector x: {x}")

# Compute quadratic form
quadratic_form = x @ M_identity @ x
print(f"\nQuadratic form f(x) = x^T I x = ||x||^2 = {quadratic_form}")

# Theoretical gradient: 2 I x = 2x (squared norm case)
gradient_theoretical = 2 * x
print(f"Theoretical gradient ∇_x f = 2x = {gradient_theoretical}")

# Numerical gradient
epsilon = 1e-5
gradient_numerical = np.zeros_like(x)

for i in range(len(x)):
    x_plus = x.copy()
    x_plus[i] += epsilon
    f_plus = x_plus @ M_identity @ x_plus
    
    x_minus = x.copy()
    x_minus[i] -= epsilon
    f_minus = x_minus @ M_identity @ x_minus
    
    gradient_numerical[i] = (f_plus - f_minus) / (2 * epsilon)

print(f"Numerical gradient ≈ {gradient_numerical}")
print(f"Difference: {np.linalg.norm(gradient_theoretical - gradient_numerical):.2e}")
print("✓ Gradients match!")

VERIFICATION: Differentiation of Quadratic Term x^T M x

Example 1: Non-Symmetric Matrix
--------------------------------------------------------------------------------
Matrix M:
[[2. 3.]
 [1. 4.]]
Vector x: [2. 1.]

Quadratic form f(x) = x^T M x = 20.0

Theoretical gradient ∇_x f = (M + M^T)x
M + M^T =
[[4. 4.]
 [4. 8.]]
(M + M^T)x = [12. 16.]
Numerical gradient ≈ [12. 16.]
Difference: 1.44e-10
✓ Gradients match!

Example 2: Symmetric Matrix
--------------------------------------------------------------------------------
Matrix M (symmetric):
[[3. 2.]
 [2. 5.]]
Vector x: [1. 2.]
Is M symmetric? True

Quadratic form f(x) = x^T M x = 31.0

Theoretical gradient ∇_x f = 2Mx = [14. 24.]
Numerical gradient ≈ [14. 24.]
Difference: 1.76e-10
✓ Gradients match!

Example 3: Identity Matrix (Special Case)
--------------------------------------------------------------------------------
Matrix M = I (identity):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Vector x: [ 1. -2.  3.]

Quadratic form f(x) = x^T

### Applications in Machine Learning

#### 1. Regularization (L2/Ridge Regression)
In ridge regression, the loss function includes:

$L = \|\|\mathbf{y} - \mathbf{X}\mathbf{w}\|\|^2 + \lambda \mathbf{w}^T\mathbf{w}$

The regularization term $\mathbf{w}^T\mathbf{w}$ is a quadratic form with $\mathbf{M} = \mathbf{I}$, so:

$\dfrac{d(\mathbf{w}^T\mathbf{w})}{d\mathbf{w}} = 2\mathbf{w}$

#### 2. Quadratic Optimization
Many machine learning problems are quadratic forms:

$\text{minimize} \quad \mathbf{x}^T\mathbf{Q}\mathbf{x} + \mathbf{c}^T\mathbf{x}$

For symmetric positive definite $\mathbf{Q}$:

$\nabla f = 2\mathbf{Q}\mathbf{x} + \mathbf{c}$

#### 3. Convexity Testing
A quadratic form $\mathbf{x}^T\mathbf{M}\mathbf{x}$ is:
- **Convex** if $\mathbf{M}$ is positive semidefinite
- **Concave** if $\mathbf{M}$ is negative semidefinite
- **Indefinite** otherwise

This determines the optimization landscape!



## Key Takeaways

1. **The gradient of $\mathbf{x}^T\mathbf{y}$ with respect to $\mathbf{x}$ is simply $\mathbf{y}$**
   - This is one of the simplest and most elegant results in calculus
   - By symmetry, $\frac{d(\mathbf{x}^T\mathbf{y})}{d\mathbf{y}} = \mathbf{x}$

2. **Intuition:** 
   - The gradient tells us which direction maximizes the dot product
   - The gradient points directly towards the other vector

3. **Implications for Optimization:**
   - In gradient descent, we move in direction $-\mathbf{y}$ to minimize $\mathbf{x}^T\mathbf{y}$
   - This drives **x** away from **y**

4. **Machine Learning Impact:**
   - Every neural network layer uses dot products
   - Backpropagation relies fundamentally on this derivative
   - Understanding this enables efficient gradient computations

## Summary Table: Differentiation Rules for Common Functions

| Function | Derivative w.r.t. **x** | Notes |
|----------|------------------------|-------|
| $f(\mathbf{x}) = \mathbf{x}^T\mathbf{y}$ | $\mathbf{y}$ | Linear in **x** |
| $f(\mathbf{x}) = \mathbf{x}^T\mathbf{A}\mathbf{x}$ | $\mathbf{A}\mathbf{x} + \mathbf{A}^T\mathbf{x}$ | Quadratic form |
| $f(\mathbf{x}) = \|\|\mathbf{x}\|\|^2$ | $2\mathbf{x}$ | Norm squared |
| $f(\mathbf{x}) = \mathbf{a}^T\mathbf{x}$ | $\mathbf{a}$ | Linear |
| $f(\mathbf{x}) = (\mathbf{x}^T\mathbf{a})^2$ | $2(\mathbf{a}^T\mathbf{x})\mathbf{a}$ | Chain rule applies |