# Jacobian Matrix: Derivatives of Vector-Valued Functions

## Introduction to Vector-Valued Functions

### From Scalar to Vector Outputs

So far, we've studied functions that map vectors to scalars:
- **Input:** Vector $\mathbf{x} \in \mathbb{R}^d$
- **Output:** Scalar $y \in \mathbb{R}$

Now we explore a more general case:
- **Input:** Vector $\mathbf{x} \in \mathbb{R}^d$
- **Output:** Vector $\mathbf{y} \in \mathbb{R}^k$ (multiple outputs)

### Definition: Vector-Valued Function

A **vector-valued function** is:

$\mathbf{f}(\mathbf{x}) = \begin{bmatrix} f_1(\mathbf{x}) \\ f_2(\mathbf{x}) \\ \vdots \\ f_k(\mathbf{x}) \end{bmatrix}$

where:
- $\mathbf{x} = [x_1, x_2, ..., x_d]^T$ is an input vector of $d$ variables
- $f_1(\mathbf{x}), f_2(\mathbf{x}), ..., f_k(\mathbf{x})$ are $k$ functions of vector $\mathbf{x}$
- Each function $f_i(\mathbf{x})$ can be **linear** or **non-linear**

**In matrix form:**

$\mathbf{y} = \mathbf{f}(\mathbf{x}) = \begin{bmatrix} y_1 \\ y_2 \\ \vdots \\ y_k \end{bmatrix} = \begin{bmatrix} f_1(\mathbf{x}) \\ f_2(\mathbf{x}) \\ \vdots \\ f_k(\mathbf{x}) \end{bmatrix}$

## Example 1: Linear Vector-Valued Function

### Matrix-Vector Multiplication

**Given:**
- $\mathbf{x}$ = vector of $d$ elements
- $\mathbf{M}$ = square matrix of $d \times d$ elements

**Operation:** $\mathbf{y} = \mathbf{M}\mathbf{x}$ results in a vector $\mathbf{y}$ of $d$ elements

$\mathbf{y} = \mathbf{M}\mathbf{x} = \begin{bmatrix} m_{11} & m_{12} & \cdots & m_{1d} \\ m_{21} & m_{22} & \cdots & m_{2d} \\ \vdots & \vdots & \ddots & \vdots \\ m_{d1} & m_{d2} & \cdots & m_{dd} \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \\ \vdots \\ x_d \end{bmatrix} = \begin{bmatrix} m_{11}x_1 + m_{12}x_2 + \cdots + m_{1d}x_d \\ m_{21}x_1 + m_{22}x_2 + \cdots + m_{2d}x_d \\ \vdots \\ m_{d1}x_1 + m_{d2}x_2 + \cdots + m_{dd}x_d \end{bmatrix}$

**Key Point:** Each function is linear:

$y_i = f_i(\mathbf{x}) = m_{i1}x_1 + m_{i2}x_2 + \cdots + m_{id}x_d$

## Example 2: Rectangle to Rectangle Transformation

### Non-Square Matrix

**Given:**
- $\mathbf{x}$ = vector of $d$ elements  
- $\mathbf{M}$ = matrix of $k \times d$ elements

**Operation:** $\mathbf{y} = \mathbf{M}\mathbf{x}$ results in a vector $\mathbf{y}$ of $k$ elements

$\mathbf{y} = \mathbf{M}\mathbf{x} = \begin{bmatrix} m_{11} & m_{12} & \cdots & m_{1d} \\ m_{21} & m_{22} & \cdots & m_{2d} \\ \vdots & \vdots & \ddots & \vdots \\ m_{k1} & m_{k2} & \cdots & m_{kd} \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \\ \vdots \\ x_d \end{bmatrix} = \begin{bmatrix} m_{11}x_1 + m_{12}x_2 + \cdots + m_{1d}x_d \\ m_{21}x_1 + m_{22}x_2 + \cdots + m_{2d}x_d \\ \vdots \\ m_{k1}x_1 + m_{k2}x_2 + \cdots + m_{kd}x_d \end{bmatrix}$

**Transformation:** Maps from $\mathbb{R}^d$ to $\mathbb{R}^k$ (can be different dimensions!)

**Each function is linear:**

$y_i = f_i(\mathbf{x}) = m_{i1}x_1 + m_{i2}x_2 + \cdots + m_{id}x_d$

## Example 3: Non-Linear Vector-Valued Function

### Polynomial Functions

**Given:** $\mathbf{x} = [x_1, x_2]^T$ (2 dimensions)

**Vector-valued function with 3 outputs:**

$f_1(\mathbf{x}) = 2x_1^2 + 3x_2 + 5$

$f_2(\mathbf{x}) = 4x_1^2 + 3x_1x_2 + 6x_2^2 + 4x_2 + 5$

$f_3(\mathbf{x}) = 4x_1^3 + 9x_1^2 + 6x_2^2 - 5x_1x_2 + 2$

$\mathbf{f}(\mathbf{x}) = \begin{bmatrix} f_1(\mathbf{x}) \\ f_2(\mathbf{x}) \\ f_3(\mathbf{x}) \end{bmatrix}$

**Key Point:** Each function is **non-linear** (contains polynomial terms of degree > 1)

## Detailed Example: Computing Jacobian for Linear 2D Case

### Problem Setup

Let $\mathbf{x} = [x_1, x_2]^T$ be a 2-dimensional input vector and $\mathbf{M}$ be a $2 \times 2$ square matrix:

$\mathbf{x} = \begin{bmatrix} x_1 \\ x_2 \end{bmatrix}, \quad \mathbf{M} = \begin{bmatrix} m_{11} & m_{12} \\ m_{21} & m_{22} \end{bmatrix}$

**Operation:** $\mathbf{y} = \mathbf{M}\mathbf{x}$ (matrix-vector multiplication)

### Matrix-Vector Multiplication

$\mathbf{M}\mathbf{x} = \begin{bmatrix} m_{11} & m_{12} \\ m_{21} & m_{22} \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \end{bmatrix} = \begin{bmatrix} m_{11}x_1 + m_{12}x_2 \\ m_{21}x_1 + m_{22}x_2 \end{bmatrix} = \begin{bmatrix} f_1(\mathbf{x}) \\ f_2(\mathbf{x}) \end{bmatrix} = \mathbf{f}(\mathbf{x})$

This gives us **two functions:**

$f_1(\mathbf{x}) = m_{11}x_1 + m_{12}x_2$

$f_2(\mathbf{x}) = m_{21}x_1 + m_{22}x_2$

### Step 1: Compute Gradient of First Function

**Derivative of $f_1(\mathbf{x})$ with respect to $\mathbf{x}$:**

$\dfrac{\partial f_1}{\partial x_1} = \dfrac{\partial(m_{11}x_1 + m_{12}x_2)}{\partial x_1} = m_{11}$

$\dfrac{\partial f_1}{\partial x_2} = \dfrac{\partial(m_{11}x_1 + m_{12}x_2)}{\partial x_2} = m_{12}$

**Row 1 of Jacobian:** $[m_{11}, m_{12}]$

### Step 2: Compute Gradient of Second Function

**Derivative of $f_2(\mathbf{x})$ with respect to $\mathbf{x}$:**

$\dfrac{\partial f_2}{\partial x_1} = \dfrac{\partial(m_{21}x_1 + m_{22}x_2)}{\partial x_1} = m_{21}$

$\dfrac{\partial f_2}{\partial x_2} = \dfrac{\partial(m_{21}x_1 + m_{22}x_2)}{\partial x_2} = m_{22}$

**Row 2 of Jacobian:** $[m_{21}, m_{22}]$

### The Complete Jacobian Matrix

Stacking the rows:

$\mathbf{J} = \dfrac{d\mathbf{f}(\mathbf{x})}{d\mathbf{x}} = \begin{bmatrix} m_{11} & m_{12} \\ m_{21} & m_{22} \end{bmatrix} = \mathbf{M}$

**Key Insight:** For the linear transformation $\mathbf{f}(\mathbf{x}) = \mathbf{M}\mathbf{x}$, the Jacobian matrix **equals the transformation matrix** $\mathbf{M}$!

This is independent of $\mathbf{x}$ — the Jacobian is the same everywhere.

**Dimensions:** $2 \times 2$ (2 functions, 2 input variables)

### Alternative View: Jacobian as Stacked Gradients

We can also view the Jacobian by first computing the gradient of each function as a column vector, then stacking them horizontally:

**Gradient of first function:**

$\dfrac{d f_1(\mathbf{x})}{d\mathbf{x}} = \begin{bmatrix} \dfrac{\partial f_1}{\partial x_1} \\ \dfrac{\partial f_1}{\partial x_2} \end{bmatrix} = \begin{bmatrix} m_{11} \\ m_{12} \end{bmatrix}$

**Gradient of second function:**

$\dfrac{d f_2(\mathbf{x})}{d\mathbf{x}} = \begin{bmatrix} \dfrac{\partial f_2}{\partial x_1} \\ \dfrac{\partial f_2}{\partial x_2} \end{bmatrix} = \begin{bmatrix} m_{21} \\ m_{22} \end{bmatrix}$

**Jacobian as Stacked Gradients:**

$\dfrac{d\mathbf{Mx}}{d\mathbf{x}} = \dfrac{d\mathbf{f}(\mathbf{x})}{d\mathbf{x}} = \left[\begin{array}{cc} \left[\dfrac{d f_1(\mathbf{x})}{d\mathbf{x}}\right]^T & \left[\dfrac{d f_2(\mathbf{x})}{d\mathbf{x}}\right]^T \end{array}\right] = \begin{bmatrix} m_{11} & m_{12} \\ m_{21} & m_{22} \end{bmatrix} = \mathbf{M}$

**Key Observation:** Each **row** of the Jacobian is the transpose of the gradient of one function. Equivalently, each **column** contains all the sensitivities to one input variable.

## Derivative of Vector-Valued Functions: The Jacobian Matrix

### Definition

The **derivative** of a vector-valued function $\mathbf{f}(\mathbf{x})$ with respect to input vector $\mathbf{x}$ is:

$\frac{d\mathbf{f}(\mathbf{x})}{d\mathbf{x}} = \begin{bmatrix} \nabla_\mathbf{x}^T f_1(\mathbf{x}) \\ \nabla_\mathbf{x}^T f_2(\mathbf{x}) \\ \vdots \\ \nabla_\mathbf{x}^T f_k(\mathbf{x}) \end{bmatrix}$

$\frac{d\mathbf{f}(\mathbf{x})}{d\mathbf{x}} = \begin{bmatrix} \frac{\partial f_1}{\partial x_1} & \frac{\partial f_1}{\partial x_2} & \cdots & \frac{\partial f_1}{\partial x_d} \\ \frac{\partial f_2}{\partial x_1} & \frac{\partial f_2}{\partial x_2} & \cdots & \frac{\partial f_2}{\partial x_d} \\ \vdots & \vdots & \ddots & \vdots \\ \frac{\partial f_k}{\partial x_1} & \frac{\partial f_k}{\partial x_2} & \cdots & \frac{\partial f_k}{\partial x_d} \end{bmatrix}$

### The Jacobian Matrix

**Key Property:** The derivative of a vector-valued function results in a **matrix** of size $k \times d$

\begin{align*}
\mathbf{J} = \begin{bmatrix} \nabla_\mathbf{x}^T f_1(\mathbf{x}) \\ \nabla_\mathbf{x}^T f_2(\mathbf{x}) \\ \vdots \\ \nabla_\mathbf{x}^T f_k(\mathbf{x}) \end{bmatrix}
\end{align*}

$\mathbf{J} = \begin{bmatrix} \nabla_\mathbf{x}^T f_1(\mathbf{x}) \\ \nabla_\mathbf{x}^T f_2(\mathbf{x}) \\ \vdots \\ \nabla_\mathbf{x}^T f_k(\mathbf{x}) \end{bmatrix}$

### Jacobian Matrix in Expanded Form (Full Detail)

The Jacobian matrix can be written explicitly with all elements as:
\mathbf{J} = \frac{d\mathbf{f}(\mathbf{x})}{d\mathbf{x}} = \begin{bmatrix} J_{11} & J_{12} & \cdots & J_{1d} \\ J_{21} & J_{22} & \cdots & J_{2d} \\ \vdots & \vdots & \ddots & \vdots \\ J_{k1} & J_{k2} & \cdots & J_{kd} \end{bmatrix}
$\mathbf{J} = \frac{d\mathbf{f}(\mathbf{x})}{d\mathbf{x}} = \begin{bmatrix} J_{11} & J_{12} & \cdots & J_{1d} \\ J_{21} & J_{22} & \cdots & J_{2d} \\ \vdots & \vdots & \ddots & \vdots \\ J_{k1} & J_{k2} & \cdots & J_{kd} \end{bmatrix}$

$J_{ij} = \frac{\partial f_i(\mathbf{x})}{\partial x_j} \quad \text{for } i = 1, 2, ..., k \text{ and } j = 1, 2, ..., d$

**Element Interpretation:**
- $J_{ij}$ = partial derivative of $i$-th function with respect to $j$-th variable
- **Row $i$:** Gradient of function $f_i(\mathbf{x})$
- **Column $j$:** Sensitivities of all functions to variable $x_j$

**Dimensions:**
- **Number of rows** = number of functions $k$

- **Number of columns** = number of input variables $d$
- **Number of columns** = number of input variables $d$
- **Number of columns** = number of input variables $d$- Total elements: $k \times d$


- **Number of columns** = number of input variables $d$
- **Total elements:** $k \times d$

## Computing the Jacobian: Detailed Example

### Setup

Let $\mathbf{x} = [x_1, x_2]^T$ be a 2-dimensional input vector.

Define three functions:

$f_1(\mathbf{x}) = 2x_1^2 + 3x_2 + 5$

$f_2(\mathbf{x}) = 4x_1^2 + 3x_1x_2 + 6x_2^2 + 4x_2 + 5$

$f_3(\mathbf{x}) = 4x_1^3 + 9x_1^2 + 6x_2^2 - 5x_1x_2 + 2$

$\frac{\partial f_1}{\partial x_1} = \frac{\partial(2x_1^2 + 3x_2 + 5)}{\partial x_1} = 4x_1$

$\frac{\partial f_1}{\partial x_2} = \frac{\partial(2x_1^2 + 3x_2 + 5)}{\partial x_2} = 3$

**Row 1 of Jacobian:** $[4x_1, 3]$

### Step 2: Compute Gradient of $f_2(\mathbf{x})$

$\frac{\partial f_2}{\partial x_1} = \frac{\partial(4x_1^2 + 3x_1x_2 + 6x_2^2 + 4x_2 + 5)}{\partial x_1} = 8x_1 + 3x_2$

$\frac{\partial f_2}{\partial x_2} = \frac{\partial(4x_1^2 + 3x_1x_2 + 6x_2^2 + 4x_2 + 5)}{\partial x_2} = 3x_1 + 12x_2 + 4$

**Row 2 of Jacobian:** $[8x_1 + 3x_2, 3x_1 + 12x_2 + 4]$

$\frac{\partial f_3}{\partial x_1} = \frac{\partial(4x_1^3 + 9x_1^2 + 6x_2^2 - 5x_1x_2 + 2)}{\partial x_1} = 12x_1^2 + 18x_1 - 5x_2$

$\frac{\partial f_3}{\partial x_2} = \frac{\partial(4x_1^3 + 9x_1^2 + 6x_2^2 - 5x_1x_2 + 2)}{\partial x_2} = 12x_2 - 5x_1$

**Row 3 of Jacobian:** $[12x_1^2 + 18x_1 - 5x_2, 12x_2 - 5x_1]$

### The Complete Jacobian Matrix

$\mathbf{J} = \frac{d\mathbf{f}(\mathbf{x})}{d\mathbf{x}} = \begin{bmatrix} 4x_1 & 3 \\ 8x_1 + 3x_2 & 3x_1 + 12x_2 + 4 \\ 12x_1^2 + 18x_1 - 5x_2 & 12x_2 - 5x_1 \end{bmatrix}$

**Dimensions:** $3 \times 2$ (3 functions, 2 input variables)

## Numerical Verification

In [1]:
import numpy as np

print("="*80)
print("JACOBIAN MATRIX VERIFICATION")
print("="*80)

# Define the three functions
def f1(x):
    return 2*x[0]**2 + 3*x[1] + 5

def f2(x):
    return 4*x[0]**2 + 3*x[0]*x[1] + 6*x[1]**2 + 4*x[1] + 5

def f3(x):
    return 4*x[0]**3 + 9*x[0]**2 + 6*x[1]**2 - 5*x[0]*x[1] + 2

# Vector-valued function
def f(x):
    return np.array([f1(x), f2(x), f3(x)])

# Analytical gradients
def df1_dx(x):
    return np.array([4*x[0], 3])

def df2_dx(x):
    return np.array([8*x[0] + 3*x[1], 3*x[0] + 12*x[1] + 4])

def df3_dx(x):
    return np.array([12*x[0]**2 + 18*x[0] - 5*x[1], 12*x[1] - 5*x[0]])

# Analytical Jacobian matrix
def jacobian_analytical(x):
    return np.array([df1_dx(x), df2_dx(x), df3_dx(x)])

# Numerical Jacobian (using finite differences)
def jacobian_numerical(x, epsilon=1e-5):
    k = 3  # number of functions
    d = 2  # number of variables
    J = np.zeros((k, d))
    
    for j in range(d):
        x_plus = x.copy()
        x_plus[j] += epsilon
        f_plus = f(x_plus)
        
        x_minus = x.copy()
        x_minus[j] -= epsilon
        f_minus = f(x_minus)
        
        J[:, j] = (f_plus - f_minus) / (2 * epsilon)
    
    return J

# Test point
x = np.array([1.0, 2.0])

print(f"\nTest point: x = {x}")
print(f"\nFunction values: f(x) = {f(x)}")

# Analytical Jacobian
J_analytical = jacobian_analytical(x)
print(f"\nAnalytical Jacobian Matrix:")
print(J_analytical)

# Numerical Jacobian
J_numerical = jacobian_numerical(x)
print(f"\nNumerical Jacobian Matrix:")
print(J_numerical)

# Difference
difference = np.linalg.norm(J_analytical - J_numerical)
print(f"\nDifference (Frobenius norm): {difference:.2e}")
print("\n✓ Jacobian matrices match!")

JACOBIAN MATRIX VERIFICATION

Test point: x = [1. 2.]

Function values: f(x) = [13. 47. 29.]

Analytical Jacobian Matrix:
[[ 4.  3.]
 [14. 31.]
 [20. 19.]]

Numerical Jacobian Matrix:
[[ 4.  3.]
 [14. 31.]
 [20. 19.]]

Difference (Frobenius norm): 4.38e-10

✓ Jacobian matrices match!


In [2]:
# Example with different test points
print("\n" + "="*80)
print("JACOBIAN AT MULTIPLE POINTS")
print("="*80)

test_points = [
    np.array([0.0, 0.0]),
    np.array([1.0, 1.0]),
    np.array([2.0, -1.0]),
    np.array([-1.0, 2.0])
]

for x in test_points:
    J = jacobian_analytical(x)
    print(f"\nAt x = {x}:")
    print(f"f(x) = {f(x)}")
    print(f"Jacobian =\n{J}")
    print("-" * 80)


JACOBIAN AT MULTIPLE POINTS

At x = [0. 0.]:
f(x) = [5. 5. 2.]
Jacobian =
[[0. 3.]
 [0. 4.]
 [0. 0.]]
--------------------------------------------------------------------------------

At x = [1. 1.]:
f(x) = [10. 22. 16.]
Jacobian =
[[ 4.  3.]
 [11. 19.]
 [25.  7.]]
--------------------------------------------------------------------------------

At x = [ 2. -1.]:
f(x) = [10. 17. 86.]
Jacobian =
[[  8.   3.]
 [ 13.  -2.]
 [ 89. -22.]]
--------------------------------------------------------------------------------

At x = [-1.  2.]:
f(x) = [13. 35. 41.]
Jacobian =
[[ -4.   3.]
 [ -2.  25.]
 [-16.  29.]]
--------------------------------------------------------------------------------


## Special Case: Linear Vector-Valued Function

### Linear Transformation: $\mathbf{y} = \mathbf{M}\mathbf{x}$

For a linear transformation where each function is:
$$f_i(\mathbf{x}) = m_{i1}x_1 + m_{i2}x_2 + \cdots + m_{id}x_d$$

**Jacobian simplifies to:**

$\mathbf{J} = \frac{d(\mathbf{M}\mathbf{x})}{d\mathbf{x}} = \mathbf{M}$

**Key Point:** For linear transformations, the Jacobian is exactly the transformation matrix!

This is a fundamental result showing that:
- The Jacobian matrix is the linear approximation of a nonlinear function at a point
- For linear functions, this approximation is exact everywhere

In [3]:
# Verify Jacobian = M for linear transformation
print("="*80)
print("LINEAR TRANSFORMATION: Jacobian = M")
print("="*80)

# Define a linear transformation: y = Mx
M = np.array([[2.0, 3.0],
              [1.0, 4.0],
              [5.0, -1.0]])

def f_linear(x):
    return M @ x

# Numerical Jacobian for linear function
def jacobian_numerical_linear(x, epsilon=1e-5):
    k = 3  # number of functions
    d = 2  # number of variables
    J = np.zeros((k, d))
    
    for j in range(d):
        x_plus = x.copy()
        x_plus[j] += epsilon
        f_plus = f_linear(x_plus)
        
        x_minus = x.copy()
        x_minus[j] -= epsilon
        f_minus = f_linear(x_minus)
        
        J[:, j] = (f_plus - f_minus) / (2 * epsilon)
    
    return J

print(f"\nTransformation matrix M:")
print(M)

x_test = np.array([1.5, 2.3])
print(f"\nFor any x = {x_test}:")
print(f"f(x) = M @ x = {f_linear(x_test)}")

# Numerical Jacobian
J_numeric = jacobian_numerical_linear(x_test, epsilon=1e-5)
print(f"\nNumerical Jacobian:")
print(J_numeric)

print(f"\nDifference from M: {np.linalg.norm(M - J_numeric):.2e}")
print("\n✓ For linear functions, Jacobian = M everywhere!")

LINEAR TRANSFORMATION: Jacobian = M

Transformation matrix M:
[[ 2.  3.]
 [ 1.  4.]
 [ 5. -1.]]

For any x = [1.5 2.3]:
f(x) = M @ x = [ 9.9 10.7  5.2]

Numerical Jacobian:
[[ 2.  3.]
 [ 1.  4.]
 [ 5. -1.]]

Difference from M: 1.07e-10

✓ For linear functions, Jacobian = M everywhere!


## Applications in Machine Learning

### 1. Neural Networks
In neural networks with multiple outputs, the Jacobian describes:
- How each output changes with each input
- Used in backpropagation algorithm
- Example: A network with 784 inputs (28×28 image) and 10 outputs (digit classes) has a Jacobian of size $10 \times 784$

### 2. System Linearization
The Jacobian provides the best linear approximation of a nonlinear system:

$\mathbf{f}(\mathbf{x}) \approx \mathbf{f}(\mathbf{x}_0) + \mathbf{J}(\mathbf{x}_0)(\mathbf{x} - \mathbf{x}_0)$

### 3. Sensitivity Analysis
- Large Jacobian elements = output sensitive to that input
- Small Jacobian elements = output insensitive
- Used to understand which inputs matter most

### 4. Optimization
- Newton's method for solving nonlinear systems requires the Jacobian
- Gauss-Newton method uses the Jacobian for nonlinear least squares

### 5. Change of Variables in Integration
In multivariable calculus, the determinant of the Jacobian (Jacobian determinant) accounts for volume scaling:

$\int_Y f(y) dy = \int_X f(g(x)) |\det(\mathbf{J}_g(x))| dx$

## Key Takeaways

| Concept | Description | Size |
|---------|-------------|------|
| **Scalar function** | $f: \mathbb{R}^d \to \mathbb{R}$ | Gradient is $d \times 1$ |
| **Vector function** | $\mathbf{f}: \mathbb{R}^d \to \mathbb{R}^k$ | Jacobian is $k \times d$ |
| **Jacobian element** | $J_{ij} = \frac{\partial f_i}{\partial x_j}$ | Partial derivative |
| **Each row** | Gradient of one function | Size $1 \times d$ |
| **Linear case** | $\mathbf{J} = \mathbf{M}$ (the transformation matrix) | Constant everywhere |
| **Nonlinear case** | $\mathbf{J}$ changes with $\mathbf{x}$ | Depends on evaluation point |

---

## Connected Concepts
- **Previous:** Partial derivatives, gradients, dot products
- **Next:** Hessian matrix (second derivatives), neural network backpropagation
- **Applications:** Optimization algorithms, deep learning, physics simulations